// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:22
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x47000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/mmcm_drp_regs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x47000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/mmcm_drp_regs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/mmcm_drp_regs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 13d49a523e5dd445357f540ac6bdd0a6bbdf34b3
//
// ===========================================================================


#ifndef __MMCM_DRP_REGS_H
#define __MMCM_DRP_REGS_H

#define MMCM_DRP_BASE 0x47000000UL
// --------------------------------------------------------------
// MMCM0STA
// 
#define MMCM_DRP_MMCM0STA_ADR (MMCM_DRP_BASE + 0x0000UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM0STA = (unsigned long*) MMCM_DRP_MMCM0STA_ADR;
#define S_MMCM_DRP_MMCM0STA (*SP_MMCM_DRP_MMCM0STA)
// bitfield: MMCM0STA_CLKIN_STOPPED
#define MMCM_DRP_MMCM0STA_CLKIN_STOPPED                   2UL
#define MMCM_DRP_MMCM0STA_CLKIN_STOPPED_BM                0x00000004UL
// bitfield: MMCM0STA_DRDY
#define MMCM_DRP_MMCM0STA_DRDY                            1UL
#define MMCM_DRP_MMCM0STA_DRDY_BM                         0x00000002UL
// bitfield: MMCM0STA_LOCKED
#define MMCM_DRP_MMCM0STA_LOCKED                          0UL
#define MMCM_DRP_MMCM0STA_LOCKED_BM                       0x00000001UL
// --------------------------------------------------------------
// MMCM0CTRL
// 
#define MMCM_DRP_MMCM0CTRL_ADR (MMCM_DRP_BASE + 0x0004UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM0CTRL = (unsigned long*) MMCM_DRP_MMCM0CTRL_ADR;
#define S_MMCM_DRP_MMCM0CTRL (*SP_MMCM_DRP_MMCM0CTRL)
// bitfield: MMCM0CTRL_RST
#define MMCM_DRP_MMCM0CTRL_RST                            0UL
#define MMCM_DRP_MMCM0CTRL_RST_BM                         0x00000001UL
// --------------------------------------------------------------
// DRP0CTRL
// 
#define MMCM_DRP_DRP0CTRL_ADR (MMCM_DRP_BASE + 0x0008UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0CTRL = (unsigned long*) MMCM_DRP_DRP0CTRL_ADR;
#define S_MMCM_DRP_DRP0CTRL (*SP_MMCM_DRP_DRP0CTRL)
// bitfield: DRP0CTRL_START
#define MMCM_DRP_DRP0CTRL_START                           0UL
#define MMCM_DRP_DRP0CTRL_START_BM                        0x00000001UL
// --------------------------------------------------------------
// DRP0STA
// 
#define MMCM_DRP_DRP0STA_ADR (MMCM_DRP_BASE + 0x000CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0STA = (unsigned long*) MMCM_DRP_DRP0STA_ADR;
#define S_MMCM_DRP_DRP0STA (*SP_MMCM_DRP_DRP0STA)
// bitfield: DRP0STA_BUSY
#define MMCM_DRP_DRP0STA_BUSY                             0UL
#define MMCM_DRP_DRP0STA_BUSY_BM                          0x00000001UL
// --------------------------------------------------------------
// DRP0CFG
// 
#define MMCM_DRP_DRP0CFG_ADR (MMCM_DRP_BASE + 0x0010UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0CFG = (unsigned long*) MMCM_DRP_DRP0CFG_ADR;
#define S_MMCM_DRP_DRP0CFG (*SP_MMCM_DRP_DRP0CFG)
// bitfield: DRP0CFG_NUMREGS
#define MMCM_DRP_DRP0CFG_NUMREGS                          0UL
#define MMCM_DRP_DRP0CFG_NUMREGS_BM                       0x0000000FUL
// --------------------------------------------------------------
// DRP0VALUE0
// 
#define MMCM_DRP_DRP0VALUE0_ADR (MMCM_DRP_BASE + 0x0014UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE0 = (unsigned long*) MMCM_DRP_DRP0VALUE0_ADR;
#define S_MMCM_DRP_DRP0VALUE0 (*SP_MMCM_DRP_DRP0VALUE0)
// bitfield: DRP0VALUE0_VALUE
#define MMCM_DRP_DRP0VALUE0_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE0_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST0
// 
#define MMCM_DRP_DRP0DEST0_ADR (MMCM_DRP_BASE + 0x0018UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST0 = (unsigned long*) MMCM_DRP_DRP0DEST0_ADR;
#define S_MMCM_DRP_DRP0DEST0 (*SP_MMCM_DRP_DRP0DEST0)
// bitfield: DRP0DEST0_ADDR
#define MMCM_DRP_DRP0DEST0_ADDR                           16UL
#define MMCM_DRP_DRP0DEST0_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST0_MASK
#define MMCM_DRP_DRP0DEST0_MASK                           0UL
#define MMCM_DRP_DRP0DEST0_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE1
// 
#define MMCM_DRP_DRP0VALUE1_ADR (MMCM_DRP_BASE + 0x001CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE1 = (unsigned long*) MMCM_DRP_DRP0VALUE1_ADR;
#define S_MMCM_DRP_DRP0VALUE1 (*SP_MMCM_DRP_DRP0VALUE1)
// bitfield: DRP0VALUE1_VALUE
#define MMCM_DRP_DRP0VALUE1_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE1_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST1
// 
#define MMCM_DRP_DRP0DEST1_ADR (MMCM_DRP_BASE + 0x0020UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST1 = (unsigned long*) MMCM_DRP_DRP0DEST1_ADR;
#define S_MMCM_DRP_DRP0DEST1 (*SP_MMCM_DRP_DRP0DEST1)
// bitfield: DRP0DEST1_ADDR
#define MMCM_DRP_DRP0DEST1_ADDR                           16UL
#define MMCM_DRP_DRP0DEST1_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST1_MASK
#define MMCM_DRP_DRP0DEST1_MASK                           0UL
#define MMCM_DRP_DRP0DEST1_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE2
// 
#define MMCM_DRP_DRP0VALUE2_ADR (MMCM_DRP_BASE + 0x0024UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE2 = (unsigned long*) MMCM_DRP_DRP0VALUE2_ADR;
#define S_MMCM_DRP_DRP0VALUE2 (*SP_MMCM_DRP_DRP0VALUE2)
// bitfield: DRP0VALUE2_VALUE
#define MMCM_DRP_DRP0VALUE2_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE2_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST2
// 
#define MMCM_DRP_DRP0DEST2_ADR (MMCM_DRP_BASE + 0x0028UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST2 = (unsigned long*) MMCM_DRP_DRP0DEST2_ADR;
#define S_MMCM_DRP_DRP0DEST2 (*SP_MMCM_DRP_DRP0DEST2)
// bitfield: DRP0DEST2_ADDR
#define MMCM_DRP_DRP0DEST2_ADDR                           16UL
#define MMCM_DRP_DRP0DEST2_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST2_MASK
#define MMCM_DRP_DRP0DEST2_MASK                           0UL
#define MMCM_DRP_DRP0DEST2_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE3
// 
#define MMCM_DRP_DRP0VALUE3_ADR (MMCM_DRP_BASE + 0x002CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE3 = (unsigned long*) MMCM_DRP_DRP0VALUE3_ADR;
#define S_MMCM_DRP_DRP0VALUE3 (*SP_MMCM_DRP_DRP0VALUE3)
// bitfield: DRP0VALUE3_VALUE
#define MMCM_DRP_DRP0VALUE3_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE3_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST3
// 
#define MMCM_DRP_DRP0DEST3_ADR (MMCM_DRP_BASE + 0x0030UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST3 = (unsigned long*) MMCM_DRP_DRP0DEST3_ADR;
#define S_MMCM_DRP_DRP0DEST3 (*SP_MMCM_DRP_DRP0DEST3)
// bitfield: DRP0DEST3_ADDR
#define MMCM_DRP_DRP0DEST3_ADDR                           16UL
#define MMCM_DRP_DRP0DEST3_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST3_MASK
#define MMCM_DRP_DRP0DEST3_MASK                           0UL
#define MMCM_DRP_DRP0DEST3_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE4
// 
#define MMCM_DRP_DRP0VALUE4_ADR (MMCM_DRP_BASE + 0x0034UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE4 = (unsigned long*) MMCM_DRP_DRP0VALUE4_ADR;
#define S_MMCM_DRP_DRP0VALUE4 (*SP_MMCM_DRP_DRP0VALUE4)
// bitfield: DRP0VALUE4_VALUE
#define MMCM_DRP_DRP0VALUE4_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE4_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST4
// 
#define MMCM_DRP_DRP0DEST4_ADR (MMCM_DRP_BASE + 0x0038UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST4 = (unsigned long*) MMCM_DRP_DRP0DEST4_ADR;
#define S_MMCM_DRP_DRP0DEST4 (*SP_MMCM_DRP_DRP0DEST4)
// bitfield: DRP0DEST4_ADDR
#define MMCM_DRP_DRP0DEST4_ADDR                           16UL
#define MMCM_DRP_DRP0DEST4_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST4_MASK
#define MMCM_DRP_DRP0DEST4_MASK                           0UL
#define MMCM_DRP_DRP0DEST4_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE5
// 
#define MMCM_DRP_DRP0VALUE5_ADR (MMCM_DRP_BASE + 0x003CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE5 = (unsigned long*) MMCM_DRP_DRP0VALUE5_ADR;
#define S_MMCM_DRP_DRP0VALUE5 (*SP_MMCM_DRP_DRP0VALUE5)
// bitfield: DRP0VALUE5_VALUE
#define MMCM_DRP_DRP0VALUE5_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE5_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST5
// 
#define MMCM_DRP_DRP0DEST5_ADR (MMCM_DRP_BASE + 0x0040UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST5 = (unsigned long*) MMCM_DRP_DRP0DEST5_ADR;
#define S_MMCM_DRP_DRP0DEST5 (*SP_MMCM_DRP_DRP0DEST5)
// bitfield: DRP0DEST5_ADDR
#define MMCM_DRP_DRP0DEST5_ADDR                           16UL
#define MMCM_DRP_DRP0DEST5_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST5_MASK
#define MMCM_DRP_DRP0DEST5_MASK                           0UL
#define MMCM_DRP_DRP0DEST5_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE6
// 
#define MMCM_DRP_DRP0VALUE6_ADR (MMCM_DRP_BASE + 0x0044UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE6 = (unsigned long*) MMCM_DRP_DRP0VALUE6_ADR;
#define S_MMCM_DRP_DRP0VALUE6 (*SP_MMCM_DRP_DRP0VALUE6)
// bitfield: DRP0VALUE6_VALUE
#define MMCM_DRP_DRP0VALUE6_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE6_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST6
// 
#define MMCM_DRP_DRP0DEST6_ADR (MMCM_DRP_BASE + 0x0048UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST6 = (unsigned long*) MMCM_DRP_DRP0DEST6_ADR;
#define S_MMCM_DRP_DRP0DEST6 (*SP_MMCM_DRP_DRP0DEST6)
// bitfield: DRP0DEST6_ADDR
#define MMCM_DRP_DRP0DEST6_ADDR                           16UL
#define MMCM_DRP_DRP0DEST6_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST6_MASK
#define MMCM_DRP_DRP0DEST6_MASK                           0UL
#define MMCM_DRP_DRP0DEST6_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE7
// 
#define MMCM_DRP_DRP0VALUE7_ADR (MMCM_DRP_BASE + 0x004CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE7 = (unsigned long*) MMCM_DRP_DRP0VALUE7_ADR;
#define S_MMCM_DRP_DRP0VALUE7 (*SP_MMCM_DRP_DRP0VALUE7)
// bitfield: DRP0VALUE7_VALUE
#define MMCM_DRP_DRP0VALUE7_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE7_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST7
// 
#define MMCM_DRP_DRP0DEST7_ADR (MMCM_DRP_BASE + 0x0050UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST7 = (unsigned long*) MMCM_DRP_DRP0DEST7_ADR;
#define S_MMCM_DRP_DRP0DEST7 (*SP_MMCM_DRP_DRP0DEST7)
// bitfield: DRP0DEST7_ADDR
#define MMCM_DRP_DRP0DEST7_ADDR                           16UL
#define MMCM_DRP_DRP0DEST7_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST7_MASK
#define MMCM_DRP_DRP0DEST7_MASK                           0UL
#define MMCM_DRP_DRP0DEST7_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE8
// 
#define MMCM_DRP_DRP0VALUE8_ADR (MMCM_DRP_BASE + 0x0054UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE8 = (unsigned long*) MMCM_DRP_DRP0VALUE8_ADR;
#define S_MMCM_DRP_DRP0VALUE8 (*SP_MMCM_DRP_DRP0VALUE8)
// bitfield: DRP0VALUE8_VALUE
#define MMCM_DRP_DRP0VALUE8_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE8_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST8
// 
#define MMCM_DRP_DRP0DEST8_ADR (MMCM_DRP_BASE + 0x0058UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST8 = (unsigned long*) MMCM_DRP_DRP0DEST8_ADR;
#define S_MMCM_DRP_DRP0DEST8 (*SP_MMCM_DRP_DRP0DEST8)
// bitfield: DRP0DEST8_ADDR
#define MMCM_DRP_DRP0DEST8_ADDR                           16UL
#define MMCM_DRP_DRP0DEST8_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST8_MASK
#define MMCM_DRP_DRP0DEST8_MASK                           0UL
#define MMCM_DRP_DRP0DEST8_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE9
// 
#define MMCM_DRP_DRP0VALUE9_ADR (MMCM_DRP_BASE + 0x005CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE9 = (unsigned long*) MMCM_DRP_DRP0VALUE9_ADR;
#define S_MMCM_DRP_DRP0VALUE9 (*SP_MMCM_DRP_DRP0VALUE9)
// bitfield: DRP0VALUE9_VALUE
#define MMCM_DRP_DRP0VALUE9_VALUE                         0UL
#define MMCM_DRP_DRP0VALUE9_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST9
// 
#define MMCM_DRP_DRP0DEST9_ADR (MMCM_DRP_BASE + 0x0060UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST9 = (unsigned long*) MMCM_DRP_DRP0DEST9_ADR;
#define S_MMCM_DRP_DRP0DEST9 (*SP_MMCM_DRP_DRP0DEST9)
// bitfield: DRP0DEST9_ADDR
#define MMCM_DRP_DRP0DEST9_ADDR                           16UL
#define MMCM_DRP_DRP0DEST9_ADDR_BM                        0x007F0000UL
// bitfield: DRP0DEST9_MASK
#define MMCM_DRP_DRP0DEST9_MASK                           0UL
#define MMCM_DRP_DRP0DEST9_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE10
// 
#define MMCM_DRP_DRP0VALUE10_ADR (MMCM_DRP_BASE + 0x0064UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE10 = (unsigned long*) MMCM_DRP_DRP0VALUE10_ADR;
#define S_MMCM_DRP_DRP0VALUE10 (*SP_MMCM_DRP_DRP0VALUE10)
// bitfield: DRP0VALUE10_VALUE
#define MMCM_DRP_DRP0VALUE10_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE10_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST10
// 
#define MMCM_DRP_DRP0DEST10_ADR (MMCM_DRP_BASE + 0x0068UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST10 = (unsigned long*) MMCM_DRP_DRP0DEST10_ADR;
#define S_MMCM_DRP_DRP0DEST10 (*SP_MMCM_DRP_DRP0DEST10)
// bitfield: DRP0DEST10_ADDR
#define MMCM_DRP_DRP0DEST10_ADDR                          16UL
#define MMCM_DRP_DRP0DEST10_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST10_MASK
#define MMCM_DRP_DRP0DEST10_MASK                          0UL
#define MMCM_DRP_DRP0DEST10_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE11
// 
#define MMCM_DRP_DRP0VALUE11_ADR (MMCM_DRP_BASE + 0x006CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE11 = (unsigned long*) MMCM_DRP_DRP0VALUE11_ADR;
#define S_MMCM_DRP_DRP0VALUE11 (*SP_MMCM_DRP_DRP0VALUE11)
// bitfield: DRP0VALUE11_VALUE
#define MMCM_DRP_DRP0VALUE11_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE11_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST11
// 
#define MMCM_DRP_DRP0DEST11_ADR (MMCM_DRP_BASE + 0x0070UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST11 = (unsigned long*) MMCM_DRP_DRP0DEST11_ADR;
#define S_MMCM_DRP_DRP0DEST11 (*SP_MMCM_DRP_DRP0DEST11)
// bitfield: DRP0DEST11_ADDR
#define MMCM_DRP_DRP0DEST11_ADDR                          16UL
#define MMCM_DRP_DRP0DEST11_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST11_MASK
#define MMCM_DRP_DRP0DEST11_MASK                          0UL
#define MMCM_DRP_DRP0DEST11_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE12
// 
#define MMCM_DRP_DRP0VALUE12_ADR (MMCM_DRP_BASE + 0x0074UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE12 = (unsigned long*) MMCM_DRP_DRP0VALUE12_ADR;
#define S_MMCM_DRP_DRP0VALUE12 (*SP_MMCM_DRP_DRP0VALUE12)
// bitfield: DRP0VALUE12_VALUE
#define MMCM_DRP_DRP0VALUE12_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE12_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST12
// 
#define MMCM_DRP_DRP0DEST12_ADR (MMCM_DRP_BASE + 0x0078UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST12 = (unsigned long*) MMCM_DRP_DRP0DEST12_ADR;
#define S_MMCM_DRP_DRP0DEST12 (*SP_MMCM_DRP_DRP0DEST12)
// bitfield: DRP0DEST12_ADDR
#define MMCM_DRP_DRP0DEST12_ADDR                          16UL
#define MMCM_DRP_DRP0DEST12_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST12_MASK
#define MMCM_DRP_DRP0DEST12_MASK                          0UL
#define MMCM_DRP_DRP0DEST12_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE13
// 
#define MMCM_DRP_DRP0VALUE13_ADR (MMCM_DRP_BASE + 0x007CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE13 = (unsigned long*) MMCM_DRP_DRP0VALUE13_ADR;
#define S_MMCM_DRP_DRP0VALUE13 (*SP_MMCM_DRP_DRP0VALUE13)
// bitfield: DRP0VALUE13_VALUE
#define MMCM_DRP_DRP0VALUE13_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE13_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST13
// 
#define MMCM_DRP_DRP0DEST13_ADR (MMCM_DRP_BASE + 0x0080UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST13 = (unsigned long*) MMCM_DRP_DRP0DEST13_ADR;
#define S_MMCM_DRP_DRP0DEST13 (*SP_MMCM_DRP_DRP0DEST13)
// bitfield: DRP0DEST13_ADDR
#define MMCM_DRP_DRP0DEST13_ADDR                          16UL
#define MMCM_DRP_DRP0DEST13_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST13_MASK
#define MMCM_DRP_DRP0DEST13_MASK                          0UL
#define MMCM_DRP_DRP0DEST13_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE14
// 
#define MMCM_DRP_DRP0VALUE14_ADR (MMCM_DRP_BASE + 0x0084UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE14 = (unsigned long*) MMCM_DRP_DRP0VALUE14_ADR;
#define S_MMCM_DRP_DRP0VALUE14 (*SP_MMCM_DRP_DRP0VALUE14)
// bitfield: DRP0VALUE14_VALUE
#define MMCM_DRP_DRP0VALUE14_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE14_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST14
// 
#define MMCM_DRP_DRP0DEST14_ADR (MMCM_DRP_BASE + 0x0088UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST14 = (unsigned long*) MMCM_DRP_DRP0DEST14_ADR;
#define S_MMCM_DRP_DRP0DEST14 (*SP_MMCM_DRP_DRP0DEST14)
// bitfield: DRP0DEST14_ADDR
#define MMCM_DRP_DRP0DEST14_ADDR                          16UL
#define MMCM_DRP_DRP0DEST14_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST14_MASK
#define MMCM_DRP_DRP0DEST14_MASK                          0UL
#define MMCM_DRP_DRP0DEST14_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP0VALUE15
// 
#define MMCM_DRP_DRP0VALUE15_ADR (MMCM_DRP_BASE + 0x008CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0VALUE15 = (unsigned long*) MMCM_DRP_DRP0VALUE15_ADR;
#define S_MMCM_DRP_DRP0VALUE15 (*SP_MMCM_DRP_DRP0VALUE15)
// bitfield: DRP0VALUE15_VALUE
#define MMCM_DRP_DRP0VALUE15_VALUE                        0UL
#define MMCM_DRP_DRP0VALUE15_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP0DEST15
// 
#define MMCM_DRP_DRP0DEST15_ADR (MMCM_DRP_BASE + 0x0090UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP0DEST15 = (unsigned long*) MMCM_DRP_DRP0DEST15_ADR;
#define S_MMCM_DRP_DRP0DEST15 (*SP_MMCM_DRP_DRP0DEST15)
// bitfield: DRP0DEST15_ADDR
#define MMCM_DRP_DRP0DEST15_ADDR                          16UL
#define MMCM_DRP_DRP0DEST15_ADDR_BM                       0x007F0000UL
// bitfield: DRP0DEST15_MASK
#define MMCM_DRP_DRP0DEST15_MASK                          0UL
#define MMCM_DRP_DRP0DEST15_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// MMCM1STA
// 
#define MMCM_DRP_MMCM1STA_ADR (MMCM_DRP_BASE + 0x0094UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM1STA = (unsigned long*) MMCM_DRP_MMCM1STA_ADR;
#define S_MMCM_DRP_MMCM1STA (*SP_MMCM_DRP_MMCM1STA)
// bitfield: MMCM1STA_CLKIN_STOPPED
#define MMCM_DRP_MMCM1STA_CLKIN_STOPPED                   2UL
#define MMCM_DRP_MMCM1STA_CLKIN_STOPPED_BM                0x00000004UL
// bitfield: MMCM1STA_DRDY
#define MMCM_DRP_MMCM1STA_DRDY                            1UL
#define MMCM_DRP_MMCM1STA_DRDY_BM                         0x00000002UL
// bitfield: MMCM1STA_LOCKED
#define MMCM_DRP_MMCM1STA_LOCKED                          0UL
#define MMCM_DRP_MMCM1STA_LOCKED_BM                       0x00000001UL
// --------------------------------------------------------------
// MMCM1CTRL
// 
#define MMCM_DRP_MMCM1CTRL_ADR (MMCM_DRP_BASE + 0x0098UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM1CTRL = (unsigned long*) MMCM_DRP_MMCM1CTRL_ADR;
#define S_MMCM_DRP_MMCM1CTRL (*SP_MMCM_DRP_MMCM1CTRL)
// bitfield: MMCM1CTRL_RST
#define MMCM_DRP_MMCM1CTRL_RST                            0UL
#define MMCM_DRP_MMCM1CTRL_RST_BM                         0x00000001UL
// --------------------------------------------------------------
// DRP1CTRL
// 
#define MMCM_DRP_DRP1CTRL_ADR (MMCM_DRP_BASE + 0x009CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1CTRL = (unsigned long*) MMCM_DRP_DRP1CTRL_ADR;
#define S_MMCM_DRP_DRP1CTRL (*SP_MMCM_DRP_DRP1CTRL)
// bitfield: DRP1CTRL_START
#define MMCM_DRP_DRP1CTRL_START                           0UL
#define MMCM_DRP_DRP1CTRL_START_BM                        0x00000001UL
// --------------------------------------------------------------
// DRP1STA
// 
#define MMCM_DRP_DRP1STA_ADR (MMCM_DRP_BASE + 0x00A0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1STA = (unsigned long*) MMCM_DRP_DRP1STA_ADR;
#define S_MMCM_DRP_DRP1STA (*SP_MMCM_DRP_DRP1STA)
// bitfield: DRP1STA_BUSY
#define MMCM_DRP_DRP1STA_BUSY                             0UL
#define MMCM_DRP_DRP1STA_BUSY_BM                          0x00000001UL
// --------------------------------------------------------------
// DRP1CFG
// 
#define MMCM_DRP_DRP1CFG_ADR (MMCM_DRP_BASE + 0x00A4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1CFG = (unsigned long*) MMCM_DRP_DRP1CFG_ADR;
#define S_MMCM_DRP_DRP1CFG (*SP_MMCM_DRP_DRP1CFG)
// bitfield: DRP1CFG_NUMREGS
#define MMCM_DRP_DRP1CFG_NUMREGS                          0UL
#define MMCM_DRP_DRP1CFG_NUMREGS_BM                       0x0000000FUL
// --------------------------------------------------------------
// DRP1VALUE0
// 
#define MMCM_DRP_DRP1VALUE0_ADR (MMCM_DRP_BASE + 0x00A8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE0 = (unsigned long*) MMCM_DRP_DRP1VALUE0_ADR;
#define S_MMCM_DRP_DRP1VALUE0 (*SP_MMCM_DRP_DRP1VALUE0)
// bitfield: DRP1VALUE0_VALUE
#define MMCM_DRP_DRP1VALUE0_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE0_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST0
// 
#define MMCM_DRP_DRP1DEST0_ADR (MMCM_DRP_BASE + 0x00ACUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST0 = (unsigned long*) MMCM_DRP_DRP1DEST0_ADR;
#define S_MMCM_DRP_DRP1DEST0 (*SP_MMCM_DRP_DRP1DEST0)
// bitfield: DRP1DEST0_ADDR
#define MMCM_DRP_DRP1DEST0_ADDR                           16UL
#define MMCM_DRP_DRP1DEST0_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST0_MASK
#define MMCM_DRP_DRP1DEST0_MASK                           0UL
#define MMCM_DRP_DRP1DEST0_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE1
// 
#define MMCM_DRP_DRP1VALUE1_ADR (MMCM_DRP_BASE + 0x00B0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE1 = (unsigned long*) MMCM_DRP_DRP1VALUE1_ADR;
#define S_MMCM_DRP_DRP1VALUE1 (*SP_MMCM_DRP_DRP1VALUE1)
// bitfield: DRP1VALUE1_VALUE
#define MMCM_DRP_DRP1VALUE1_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE1_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST1
// 
#define MMCM_DRP_DRP1DEST1_ADR (MMCM_DRP_BASE + 0x00B4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST1 = (unsigned long*) MMCM_DRP_DRP1DEST1_ADR;
#define S_MMCM_DRP_DRP1DEST1 (*SP_MMCM_DRP_DRP1DEST1)
// bitfield: DRP1DEST1_ADDR
#define MMCM_DRP_DRP1DEST1_ADDR                           16UL
#define MMCM_DRP_DRP1DEST1_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST1_MASK
#define MMCM_DRP_DRP1DEST1_MASK                           0UL
#define MMCM_DRP_DRP1DEST1_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE2
// 
#define MMCM_DRP_DRP1VALUE2_ADR (MMCM_DRP_BASE + 0x00B8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE2 = (unsigned long*) MMCM_DRP_DRP1VALUE2_ADR;
#define S_MMCM_DRP_DRP1VALUE2 (*SP_MMCM_DRP_DRP1VALUE2)
// bitfield: DRP1VALUE2_VALUE
#define MMCM_DRP_DRP1VALUE2_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE2_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST2
// 
#define MMCM_DRP_DRP1DEST2_ADR (MMCM_DRP_BASE + 0x00BCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST2 = (unsigned long*) MMCM_DRP_DRP1DEST2_ADR;
#define S_MMCM_DRP_DRP1DEST2 (*SP_MMCM_DRP_DRP1DEST2)
// bitfield: DRP1DEST2_ADDR
#define MMCM_DRP_DRP1DEST2_ADDR                           16UL
#define MMCM_DRP_DRP1DEST2_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST2_MASK
#define MMCM_DRP_DRP1DEST2_MASK                           0UL
#define MMCM_DRP_DRP1DEST2_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE3
// 
#define MMCM_DRP_DRP1VALUE3_ADR (MMCM_DRP_BASE + 0x00C0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE3 = (unsigned long*) MMCM_DRP_DRP1VALUE3_ADR;
#define S_MMCM_DRP_DRP1VALUE3 (*SP_MMCM_DRP_DRP1VALUE3)
// bitfield: DRP1VALUE3_VALUE
#define MMCM_DRP_DRP1VALUE3_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE3_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST3
// 
#define MMCM_DRP_DRP1DEST3_ADR (MMCM_DRP_BASE + 0x00C4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST3 = (unsigned long*) MMCM_DRP_DRP1DEST3_ADR;
#define S_MMCM_DRP_DRP1DEST3 (*SP_MMCM_DRP_DRP1DEST3)
// bitfield: DRP1DEST3_ADDR
#define MMCM_DRP_DRP1DEST3_ADDR                           16UL
#define MMCM_DRP_DRP1DEST3_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST3_MASK
#define MMCM_DRP_DRP1DEST3_MASK                           0UL
#define MMCM_DRP_DRP1DEST3_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE4
// 
#define MMCM_DRP_DRP1VALUE4_ADR (MMCM_DRP_BASE + 0x00C8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE4 = (unsigned long*) MMCM_DRP_DRP1VALUE4_ADR;
#define S_MMCM_DRP_DRP1VALUE4 (*SP_MMCM_DRP_DRP1VALUE4)
// bitfield: DRP1VALUE4_VALUE
#define MMCM_DRP_DRP1VALUE4_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE4_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST4
// 
#define MMCM_DRP_DRP1DEST4_ADR (MMCM_DRP_BASE + 0x00CCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST4 = (unsigned long*) MMCM_DRP_DRP1DEST4_ADR;
#define S_MMCM_DRP_DRP1DEST4 (*SP_MMCM_DRP_DRP1DEST4)
// bitfield: DRP1DEST4_ADDR
#define MMCM_DRP_DRP1DEST4_ADDR                           16UL
#define MMCM_DRP_DRP1DEST4_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST4_MASK
#define MMCM_DRP_DRP1DEST4_MASK                           0UL
#define MMCM_DRP_DRP1DEST4_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE5
// 
#define MMCM_DRP_DRP1VALUE5_ADR (MMCM_DRP_BASE + 0x00D0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE5 = (unsigned long*) MMCM_DRP_DRP1VALUE5_ADR;
#define S_MMCM_DRP_DRP1VALUE5 (*SP_MMCM_DRP_DRP1VALUE5)
// bitfield: DRP1VALUE5_VALUE
#define MMCM_DRP_DRP1VALUE5_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE5_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST5
// 
#define MMCM_DRP_DRP1DEST5_ADR (MMCM_DRP_BASE + 0x00D4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST5 = (unsigned long*) MMCM_DRP_DRP1DEST5_ADR;
#define S_MMCM_DRP_DRP1DEST5 (*SP_MMCM_DRP_DRP1DEST5)
// bitfield: DRP1DEST5_ADDR
#define MMCM_DRP_DRP1DEST5_ADDR                           16UL
#define MMCM_DRP_DRP1DEST5_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST5_MASK
#define MMCM_DRP_DRP1DEST5_MASK                           0UL
#define MMCM_DRP_DRP1DEST5_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE6
// 
#define MMCM_DRP_DRP1VALUE6_ADR (MMCM_DRP_BASE + 0x00D8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE6 = (unsigned long*) MMCM_DRP_DRP1VALUE6_ADR;
#define S_MMCM_DRP_DRP1VALUE6 (*SP_MMCM_DRP_DRP1VALUE6)
// bitfield: DRP1VALUE6_VALUE
#define MMCM_DRP_DRP1VALUE6_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE6_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST6
// 
#define MMCM_DRP_DRP1DEST6_ADR (MMCM_DRP_BASE + 0x00DCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST6 = (unsigned long*) MMCM_DRP_DRP1DEST6_ADR;
#define S_MMCM_DRP_DRP1DEST6 (*SP_MMCM_DRP_DRP1DEST6)
// bitfield: DRP1DEST6_ADDR
#define MMCM_DRP_DRP1DEST6_ADDR                           16UL
#define MMCM_DRP_DRP1DEST6_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST6_MASK
#define MMCM_DRP_DRP1DEST6_MASK                           0UL
#define MMCM_DRP_DRP1DEST6_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE7
// 
#define MMCM_DRP_DRP1VALUE7_ADR (MMCM_DRP_BASE + 0x00E0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE7 = (unsigned long*) MMCM_DRP_DRP1VALUE7_ADR;
#define S_MMCM_DRP_DRP1VALUE7 (*SP_MMCM_DRP_DRP1VALUE7)
// bitfield: DRP1VALUE7_VALUE
#define MMCM_DRP_DRP1VALUE7_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE7_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST7
// 
#define MMCM_DRP_DRP1DEST7_ADR (MMCM_DRP_BASE + 0x00E4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST7 = (unsigned long*) MMCM_DRP_DRP1DEST7_ADR;
#define S_MMCM_DRP_DRP1DEST7 (*SP_MMCM_DRP_DRP1DEST7)
// bitfield: DRP1DEST7_ADDR
#define MMCM_DRP_DRP1DEST7_ADDR                           16UL
#define MMCM_DRP_DRP1DEST7_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST7_MASK
#define MMCM_DRP_DRP1DEST7_MASK                           0UL
#define MMCM_DRP_DRP1DEST7_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE8
// 
#define MMCM_DRP_DRP1VALUE8_ADR (MMCM_DRP_BASE + 0x00E8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE8 = (unsigned long*) MMCM_DRP_DRP1VALUE8_ADR;
#define S_MMCM_DRP_DRP1VALUE8 (*SP_MMCM_DRP_DRP1VALUE8)
// bitfield: DRP1VALUE8_VALUE
#define MMCM_DRP_DRP1VALUE8_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE8_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST8
// 
#define MMCM_DRP_DRP1DEST8_ADR (MMCM_DRP_BASE + 0x00ECUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST8 = (unsigned long*) MMCM_DRP_DRP1DEST8_ADR;
#define S_MMCM_DRP_DRP1DEST8 (*SP_MMCM_DRP_DRP1DEST8)
// bitfield: DRP1DEST8_ADDR
#define MMCM_DRP_DRP1DEST8_ADDR                           16UL
#define MMCM_DRP_DRP1DEST8_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST8_MASK
#define MMCM_DRP_DRP1DEST8_MASK                           0UL
#define MMCM_DRP_DRP1DEST8_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE9
// 
#define MMCM_DRP_DRP1VALUE9_ADR (MMCM_DRP_BASE + 0x00F0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE9 = (unsigned long*) MMCM_DRP_DRP1VALUE9_ADR;
#define S_MMCM_DRP_DRP1VALUE9 (*SP_MMCM_DRP_DRP1VALUE9)
// bitfield: DRP1VALUE9_VALUE
#define MMCM_DRP_DRP1VALUE9_VALUE                         0UL
#define MMCM_DRP_DRP1VALUE9_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST9
// 
#define MMCM_DRP_DRP1DEST9_ADR (MMCM_DRP_BASE + 0x00F4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST9 = (unsigned long*) MMCM_DRP_DRP1DEST9_ADR;
#define S_MMCM_DRP_DRP1DEST9 (*SP_MMCM_DRP_DRP1DEST9)
// bitfield: DRP1DEST9_ADDR
#define MMCM_DRP_DRP1DEST9_ADDR                           16UL
#define MMCM_DRP_DRP1DEST9_ADDR_BM                        0x007F0000UL
// bitfield: DRP1DEST9_MASK
#define MMCM_DRP_DRP1DEST9_MASK                           0UL
#define MMCM_DRP_DRP1DEST9_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE10
// 
#define MMCM_DRP_DRP1VALUE10_ADR (MMCM_DRP_BASE + 0x00F8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE10 = (unsigned long*) MMCM_DRP_DRP1VALUE10_ADR;
#define S_MMCM_DRP_DRP1VALUE10 (*SP_MMCM_DRP_DRP1VALUE10)
// bitfield: DRP1VALUE10_VALUE
#define MMCM_DRP_DRP1VALUE10_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE10_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST10
// 
#define MMCM_DRP_DRP1DEST10_ADR (MMCM_DRP_BASE + 0x00FCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST10 = (unsigned long*) MMCM_DRP_DRP1DEST10_ADR;
#define S_MMCM_DRP_DRP1DEST10 (*SP_MMCM_DRP_DRP1DEST10)
// bitfield: DRP1DEST10_ADDR
#define MMCM_DRP_DRP1DEST10_ADDR                          16UL
#define MMCM_DRP_DRP1DEST10_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST10_MASK
#define MMCM_DRP_DRP1DEST10_MASK                          0UL
#define MMCM_DRP_DRP1DEST10_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE11
// 
#define MMCM_DRP_DRP1VALUE11_ADR (MMCM_DRP_BASE + 0x0100UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE11 = (unsigned long*) MMCM_DRP_DRP1VALUE11_ADR;
#define S_MMCM_DRP_DRP1VALUE11 (*SP_MMCM_DRP_DRP1VALUE11)
// bitfield: DRP1VALUE11_VALUE
#define MMCM_DRP_DRP1VALUE11_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE11_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST11
// 
#define MMCM_DRP_DRP1DEST11_ADR (MMCM_DRP_BASE + 0x0104UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST11 = (unsigned long*) MMCM_DRP_DRP1DEST11_ADR;
#define S_MMCM_DRP_DRP1DEST11 (*SP_MMCM_DRP_DRP1DEST11)
// bitfield: DRP1DEST11_ADDR
#define MMCM_DRP_DRP1DEST11_ADDR                          16UL
#define MMCM_DRP_DRP1DEST11_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST11_MASK
#define MMCM_DRP_DRP1DEST11_MASK                          0UL
#define MMCM_DRP_DRP1DEST11_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE12
// 
#define MMCM_DRP_DRP1VALUE12_ADR (MMCM_DRP_BASE + 0x0108UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE12 = (unsigned long*) MMCM_DRP_DRP1VALUE12_ADR;
#define S_MMCM_DRP_DRP1VALUE12 (*SP_MMCM_DRP_DRP1VALUE12)
// bitfield: DRP1VALUE12_VALUE
#define MMCM_DRP_DRP1VALUE12_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE12_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST12
// 
#define MMCM_DRP_DRP1DEST12_ADR (MMCM_DRP_BASE + 0x010CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST12 = (unsigned long*) MMCM_DRP_DRP1DEST12_ADR;
#define S_MMCM_DRP_DRP1DEST12 (*SP_MMCM_DRP_DRP1DEST12)
// bitfield: DRP1DEST12_ADDR
#define MMCM_DRP_DRP1DEST12_ADDR                          16UL
#define MMCM_DRP_DRP1DEST12_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST12_MASK
#define MMCM_DRP_DRP1DEST12_MASK                          0UL
#define MMCM_DRP_DRP1DEST12_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE13
// 
#define MMCM_DRP_DRP1VALUE13_ADR (MMCM_DRP_BASE + 0x0110UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE13 = (unsigned long*) MMCM_DRP_DRP1VALUE13_ADR;
#define S_MMCM_DRP_DRP1VALUE13 (*SP_MMCM_DRP_DRP1VALUE13)
// bitfield: DRP1VALUE13_VALUE
#define MMCM_DRP_DRP1VALUE13_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE13_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST13
// 
#define MMCM_DRP_DRP1DEST13_ADR (MMCM_DRP_BASE + 0x0114UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST13 = (unsigned long*) MMCM_DRP_DRP1DEST13_ADR;
#define S_MMCM_DRP_DRP1DEST13 (*SP_MMCM_DRP_DRP1DEST13)
// bitfield: DRP1DEST13_ADDR
#define MMCM_DRP_DRP1DEST13_ADDR                          16UL
#define MMCM_DRP_DRP1DEST13_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST13_MASK
#define MMCM_DRP_DRP1DEST13_MASK                          0UL
#define MMCM_DRP_DRP1DEST13_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE14
// 
#define MMCM_DRP_DRP1VALUE14_ADR (MMCM_DRP_BASE + 0x0118UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE14 = (unsigned long*) MMCM_DRP_DRP1VALUE14_ADR;
#define S_MMCM_DRP_DRP1VALUE14 (*SP_MMCM_DRP_DRP1VALUE14)
// bitfield: DRP1VALUE14_VALUE
#define MMCM_DRP_DRP1VALUE14_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE14_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST14
// 
#define MMCM_DRP_DRP1DEST14_ADR (MMCM_DRP_BASE + 0x011CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST14 = (unsigned long*) MMCM_DRP_DRP1DEST14_ADR;
#define S_MMCM_DRP_DRP1DEST14 (*SP_MMCM_DRP_DRP1DEST14)
// bitfield: DRP1DEST14_ADDR
#define MMCM_DRP_DRP1DEST14_ADDR                          16UL
#define MMCM_DRP_DRP1DEST14_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST14_MASK
#define MMCM_DRP_DRP1DEST14_MASK                          0UL
#define MMCM_DRP_DRP1DEST14_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP1VALUE15
// 
#define MMCM_DRP_DRP1VALUE15_ADR (MMCM_DRP_BASE + 0x0120UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1VALUE15 = (unsigned long*) MMCM_DRP_DRP1VALUE15_ADR;
#define S_MMCM_DRP_DRP1VALUE15 (*SP_MMCM_DRP_DRP1VALUE15)
// bitfield: DRP1VALUE15_VALUE
#define MMCM_DRP_DRP1VALUE15_VALUE                        0UL
#define MMCM_DRP_DRP1VALUE15_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP1DEST15
// 
#define MMCM_DRP_DRP1DEST15_ADR (MMCM_DRP_BASE + 0x0124UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP1DEST15 = (unsigned long*) MMCM_DRP_DRP1DEST15_ADR;
#define S_MMCM_DRP_DRP1DEST15 (*SP_MMCM_DRP_DRP1DEST15)
// bitfield: DRP1DEST15_ADDR
#define MMCM_DRP_DRP1DEST15_ADDR                          16UL
#define MMCM_DRP_DRP1DEST15_ADDR_BM                       0x007F0000UL
// bitfield: DRP1DEST15_MASK
#define MMCM_DRP_DRP1DEST15_MASK                          0UL
#define MMCM_DRP_DRP1DEST15_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// MMCM2STA
// 
#define MMCM_DRP_MMCM2STA_ADR (MMCM_DRP_BASE + 0x0128UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM2STA = (unsigned long*) MMCM_DRP_MMCM2STA_ADR;
#define S_MMCM_DRP_MMCM2STA (*SP_MMCM_DRP_MMCM2STA)
// bitfield: MMCM2STA_CLKIN_STOPPED
#define MMCM_DRP_MMCM2STA_CLKIN_STOPPED                   2UL
#define MMCM_DRP_MMCM2STA_CLKIN_STOPPED_BM                0x00000004UL
// bitfield: MMCM2STA_DRDY
#define MMCM_DRP_MMCM2STA_DRDY                            1UL
#define MMCM_DRP_MMCM2STA_DRDY_BM                         0x00000002UL
// bitfield: MMCM2STA_LOCKED
#define MMCM_DRP_MMCM2STA_LOCKED                          0UL
#define MMCM_DRP_MMCM2STA_LOCKED_BM                       0x00000001UL
// --------------------------------------------------------------
// MMCM2CTRL
// 
#define MMCM_DRP_MMCM2CTRL_ADR (MMCM_DRP_BASE + 0x012CUL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM2CTRL = (unsigned long*) MMCM_DRP_MMCM2CTRL_ADR;
#define S_MMCM_DRP_MMCM2CTRL (*SP_MMCM_DRP_MMCM2CTRL)
// bitfield: MMCM2CTRL_RST
#define MMCM_DRP_MMCM2CTRL_RST                            0UL
#define MMCM_DRP_MMCM2CTRL_RST_BM                         0x00000001UL
// --------------------------------------------------------------
// DRP2CTRL
// 
#define MMCM_DRP_DRP2CTRL_ADR (MMCM_DRP_BASE + 0x0130UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2CTRL = (unsigned long*) MMCM_DRP_DRP2CTRL_ADR;
#define S_MMCM_DRP_DRP2CTRL (*SP_MMCM_DRP_DRP2CTRL)
// bitfield: DRP2CTRL_START
#define MMCM_DRP_DRP2CTRL_START                           0UL
#define MMCM_DRP_DRP2CTRL_START_BM                        0x00000001UL
// --------------------------------------------------------------
// DRP2STA
// 
#define MMCM_DRP_DRP2STA_ADR (MMCM_DRP_BASE + 0x0134UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2STA = (unsigned long*) MMCM_DRP_DRP2STA_ADR;
#define S_MMCM_DRP_DRP2STA (*SP_MMCM_DRP_DRP2STA)
// bitfield: DRP2STA_BUSY
#define MMCM_DRP_DRP2STA_BUSY                             0UL
#define MMCM_DRP_DRP2STA_BUSY_BM                          0x00000001UL
// --------------------------------------------------------------
// DRP2CFG
// 
#define MMCM_DRP_DRP2CFG_ADR (MMCM_DRP_BASE + 0x0138UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2CFG = (unsigned long*) MMCM_DRP_DRP2CFG_ADR;
#define S_MMCM_DRP_DRP2CFG (*SP_MMCM_DRP_DRP2CFG)
// bitfield: DRP2CFG_NUMREGS
#define MMCM_DRP_DRP2CFG_NUMREGS                          0UL
#define MMCM_DRP_DRP2CFG_NUMREGS_BM                       0x0000000FUL
// --------------------------------------------------------------
// DRP2VALUE0
// 
#define MMCM_DRP_DRP2VALUE0_ADR (MMCM_DRP_BASE + 0x013CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE0 = (unsigned long*) MMCM_DRP_DRP2VALUE0_ADR;
#define S_MMCM_DRP_DRP2VALUE0 (*SP_MMCM_DRP_DRP2VALUE0)
// bitfield: DRP2VALUE0_VALUE
#define MMCM_DRP_DRP2VALUE0_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE0_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST0
// 
#define MMCM_DRP_DRP2DEST0_ADR (MMCM_DRP_BASE + 0x0140UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST0 = (unsigned long*) MMCM_DRP_DRP2DEST0_ADR;
#define S_MMCM_DRP_DRP2DEST0 (*SP_MMCM_DRP_DRP2DEST0)
// bitfield: DRP2DEST0_ADDR
#define MMCM_DRP_DRP2DEST0_ADDR                           16UL
#define MMCM_DRP_DRP2DEST0_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST0_MASK
#define MMCM_DRP_DRP2DEST0_MASK                           0UL
#define MMCM_DRP_DRP2DEST0_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE1
// 
#define MMCM_DRP_DRP2VALUE1_ADR (MMCM_DRP_BASE + 0x0144UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE1 = (unsigned long*) MMCM_DRP_DRP2VALUE1_ADR;
#define S_MMCM_DRP_DRP2VALUE1 (*SP_MMCM_DRP_DRP2VALUE1)
// bitfield: DRP2VALUE1_VALUE
#define MMCM_DRP_DRP2VALUE1_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE1_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST1
// 
#define MMCM_DRP_DRP2DEST1_ADR (MMCM_DRP_BASE + 0x0148UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST1 = (unsigned long*) MMCM_DRP_DRP2DEST1_ADR;
#define S_MMCM_DRP_DRP2DEST1 (*SP_MMCM_DRP_DRP2DEST1)
// bitfield: DRP2DEST1_ADDR
#define MMCM_DRP_DRP2DEST1_ADDR                           16UL
#define MMCM_DRP_DRP2DEST1_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST1_MASK
#define MMCM_DRP_DRP2DEST1_MASK                           0UL
#define MMCM_DRP_DRP2DEST1_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE2
// 
#define MMCM_DRP_DRP2VALUE2_ADR (MMCM_DRP_BASE + 0x014CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE2 = (unsigned long*) MMCM_DRP_DRP2VALUE2_ADR;
#define S_MMCM_DRP_DRP2VALUE2 (*SP_MMCM_DRP_DRP2VALUE2)
// bitfield: DRP2VALUE2_VALUE
#define MMCM_DRP_DRP2VALUE2_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE2_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST2
// 
#define MMCM_DRP_DRP2DEST2_ADR (MMCM_DRP_BASE + 0x0150UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST2 = (unsigned long*) MMCM_DRP_DRP2DEST2_ADR;
#define S_MMCM_DRP_DRP2DEST2 (*SP_MMCM_DRP_DRP2DEST2)
// bitfield: DRP2DEST2_ADDR
#define MMCM_DRP_DRP2DEST2_ADDR                           16UL
#define MMCM_DRP_DRP2DEST2_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST2_MASK
#define MMCM_DRP_DRP2DEST2_MASK                           0UL
#define MMCM_DRP_DRP2DEST2_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE3
// 
#define MMCM_DRP_DRP2VALUE3_ADR (MMCM_DRP_BASE + 0x0154UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE3 = (unsigned long*) MMCM_DRP_DRP2VALUE3_ADR;
#define S_MMCM_DRP_DRP2VALUE3 (*SP_MMCM_DRP_DRP2VALUE3)
// bitfield: DRP2VALUE3_VALUE
#define MMCM_DRP_DRP2VALUE3_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE3_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST3
// 
#define MMCM_DRP_DRP2DEST3_ADR (MMCM_DRP_BASE + 0x0158UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST3 = (unsigned long*) MMCM_DRP_DRP2DEST3_ADR;
#define S_MMCM_DRP_DRP2DEST3 (*SP_MMCM_DRP_DRP2DEST3)
// bitfield: DRP2DEST3_ADDR
#define MMCM_DRP_DRP2DEST3_ADDR                           16UL
#define MMCM_DRP_DRP2DEST3_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST3_MASK
#define MMCM_DRP_DRP2DEST3_MASK                           0UL
#define MMCM_DRP_DRP2DEST3_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE4
// 
#define MMCM_DRP_DRP2VALUE4_ADR (MMCM_DRP_BASE + 0x015CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE4 = (unsigned long*) MMCM_DRP_DRP2VALUE4_ADR;
#define S_MMCM_DRP_DRP2VALUE4 (*SP_MMCM_DRP_DRP2VALUE4)
// bitfield: DRP2VALUE4_VALUE
#define MMCM_DRP_DRP2VALUE4_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE4_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST4
// 
#define MMCM_DRP_DRP2DEST4_ADR (MMCM_DRP_BASE + 0x0160UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST4 = (unsigned long*) MMCM_DRP_DRP2DEST4_ADR;
#define S_MMCM_DRP_DRP2DEST4 (*SP_MMCM_DRP_DRP2DEST4)
// bitfield: DRP2DEST4_ADDR
#define MMCM_DRP_DRP2DEST4_ADDR                           16UL
#define MMCM_DRP_DRP2DEST4_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST4_MASK
#define MMCM_DRP_DRP2DEST4_MASK                           0UL
#define MMCM_DRP_DRP2DEST4_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE5
// 
#define MMCM_DRP_DRP2VALUE5_ADR (MMCM_DRP_BASE + 0x0164UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE5 = (unsigned long*) MMCM_DRP_DRP2VALUE5_ADR;
#define S_MMCM_DRP_DRP2VALUE5 (*SP_MMCM_DRP_DRP2VALUE5)
// bitfield: DRP2VALUE5_VALUE
#define MMCM_DRP_DRP2VALUE5_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE5_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST5
// 
#define MMCM_DRP_DRP2DEST5_ADR (MMCM_DRP_BASE + 0x0168UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST5 = (unsigned long*) MMCM_DRP_DRP2DEST5_ADR;
#define S_MMCM_DRP_DRP2DEST5 (*SP_MMCM_DRP_DRP2DEST5)
// bitfield: DRP2DEST5_ADDR
#define MMCM_DRP_DRP2DEST5_ADDR                           16UL
#define MMCM_DRP_DRP2DEST5_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST5_MASK
#define MMCM_DRP_DRP2DEST5_MASK                           0UL
#define MMCM_DRP_DRP2DEST5_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE6
// 
#define MMCM_DRP_DRP2VALUE6_ADR (MMCM_DRP_BASE + 0x016CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE6 = (unsigned long*) MMCM_DRP_DRP2VALUE6_ADR;
#define S_MMCM_DRP_DRP2VALUE6 (*SP_MMCM_DRP_DRP2VALUE6)
// bitfield: DRP2VALUE6_VALUE
#define MMCM_DRP_DRP2VALUE6_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE6_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST6
// 
#define MMCM_DRP_DRP2DEST6_ADR (MMCM_DRP_BASE + 0x0170UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST6 = (unsigned long*) MMCM_DRP_DRP2DEST6_ADR;
#define S_MMCM_DRP_DRP2DEST6 (*SP_MMCM_DRP_DRP2DEST6)
// bitfield: DRP2DEST6_ADDR
#define MMCM_DRP_DRP2DEST6_ADDR                           16UL
#define MMCM_DRP_DRP2DEST6_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST6_MASK
#define MMCM_DRP_DRP2DEST6_MASK                           0UL
#define MMCM_DRP_DRP2DEST6_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE7
// 
#define MMCM_DRP_DRP2VALUE7_ADR (MMCM_DRP_BASE + 0x0174UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE7 = (unsigned long*) MMCM_DRP_DRP2VALUE7_ADR;
#define S_MMCM_DRP_DRP2VALUE7 (*SP_MMCM_DRP_DRP2VALUE7)
// bitfield: DRP2VALUE7_VALUE
#define MMCM_DRP_DRP2VALUE7_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE7_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST7
// 
#define MMCM_DRP_DRP2DEST7_ADR (MMCM_DRP_BASE + 0x0178UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST7 = (unsigned long*) MMCM_DRP_DRP2DEST7_ADR;
#define S_MMCM_DRP_DRP2DEST7 (*SP_MMCM_DRP_DRP2DEST7)
// bitfield: DRP2DEST7_ADDR
#define MMCM_DRP_DRP2DEST7_ADDR                           16UL
#define MMCM_DRP_DRP2DEST7_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST7_MASK
#define MMCM_DRP_DRP2DEST7_MASK                           0UL
#define MMCM_DRP_DRP2DEST7_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE8
// 
#define MMCM_DRP_DRP2VALUE8_ADR (MMCM_DRP_BASE + 0x017CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE8 = (unsigned long*) MMCM_DRP_DRP2VALUE8_ADR;
#define S_MMCM_DRP_DRP2VALUE8 (*SP_MMCM_DRP_DRP2VALUE8)
// bitfield: DRP2VALUE8_VALUE
#define MMCM_DRP_DRP2VALUE8_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE8_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST8
// 
#define MMCM_DRP_DRP2DEST8_ADR (MMCM_DRP_BASE + 0x0180UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST8 = (unsigned long*) MMCM_DRP_DRP2DEST8_ADR;
#define S_MMCM_DRP_DRP2DEST8 (*SP_MMCM_DRP_DRP2DEST8)
// bitfield: DRP2DEST8_ADDR
#define MMCM_DRP_DRP2DEST8_ADDR                           16UL
#define MMCM_DRP_DRP2DEST8_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST8_MASK
#define MMCM_DRP_DRP2DEST8_MASK                           0UL
#define MMCM_DRP_DRP2DEST8_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE9
// 
#define MMCM_DRP_DRP2VALUE9_ADR (MMCM_DRP_BASE + 0x0184UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE9 = (unsigned long*) MMCM_DRP_DRP2VALUE9_ADR;
#define S_MMCM_DRP_DRP2VALUE9 (*SP_MMCM_DRP_DRP2VALUE9)
// bitfield: DRP2VALUE9_VALUE
#define MMCM_DRP_DRP2VALUE9_VALUE                         0UL
#define MMCM_DRP_DRP2VALUE9_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST9
// 
#define MMCM_DRP_DRP2DEST9_ADR (MMCM_DRP_BASE + 0x0188UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST9 = (unsigned long*) MMCM_DRP_DRP2DEST9_ADR;
#define S_MMCM_DRP_DRP2DEST9 (*SP_MMCM_DRP_DRP2DEST9)
// bitfield: DRP2DEST9_ADDR
#define MMCM_DRP_DRP2DEST9_ADDR                           16UL
#define MMCM_DRP_DRP2DEST9_ADDR_BM                        0x007F0000UL
// bitfield: DRP2DEST9_MASK
#define MMCM_DRP_DRP2DEST9_MASK                           0UL
#define MMCM_DRP_DRP2DEST9_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE10
// 
#define MMCM_DRP_DRP2VALUE10_ADR (MMCM_DRP_BASE + 0x018CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE10 = (unsigned long*) MMCM_DRP_DRP2VALUE10_ADR;
#define S_MMCM_DRP_DRP2VALUE10 (*SP_MMCM_DRP_DRP2VALUE10)
// bitfield: DRP2VALUE10_VALUE
#define MMCM_DRP_DRP2VALUE10_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE10_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST10
// 
#define MMCM_DRP_DRP2DEST10_ADR (MMCM_DRP_BASE + 0x0190UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST10 = (unsigned long*) MMCM_DRP_DRP2DEST10_ADR;
#define S_MMCM_DRP_DRP2DEST10 (*SP_MMCM_DRP_DRP2DEST10)
// bitfield: DRP2DEST10_ADDR
#define MMCM_DRP_DRP2DEST10_ADDR                          16UL
#define MMCM_DRP_DRP2DEST10_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST10_MASK
#define MMCM_DRP_DRP2DEST10_MASK                          0UL
#define MMCM_DRP_DRP2DEST10_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE11
// 
#define MMCM_DRP_DRP2VALUE11_ADR (MMCM_DRP_BASE + 0x0194UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE11 = (unsigned long*) MMCM_DRP_DRP2VALUE11_ADR;
#define S_MMCM_DRP_DRP2VALUE11 (*SP_MMCM_DRP_DRP2VALUE11)
// bitfield: DRP2VALUE11_VALUE
#define MMCM_DRP_DRP2VALUE11_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE11_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST11
// 
#define MMCM_DRP_DRP2DEST11_ADR (MMCM_DRP_BASE + 0x0198UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST11 = (unsigned long*) MMCM_DRP_DRP2DEST11_ADR;
#define S_MMCM_DRP_DRP2DEST11 (*SP_MMCM_DRP_DRP2DEST11)
// bitfield: DRP2DEST11_ADDR
#define MMCM_DRP_DRP2DEST11_ADDR                          16UL
#define MMCM_DRP_DRP2DEST11_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST11_MASK
#define MMCM_DRP_DRP2DEST11_MASK                          0UL
#define MMCM_DRP_DRP2DEST11_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE12
// 
#define MMCM_DRP_DRP2VALUE12_ADR (MMCM_DRP_BASE + 0x019CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE12 = (unsigned long*) MMCM_DRP_DRP2VALUE12_ADR;
#define S_MMCM_DRP_DRP2VALUE12 (*SP_MMCM_DRP_DRP2VALUE12)
// bitfield: DRP2VALUE12_VALUE
#define MMCM_DRP_DRP2VALUE12_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE12_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST12
// 
#define MMCM_DRP_DRP2DEST12_ADR (MMCM_DRP_BASE + 0x01A0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST12 = (unsigned long*) MMCM_DRP_DRP2DEST12_ADR;
#define S_MMCM_DRP_DRP2DEST12 (*SP_MMCM_DRP_DRP2DEST12)
// bitfield: DRP2DEST12_ADDR
#define MMCM_DRP_DRP2DEST12_ADDR                          16UL
#define MMCM_DRP_DRP2DEST12_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST12_MASK
#define MMCM_DRP_DRP2DEST12_MASK                          0UL
#define MMCM_DRP_DRP2DEST12_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE13
// 
#define MMCM_DRP_DRP2VALUE13_ADR (MMCM_DRP_BASE + 0x01A4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE13 = (unsigned long*) MMCM_DRP_DRP2VALUE13_ADR;
#define S_MMCM_DRP_DRP2VALUE13 (*SP_MMCM_DRP_DRP2VALUE13)
// bitfield: DRP2VALUE13_VALUE
#define MMCM_DRP_DRP2VALUE13_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE13_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST13
// 
#define MMCM_DRP_DRP2DEST13_ADR (MMCM_DRP_BASE + 0x01A8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST13 = (unsigned long*) MMCM_DRP_DRP2DEST13_ADR;
#define S_MMCM_DRP_DRP2DEST13 (*SP_MMCM_DRP_DRP2DEST13)
// bitfield: DRP2DEST13_ADDR
#define MMCM_DRP_DRP2DEST13_ADDR                          16UL
#define MMCM_DRP_DRP2DEST13_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST13_MASK
#define MMCM_DRP_DRP2DEST13_MASK                          0UL
#define MMCM_DRP_DRP2DEST13_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE14
// 
#define MMCM_DRP_DRP2VALUE14_ADR (MMCM_DRP_BASE + 0x01ACUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE14 = (unsigned long*) MMCM_DRP_DRP2VALUE14_ADR;
#define S_MMCM_DRP_DRP2VALUE14 (*SP_MMCM_DRP_DRP2VALUE14)
// bitfield: DRP2VALUE14_VALUE
#define MMCM_DRP_DRP2VALUE14_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE14_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST14
// 
#define MMCM_DRP_DRP2DEST14_ADR (MMCM_DRP_BASE + 0x01B0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST14 = (unsigned long*) MMCM_DRP_DRP2DEST14_ADR;
#define S_MMCM_DRP_DRP2DEST14 (*SP_MMCM_DRP_DRP2DEST14)
// bitfield: DRP2DEST14_ADDR
#define MMCM_DRP_DRP2DEST14_ADDR                          16UL
#define MMCM_DRP_DRP2DEST14_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST14_MASK
#define MMCM_DRP_DRP2DEST14_MASK                          0UL
#define MMCM_DRP_DRP2DEST14_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP2VALUE15
// 
#define MMCM_DRP_DRP2VALUE15_ADR (MMCM_DRP_BASE + 0x01B4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2VALUE15 = (unsigned long*) MMCM_DRP_DRP2VALUE15_ADR;
#define S_MMCM_DRP_DRP2VALUE15 (*SP_MMCM_DRP_DRP2VALUE15)
// bitfield: DRP2VALUE15_VALUE
#define MMCM_DRP_DRP2VALUE15_VALUE                        0UL
#define MMCM_DRP_DRP2VALUE15_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP2DEST15
// 
#define MMCM_DRP_DRP2DEST15_ADR (MMCM_DRP_BASE + 0x01B8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP2DEST15 = (unsigned long*) MMCM_DRP_DRP2DEST15_ADR;
#define S_MMCM_DRP_DRP2DEST15 (*SP_MMCM_DRP_DRP2DEST15)
// bitfield: DRP2DEST15_ADDR
#define MMCM_DRP_DRP2DEST15_ADDR                          16UL
#define MMCM_DRP_DRP2DEST15_ADDR_BM                       0x007F0000UL
// bitfield: DRP2DEST15_MASK
#define MMCM_DRP_DRP2DEST15_MASK                          0UL
#define MMCM_DRP_DRP2DEST15_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// MMCM3STA
// 
#define MMCM_DRP_MMCM3STA_ADR (MMCM_DRP_BASE + 0x01BCUL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM3STA = (unsigned long*) MMCM_DRP_MMCM3STA_ADR;
#define S_MMCM_DRP_MMCM3STA (*SP_MMCM_DRP_MMCM3STA)
// bitfield: MMCM3STA_CLKIN_STOPPED
#define MMCM_DRP_MMCM3STA_CLKIN_STOPPED                   2UL
#define MMCM_DRP_MMCM3STA_CLKIN_STOPPED_BM                0x00000004UL
// bitfield: MMCM3STA_DRDY
#define MMCM_DRP_MMCM3STA_DRDY                            1UL
#define MMCM_DRP_MMCM3STA_DRDY_BM                         0x00000002UL
// bitfield: MMCM3STA_LOCKED
#define MMCM_DRP_MMCM3STA_LOCKED                          0UL
#define MMCM_DRP_MMCM3STA_LOCKED_BM                       0x00000001UL
// --------------------------------------------------------------
// MMCM3CTRL
// 
#define MMCM_DRP_MMCM3CTRL_ADR (MMCM_DRP_BASE + 0x01C0UL)
static volatile unsigned long* const SP_MMCM_DRP_MMCM3CTRL = (unsigned long*) MMCM_DRP_MMCM3CTRL_ADR;
#define S_MMCM_DRP_MMCM3CTRL (*SP_MMCM_DRP_MMCM3CTRL)
// bitfield: MMCM3CTRL_RST
#define MMCM_DRP_MMCM3CTRL_RST                            0UL
#define MMCM_DRP_MMCM3CTRL_RST_BM                         0x00000001UL
// --------------------------------------------------------------
// DRP3CTRL
// 
#define MMCM_DRP_DRP3CTRL_ADR (MMCM_DRP_BASE + 0x01C4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3CTRL = (unsigned long*) MMCM_DRP_DRP3CTRL_ADR;
#define S_MMCM_DRP_DRP3CTRL (*SP_MMCM_DRP_DRP3CTRL)
// bitfield: DRP3CTRL_START
#define MMCM_DRP_DRP3CTRL_START                           0UL
#define MMCM_DRP_DRP3CTRL_START_BM                        0x00000001UL
// --------------------------------------------------------------
// DRP3STA
// 
#define MMCM_DRP_DRP3STA_ADR (MMCM_DRP_BASE + 0x01C8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3STA = (unsigned long*) MMCM_DRP_DRP3STA_ADR;
#define S_MMCM_DRP_DRP3STA (*SP_MMCM_DRP_DRP3STA)
// bitfield: DRP3STA_BUSY
#define MMCM_DRP_DRP3STA_BUSY                             0UL
#define MMCM_DRP_DRP3STA_BUSY_BM                          0x00000001UL
// --------------------------------------------------------------
// DRP3CFG
// 
#define MMCM_DRP_DRP3CFG_ADR (MMCM_DRP_BASE + 0x01CCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3CFG = (unsigned long*) MMCM_DRP_DRP3CFG_ADR;
#define S_MMCM_DRP_DRP3CFG (*SP_MMCM_DRP_DRP3CFG)
// bitfield: DRP3CFG_NUMREGS
#define MMCM_DRP_DRP3CFG_NUMREGS                          0UL
#define MMCM_DRP_DRP3CFG_NUMREGS_BM                       0x0000000FUL
// --------------------------------------------------------------
// DRP3VALUE0
// 
#define MMCM_DRP_DRP3VALUE0_ADR (MMCM_DRP_BASE + 0x01D0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE0 = (unsigned long*) MMCM_DRP_DRP3VALUE0_ADR;
#define S_MMCM_DRP_DRP3VALUE0 (*SP_MMCM_DRP_DRP3VALUE0)
// bitfield: DRP3VALUE0_VALUE
#define MMCM_DRP_DRP3VALUE0_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE0_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST0
// 
#define MMCM_DRP_DRP3DEST0_ADR (MMCM_DRP_BASE + 0x01D4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST0 = (unsigned long*) MMCM_DRP_DRP3DEST0_ADR;
#define S_MMCM_DRP_DRP3DEST0 (*SP_MMCM_DRP_DRP3DEST0)
// bitfield: DRP3DEST0_ADDR
#define MMCM_DRP_DRP3DEST0_ADDR                           16UL
#define MMCM_DRP_DRP3DEST0_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST0_MASK
#define MMCM_DRP_DRP3DEST0_MASK                           0UL
#define MMCM_DRP_DRP3DEST0_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE1
// 
#define MMCM_DRP_DRP3VALUE1_ADR (MMCM_DRP_BASE + 0x01D8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE1 = (unsigned long*) MMCM_DRP_DRP3VALUE1_ADR;
#define S_MMCM_DRP_DRP3VALUE1 (*SP_MMCM_DRP_DRP3VALUE1)
// bitfield: DRP3VALUE1_VALUE
#define MMCM_DRP_DRP3VALUE1_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE1_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST1
// 
#define MMCM_DRP_DRP3DEST1_ADR (MMCM_DRP_BASE + 0x01DCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST1 = (unsigned long*) MMCM_DRP_DRP3DEST1_ADR;
#define S_MMCM_DRP_DRP3DEST1 (*SP_MMCM_DRP_DRP3DEST1)
// bitfield: DRP3DEST1_ADDR
#define MMCM_DRP_DRP3DEST1_ADDR                           16UL
#define MMCM_DRP_DRP3DEST1_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST1_MASK
#define MMCM_DRP_DRP3DEST1_MASK                           0UL
#define MMCM_DRP_DRP3DEST1_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE2
// 
#define MMCM_DRP_DRP3VALUE2_ADR (MMCM_DRP_BASE + 0x01E0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE2 = (unsigned long*) MMCM_DRP_DRP3VALUE2_ADR;
#define S_MMCM_DRP_DRP3VALUE2 (*SP_MMCM_DRP_DRP3VALUE2)
// bitfield: DRP3VALUE2_VALUE
#define MMCM_DRP_DRP3VALUE2_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE2_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST2
// 
#define MMCM_DRP_DRP3DEST2_ADR (MMCM_DRP_BASE + 0x01E4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST2 = (unsigned long*) MMCM_DRP_DRP3DEST2_ADR;
#define S_MMCM_DRP_DRP3DEST2 (*SP_MMCM_DRP_DRP3DEST2)
// bitfield: DRP3DEST2_ADDR
#define MMCM_DRP_DRP3DEST2_ADDR                           16UL
#define MMCM_DRP_DRP3DEST2_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST2_MASK
#define MMCM_DRP_DRP3DEST2_MASK                           0UL
#define MMCM_DRP_DRP3DEST2_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE3
// 
#define MMCM_DRP_DRP3VALUE3_ADR (MMCM_DRP_BASE + 0x01E8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE3 = (unsigned long*) MMCM_DRP_DRP3VALUE3_ADR;
#define S_MMCM_DRP_DRP3VALUE3 (*SP_MMCM_DRP_DRP3VALUE3)
// bitfield: DRP3VALUE3_VALUE
#define MMCM_DRP_DRP3VALUE3_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE3_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST3
// 
#define MMCM_DRP_DRP3DEST3_ADR (MMCM_DRP_BASE + 0x01ECUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST3 = (unsigned long*) MMCM_DRP_DRP3DEST3_ADR;
#define S_MMCM_DRP_DRP3DEST3 (*SP_MMCM_DRP_DRP3DEST3)
// bitfield: DRP3DEST3_ADDR
#define MMCM_DRP_DRP3DEST3_ADDR                           16UL
#define MMCM_DRP_DRP3DEST3_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST3_MASK
#define MMCM_DRP_DRP3DEST3_MASK                           0UL
#define MMCM_DRP_DRP3DEST3_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE4
// 
#define MMCM_DRP_DRP3VALUE4_ADR (MMCM_DRP_BASE + 0x01F0UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE4 = (unsigned long*) MMCM_DRP_DRP3VALUE4_ADR;
#define S_MMCM_DRP_DRP3VALUE4 (*SP_MMCM_DRP_DRP3VALUE4)
// bitfield: DRP3VALUE4_VALUE
#define MMCM_DRP_DRP3VALUE4_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE4_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST4
// 
#define MMCM_DRP_DRP3DEST4_ADR (MMCM_DRP_BASE + 0x01F4UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST4 = (unsigned long*) MMCM_DRP_DRP3DEST4_ADR;
#define S_MMCM_DRP_DRP3DEST4 (*SP_MMCM_DRP_DRP3DEST4)
// bitfield: DRP3DEST4_ADDR
#define MMCM_DRP_DRP3DEST4_ADDR                           16UL
#define MMCM_DRP_DRP3DEST4_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST4_MASK
#define MMCM_DRP_DRP3DEST4_MASK                           0UL
#define MMCM_DRP_DRP3DEST4_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE5
// 
#define MMCM_DRP_DRP3VALUE5_ADR (MMCM_DRP_BASE + 0x01F8UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE5 = (unsigned long*) MMCM_DRP_DRP3VALUE5_ADR;
#define S_MMCM_DRP_DRP3VALUE5 (*SP_MMCM_DRP_DRP3VALUE5)
// bitfield: DRP3VALUE5_VALUE
#define MMCM_DRP_DRP3VALUE5_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE5_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST5
// 
#define MMCM_DRP_DRP3DEST5_ADR (MMCM_DRP_BASE + 0x01FCUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST5 = (unsigned long*) MMCM_DRP_DRP3DEST5_ADR;
#define S_MMCM_DRP_DRP3DEST5 (*SP_MMCM_DRP_DRP3DEST5)
// bitfield: DRP3DEST5_ADDR
#define MMCM_DRP_DRP3DEST5_ADDR                           16UL
#define MMCM_DRP_DRP3DEST5_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST5_MASK
#define MMCM_DRP_DRP3DEST5_MASK                           0UL
#define MMCM_DRP_DRP3DEST5_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE6
// 
#define MMCM_DRP_DRP3VALUE6_ADR (MMCM_DRP_BASE + 0x0200UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE6 = (unsigned long*) MMCM_DRP_DRP3VALUE6_ADR;
#define S_MMCM_DRP_DRP3VALUE6 (*SP_MMCM_DRP_DRP3VALUE6)
// bitfield: DRP3VALUE6_VALUE
#define MMCM_DRP_DRP3VALUE6_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE6_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST6
// 
#define MMCM_DRP_DRP3DEST6_ADR (MMCM_DRP_BASE + 0x0204UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST6 = (unsigned long*) MMCM_DRP_DRP3DEST6_ADR;
#define S_MMCM_DRP_DRP3DEST6 (*SP_MMCM_DRP_DRP3DEST6)
// bitfield: DRP3DEST6_ADDR
#define MMCM_DRP_DRP3DEST6_ADDR                           16UL
#define MMCM_DRP_DRP3DEST6_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST6_MASK
#define MMCM_DRP_DRP3DEST6_MASK                           0UL
#define MMCM_DRP_DRP3DEST6_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE7
// 
#define MMCM_DRP_DRP3VALUE7_ADR (MMCM_DRP_BASE + 0x0208UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE7 = (unsigned long*) MMCM_DRP_DRP3VALUE7_ADR;
#define S_MMCM_DRP_DRP3VALUE7 (*SP_MMCM_DRP_DRP3VALUE7)
// bitfield: DRP3VALUE7_VALUE
#define MMCM_DRP_DRP3VALUE7_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE7_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST7
// 
#define MMCM_DRP_DRP3DEST7_ADR (MMCM_DRP_BASE + 0x020CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST7 = (unsigned long*) MMCM_DRP_DRP3DEST7_ADR;
#define S_MMCM_DRP_DRP3DEST7 (*SP_MMCM_DRP_DRP3DEST7)
// bitfield: DRP3DEST7_ADDR
#define MMCM_DRP_DRP3DEST7_ADDR                           16UL
#define MMCM_DRP_DRP3DEST7_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST7_MASK
#define MMCM_DRP_DRP3DEST7_MASK                           0UL
#define MMCM_DRP_DRP3DEST7_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE8
// 
#define MMCM_DRP_DRP3VALUE8_ADR (MMCM_DRP_BASE + 0x0210UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE8 = (unsigned long*) MMCM_DRP_DRP3VALUE8_ADR;
#define S_MMCM_DRP_DRP3VALUE8 (*SP_MMCM_DRP_DRP3VALUE8)
// bitfield: DRP3VALUE8_VALUE
#define MMCM_DRP_DRP3VALUE8_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE8_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST8
// 
#define MMCM_DRP_DRP3DEST8_ADR (MMCM_DRP_BASE + 0x0214UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST8 = (unsigned long*) MMCM_DRP_DRP3DEST8_ADR;
#define S_MMCM_DRP_DRP3DEST8 (*SP_MMCM_DRP_DRP3DEST8)
// bitfield: DRP3DEST8_ADDR
#define MMCM_DRP_DRP3DEST8_ADDR                           16UL
#define MMCM_DRP_DRP3DEST8_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST8_MASK
#define MMCM_DRP_DRP3DEST8_MASK                           0UL
#define MMCM_DRP_DRP3DEST8_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE9
// 
#define MMCM_DRP_DRP3VALUE9_ADR (MMCM_DRP_BASE + 0x0218UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE9 = (unsigned long*) MMCM_DRP_DRP3VALUE9_ADR;
#define S_MMCM_DRP_DRP3VALUE9 (*SP_MMCM_DRP_DRP3VALUE9)
// bitfield: DRP3VALUE9_VALUE
#define MMCM_DRP_DRP3VALUE9_VALUE                         0UL
#define MMCM_DRP_DRP3VALUE9_VALUE_BM                      0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST9
// 
#define MMCM_DRP_DRP3DEST9_ADR (MMCM_DRP_BASE + 0x021CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST9 = (unsigned long*) MMCM_DRP_DRP3DEST9_ADR;
#define S_MMCM_DRP_DRP3DEST9 (*SP_MMCM_DRP_DRP3DEST9)
// bitfield: DRP3DEST9_ADDR
#define MMCM_DRP_DRP3DEST9_ADDR                           16UL
#define MMCM_DRP_DRP3DEST9_ADDR_BM                        0x007F0000UL
// bitfield: DRP3DEST9_MASK
#define MMCM_DRP_DRP3DEST9_MASK                           0UL
#define MMCM_DRP_DRP3DEST9_MASK_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE10
// 
#define MMCM_DRP_DRP3VALUE10_ADR (MMCM_DRP_BASE + 0x0220UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE10 = (unsigned long*) MMCM_DRP_DRP3VALUE10_ADR;
#define S_MMCM_DRP_DRP3VALUE10 (*SP_MMCM_DRP_DRP3VALUE10)
// bitfield: DRP3VALUE10_VALUE
#define MMCM_DRP_DRP3VALUE10_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE10_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST10
// 
#define MMCM_DRP_DRP3DEST10_ADR (MMCM_DRP_BASE + 0x0224UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST10 = (unsigned long*) MMCM_DRP_DRP3DEST10_ADR;
#define S_MMCM_DRP_DRP3DEST10 (*SP_MMCM_DRP_DRP3DEST10)
// bitfield: DRP3DEST10_ADDR
#define MMCM_DRP_DRP3DEST10_ADDR                          16UL
#define MMCM_DRP_DRP3DEST10_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST10_MASK
#define MMCM_DRP_DRP3DEST10_MASK                          0UL
#define MMCM_DRP_DRP3DEST10_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE11
// 
#define MMCM_DRP_DRP3VALUE11_ADR (MMCM_DRP_BASE + 0x0228UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE11 = (unsigned long*) MMCM_DRP_DRP3VALUE11_ADR;
#define S_MMCM_DRP_DRP3VALUE11 (*SP_MMCM_DRP_DRP3VALUE11)
// bitfield: DRP3VALUE11_VALUE
#define MMCM_DRP_DRP3VALUE11_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE11_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST11
// 
#define MMCM_DRP_DRP3DEST11_ADR (MMCM_DRP_BASE + 0x022CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST11 = (unsigned long*) MMCM_DRP_DRP3DEST11_ADR;
#define S_MMCM_DRP_DRP3DEST11 (*SP_MMCM_DRP_DRP3DEST11)
// bitfield: DRP3DEST11_ADDR
#define MMCM_DRP_DRP3DEST11_ADDR                          16UL
#define MMCM_DRP_DRP3DEST11_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST11_MASK
#define MMCM_DRP_DRP3DEST11_MASK                          0UL
#define MMCM_DRP_DRP3DEST11_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE12
// 
#define MMCM_DRP_DRP3VALUE12_ADR (MMCM_DRP_BASE + 0x0230UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE12 = (unsigned long*) MMCM_DRP_DRP3VALUE12_ADR;
#define S_MMCM_DRP_DRP3VALUE12 (*SP_MMCM_DRP_DRP3VALUE12)
// bitfield: DRP3VALUE12_VALUE
#define MMCM_DRP_DRP3VALUE12_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE12_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST12
// 
#define MMCM_DRP_DRP3DEST12_ADR (MMCM_DRP_BASE + 0x0234UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST12 = (unsigned long*) MMCM_DRP_DRP3DEST12_ADR;
#define S_MMCM_DRP_DRP3DEST12 (*SP_MMCM_DRP_DRP3DEST12)
// bitfield: DRP3DEST12_ADDR
#define MMCM_DRP_DRP3DEST12_ADDR                          16UL
#define MMCM_DRP_DRP3DEST12_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST12_MASK
#define MMCM_DRP_DRP3DEST12_MASK                          0UL
#define MMCM_DRP_DRP3DEST12_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE13
// 
#define MMCM_DRP_DRP3VALUE13_ADR (MMCM_DRP_BASE + 0x0238UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE13 = (unsigned long*) MMCM_DRP_DRP3VALUE13_ADR;
#define S_MMCM_DRP_DRP3VALUE13 (*SP_MMCM_DRP_DRP3VALUE13)
// bitfield: DRP3VALUE13_VALUE
#define MMCM_DRP_DRP3VALUE13_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE13_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST13
// 
#define MMCM_DRP_DRP3DEST13_ADR (MMCM_DRP_BASE + 0x023CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST13 = (unsigned long*) MMCM_DRP_DRP3DEST13_ADR;
#define S_MMCM_DRP_DRP3DEST13 (*SP_MMCM_DRP_DRP3DEST13)
// bitfield: DRP3DEST13_ADDR
#define MMCM_DRP_DRP3DEST13_ADDR                          16UL
#define MMCM_DRP_DRP3DEST13_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST13_MASK
#define MMCM_DRP_DRP3DEST13_MASK                          0UL
#define MMCM_DRP_DRP3DEST13_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE14
// 
#define MMCM_DRP_DRP3VALUE14_ADR (MMCM_DRP_BASE + 0x0240UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE14 = (unsigned long*) MMCM_DRP_DRP3VALUE14_ADR;
#define S_MMCM_DRP_DRP3VALUE14 (*SP_MMCM_DRP_DRP3VALUE14)
// bitfield: DRP3VALUE14_VALUE
#define MMCM_DRP_DRP3VALUE14_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE14_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST14
// 
#define MMCM_DRP_DRP3DEST14_ADR (MMCM_DRP_BASE + 0x0244UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST14 = (unsigned long*) MMCM_DRP_DRP3DEST14_ADR;
#define S_MMCM_DRP_DRP3DEST14 (*SP_MMCM_DRP_DRP3DEST14)
// bitfield: DRP3DEST14_ADDR
#define MMCM_DRP_DRP3DEST14_ADDR                          16UL
#define MMCM_DRP_DRP3DEST14_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST14_MASK
#define MMCM_DRP_DRP3DEST14_MASK                          0UL
#define MMCM_DRP_DRP3DEST14_MASK_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// DRP3VALUE15
// 
#define MMCM_DRP_DRP3VALUE15_ADR (MMCM_DRP_BASE + 0x0248UL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3VALUE15 = (unsigned long*) MMCM_DRP_DRP3VALUE15_ADR;
#define S_MMCM_DRP_DRP3VALUE15 (*SP_MMCM_DRP_DRP3VALUE15)
// bitfield: DRP3VALUE15_VALUE
#define MMCM_DRP_DRP3VALUE15_VALUE                        0UL
#define MMCM_DRP_DRP3VALUE15_VALUE_BM                     0x0000FFFFUL
// --------------------------------------------------------------
// DRP3DEST15
// 
#define MMCM_DRP_DRP3DEST15_ADR (MMCM_DRP_BASE + 0x024CUL)
static volatile unsigned long* const SP_MMCM_DRP_DRP3DEST15 = (unsigned long*) MMCM_DRP_DRP3DEST15_ADR;
#define S_MMCM_DRP_DRP3DEST15 (*SP_MMCM_DRP_DRP3DEST15)
// bitfield: DRP3DEST15_ADDR
#define MMCM_DRP_DRP3DEST15_ADDR                          16UL
#define MMCM_DRP_DRP3DEST15_ADDR_BM                       0x007F0000UL
// bitfield: DRP3DEST15_MASK
#define MMCM_DRP_DRP3DEST15_MASK                          0UL
#define MMCM_DRP_DRP3DEST15_MASK_BM                       0x0000FFFFUL

#endif
