// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:21
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40092000 -dat_sz 16 -sub 128 -ramreg -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/generic/doc/ram_registers.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40092000 -dat_sz 16 -sub 128 -ramreg -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/generic/doc/ram_registers.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/generic/doc/ram_registers.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 15b8a32569204575a2dca5047edb178aaff0b7dd
//
// ===========================================================================


#ifndef __PBE_GENERIC_RAM_REGS_H
#define __PBE_GENERIC_RAM_REGS_H

#define PBE_GENERIC_RAM_BASE 0x40092000UL
// --------------------------------------------------------------
// PHY
// 
#define PBE_GENERIC_RAM_PHY_ADR (PBE_GENERIC_RAM_BASE + 0x0020UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PHY = (unsigned short*) PBE_GENERIC_RAM_PHY_ADR;
#define S_PBE_GENERIC_RAM_PHY (*SP_PBE_GENERIC_RAM_PHY)
// bitfield: PHY_RFESEL
#define PBE_GENERIC_RAM_PHY_RFESEL                               3UL
#define PBE_GENERIC_RAM_PHY_RFESEL_BM                            0x0038UL
// enums for bitfield PHY_RFESEL (width: 3)UL
#define PBE_GENERIC_RAM_PHY_RFESEL_1M                            0x0UL
#define PBE_GENERIC_RAM_PHY_RFESEL_2M                            0x1UL
#define PBE_GENERIC_RAM_PHY_RFESEL_CODED_125K                    0x2UL
#define PBE_GENERIC_RAM_PHY_RFESEL_CODED_500K                    0x3UL
// bitfield: PHY_MCESEL
#define PBE_GENERIC_RAM_PHY_MCESEL                               0UL
#define PBE_GENERIC_RAM_PHY_MCESEL_BM                            0x0007UL
// enums for bitfield PHY_MCESEL (width: 3)UL
#define PBE_GENERIC_RAM_PHY_MCESEL_1M                            0x0UL
#define PBE_GENERIC_RAM_PHY_MCESEL_2M                            0x1UL
#define PBE_GENERIC_RAM_PHY_MCESEL_CODED_125K                    0x2UL
#define PBE_GENERIC_RAM_PHY_MCESEL_CODED_500K                    0x3UL
// --------------------------------------------------------------
// SYNTHCALTIMEOUT
// 
#define PBE_GENERIC_RAM_SYNTHCALTIMEOUT_ADR (PBE_GENERIC_RAM_BASE + 0x0022UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_SYNTHCALTIMEOUT = (unsigned short*) PBE_GENERIC_RAM_SYNTHCALTIMEOUT_ADR;
#define S_PBE_GENERIC_RAM_SYNTHCALTIMEOUT (*SP_PBE_GENERIC_RAM_SYNTHCALTIMEOUT)
// bitfield: SYNTHCALTIMEOUT_VAL
#define PBE_GENERIC_RAM_SYNTHCALTIMEOUT_VAL                      0UL
#define PBE_GENERIC_RAM_SYNTHCALTIMEOUT_VAL_BM                   0xFFFFUL
// --------------------------------------------------------------
// PKTCFG
// 
#define PBE_GENERIC_RAM_PKTCFG_ADR (PBE_GENERIC_RAM_BASE + 0x0024UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PKTCFG = (unsigned short*) PBE_GENERIC_RAM_PKTCFG_ADR;
#define S_PBE_GENERIC_RAM_PKTCFG (*SP_PBE_GENERIC_RAM_PKTCFG)
// bitfield: PKTCFG_CRCORDER
#define PBE_GENERIC_RAM_PKTCFG_CRCORDER                          10UL
#define PBE_GENERIC_RAM_PKTCFG_CRCORDER_BM                       0x0400UL
// bitfield: PKTCFG_BITORDER
#define PBE_GENERIC_RAM_PKTCFG_BITORDER                          9UL
#define PBE_GENERIC_RAM_PKTCFG_BITORDER_BM                       0x0200UL
// bitfield: PKTCFG_HDRORDER
#define PBE_GENERIC_RAM_PKTCFG_HDRORDER                          8UL
#define PBE_GENERIC_RAM_PKTCFG_HDRORDER_BM                       0x0100UL
// bitfield: PKTCFG_CRCINCHDR
#define PBE_GENERIC_RAM_PKTCFG_CRCINCHDR                         7UL
#define PBE_GENERIC_RAM_PKTCFG_CRCINCHDR_BM                      0x0080UL
// bitfield: PKTCFG_CRCINCSW
#define PBE_GENERIC_RAM_PKTCFG_CRCINCSW                          6UL
#define PBE_GENERIC_RAM_PKTCFG_CRCINCSW_BM                       0x0040UL
// bitfield: PKTCFG_NUMHDRBITS
#define PBE_GENERIC_RAM_PKTCFG_NUMHDRBITS                        0UL
#define PBE_GENERIC_RAM_PKTCFG_NUMHDRBITS_BM                     0x003FUL
// --------------------------------------------------------------
// NUMCRCBITS
// 
#define PBE_GENERIC_RAM_NUMCRCBITS_ADR (PBE_GENERIC_RAM_BASE + 0x0026UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NUMCRCBITS = (unsigned short*) PBE_GENERIC_RAM_NUMCRCBITS_ADR;
#define S_PBE_GENERIC_RAM_NUMCRCBITS (*SP_PBE_GENERIC_RAM_NUMCRCBITS)
// bitfield: NUMCRCBITS_VAL
#define PBE_GENERIC_RAM_NUMCRCBITS_VAL                           0UL
#define PBE_GENERIC_RAM_NUMCRCBITS_VAL_BM                        0x003FUL
// --------------------------------------------------------------
// FIFOCFG
// 
#define PBE_GENERIC_RAM_FIFOCFG_ADR (PBE_GENERIC_RAM_BASE + 0x0028UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_FIFOCFG = (unsigned short*) PBE_GENERIC_RAM_FIFOCFG_ADR;
#define S_PBE_GENERIC_RAM_FIFOCFG (*SP_PBE_GENERIC_RAM_FIFOCFG)
// bitfield: FIFOCFG_APPENDTIMESTAMP
#define PBE_GENERIC_RAM_FIFOCFG_APPENDTIMESTAMP                  15UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDTIMESTAMP_BM               0x8000UL
// bitfield: FIFOCFG_APPENDRSSI
#define PBE_GENERIC_RAM_FIFOCFG_APPENDRSSI                       14UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDRSSI_BM                    0x4000UL
// bitfield: FIFOCFG_APPENDFREQEST
#define PBE_GENERIC_RAM_FIFOCFG_APPENDFREQEST                    13UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDFREQEST_BM                 0x2000UL
// bitfield: FIFOCFG_APPENDLQI
#define PBE_GENERIC_RAM_FIFOCFG_APPENDLQI                        12UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDLQI_BM                     0x1000UL
// bitfield: FIFOCFG_APPENDSTATUS
#define PBE_GENERIC_RAM_FIFOCFG_APPENDSTATUS                     11UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDSTATUS_BM                  0x0800UL
// bitfield: FIFOCFG_APPENDCRC
#define PBE_GENERIC_RAM_FIFOCFG_APPENDCRC                        10UL
#define PBE_GENERIC_RAM_FIFOCFG_APPENDCRC_BM                     0x0400UL
// bitfield: FIFOCFG_AUTOFLUSHEMPTY
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHEMPTY                   9UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHEMPTY_BM                0x0200UL
// enums for bitfield FIFOCFG_AUTOFLUSHEMPTY (width: 1)UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHEMPTY_KEEP              0x0UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHEMPTY_FLUSH             0x1UL
// bitfield: FIFOCFG_AUTOFLUSHIGN
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHIGN                     8UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHIGN_BM                  0x0100UL
// enums for bitfield FIFOCFG_AUTOFLUSHIGN (width: 1)UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHIGN_KEEP                0x0UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHIGN_FLUSH               0x1UL
// bitfield: FIFOCFG_AUTOFLUSHCRC
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHCRC                     7UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHCRC_BM                  0x0080UL
// enums for bitfield FIFOCFG_AUTOFLUSHCRC (width: 1)UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHCRC_KEEP                0x0UL
#define PBE_GENERIC_RAM_FIFOCFG_AUTOFLUSHCRC_FLUSH               0x1UL
// bitfield: FIFOCFG_LENOPTPAD
#define PBE_GENERIC_RAM_FIFOCFG_LENOPTPAD                        4UL
#define PBE_GENERIC_RAM_FIFOCFG_LENOPTPAD_BM                     0x0070UL
// --------------------------------------------------------------
// EXTRABYTES
// 
#define PBE_GENERIC_RAM_EXTRABYTES_ADR (PBE_GENERIC_RAM_BASE + 0x002AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_EXTRABYTES = (unsigned short*) PBE_GENERIC_RAM_EXTRABYTES_ADR;
#define S_PBE_GENERIC_RAM_EXTRABYTES (*SP_PBE_GENERIC_RAM_EXTRABYTES)
// bitfield: EXTRABYTES_VAL
#define PBE_GENERIC_RAM_EXTRABYTES_VAL                           0UL
#define PBE_GENERIC_RAM_EXTRABYTES_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// WHITEINIT
// 
#define PBE_GENERIC_RAM_WHITEINIT_ADR (PBE_GENERIC_RAM_BASE + 0x002CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_WHITEINIT = (unsigned short*) PBE_GENERIC_RAM_WHITEINIT_ADR;
#define S_PBE_GENERIC_RAM_WHITEINIT (*SP_PBE_GENERIC_RAM_WHITEINIT)
// bitfield: WHITEINIT_VAL
#define PBE_GENERIC_RAM_WHITEINIT_VAL                            0UL
#define PBE_GENERIC_RAM_WHITEINIT_VAL_BM                         0xFFFFUL
// --------------------------------------------------------------
// CRCINITL
// 
#define PBE_GENERIC_RAM_CRCINITL_ADR (PBE_GENERIC_RAM_BASE + 0x0030UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_CRCINITL = (unsigned short*) PBE_GENERIC_RAM_CRCINITL_ADR;
#define S_PBE_GENERIC_RAM_CRCINITL (*SP_PBE_GENERIC_RAM_CRCINITL)
// bitfield: CRCINITL_VALLSB
#define PBE_GENERIC_RAM_CRCINITL_VALLSB                          0UL
#define PBE_GENERIC_RAM_CRCINITL_VALLSB_BM                       0xFFFFUL
// --------------------------------------------------------------
// CRCINITH
// 
#define PBE_GENERIC_RAM_CRCINITH_ADR (PBE_GENERIC_RAM_BASE + 0x0032UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_CRCINITH = (unsigned short*) PBE_GENERIC_RAM_CRCINITH_ADR;
#define S_PBE_GENERIC_RAM_CRCINITH (*SP_PBE_GENERIC_RAM_CRCINITH)
// bitfield: CRCINITH_VALMSB
#define PBE_GENERIC_RAM_CRCINITH_VALMSB                          0UL
#define PBE_GENERIC_RAM_CRCINITH_VALMSB_BM                       0xFFFFUL
// --------------------------------------------------------------
// LENCFG
// 
#define PBE_GENERIC_RAM_LENCFG_ADR (PBE_GENERIC_RAM_BASE + 0x0034UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LENCFG = (unsigned short*) PBE_GENERIC_RAM_LENCFG_ADR;
#define S_PBE_GENERIC_RAM_LENCFG (*SP_PBE_GENERIC_RAM_LENCFG)
// bitfield: LENCFG_RESERVED
#define PBE_GENERIC_RAM_LENCFG_RESERVED                          10UL
#define PBE_GENERIC_RAM_LENCFG_RESERVED_BM                       0xFC00UL
// bitfield: LENCFG_NUMLENBITS
#define PBE_GENERIC_RAM_LENCFG_NUMLENBITS                        5UL
#define PBE_GENERIC_RAM_LENCFG_NUMLENBITS_BM                     0x03E0UL
// enums for bitfield LENCFG_NUMLENBITS (width: 5)UL
#define PBE_GENERIC_RAM_LENCFG_NUMLENBITS_FIXED                  0x00UL
// bitfield: LENCFG_LENPOS
#define PBE_GENERIC_RAM_LENCFG_LENPOS                            0UL
#define PBE_GENERIC_RAM_LENCFG_LENPOS_BM                         0x001FUL
// --------------------------------------------------------------
// LENOFFSET
// 
#define PBE_GENERIC_RAM_LENOFFSET_ADR (PBE_GENERIC_RAM_BASE + 0x0036UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LENOFFSET = (unsigned short*) PBE_GENERIC_RAM_LENOFFSET_ADR;
#define S_PBE_GENERIC_RAM_LENOFFSET (*SP_PBE_GENERIC_RAM_LENOFFSET)
// bitfield: LENOFFSET_VAL
#define PBE_GENERIC_RAM_LENOFFSET_VAL                            0UL
#define PBE_GENERIC_RAM_LENOFFSET_VAL_BM                         0xFFFFUL
// --------------------------------------------------------------
// FIRSTRXTIMEOUT
// 
#define PBE_GENERIC_RAM_FIRSTRXTIMEOUT_ADR (PBE_GENERIC_RAM_BASE + 0x0038UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_FIRSTRXTIMEOUT = (unsigned short*) PBE_GENERIC_RAM_FIRSTRXTIMEOUT_ADR;
#define S_PBE_GENERIC_RAM_FIRSTRXTIMEOUT (*SP_PBE_GENERIC_RAM_FIRSTRXTIMEOUT)
// bitfield: FIRSTRXTIMEOUT_VAL
#define PBE_GENERIC_RAM_FIRSTRXTIMEOUT_VAL                       0UL
#define PBE_GENERIC_RAM_FIRSTRXTIMEOUT_VAL_BM                    0xFFFFUL
// --------------------------------------------------------------
// RXTIMEOUT
// 
#define PBE_GENERIC_RAM_RXTIMEOUT_ADR (PBE_GENERIC_RAM_BASE + 0x003AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_RXTIMEOUT = (unsigned short*) PBE_GENERIC_RAM_RXTIMEOUT_ADR;
#define S_PBE_GENERIC_RAM_RXTIMEOUT (*SP_PBE_GENERIC_RAM_RXTIMEOUT)
// bitfield: RXTIMEOUT_VAL
#define PBE_GENERIC_RAM_RXTIMEOUT_VAL                            0UL
#define PBE_GENERIC_RAM_RXTIMEOUT_VAL_BM                         0xFFFFUL
// --------------------------------------------------------------
// RFINTERVAL
// 
#define PBE_GENERIC_RAM_RFINTERVAL_ADR (PBE_GENERIC_RAM_BASE + 0x003CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_RFINTERVAL = (unsigned short*) PBE_GENERIC_RAM_RFINTERVAL_ADR;
#define S_PBE_GENERIC_RAM_RFINTERVAL (*SP_PBE_GENERIC_RAM_RFINTERVAL)
// bitfield: RFINTERVAL_VAL
#define PBE_GENERIC_RAM_RFINTERVAL_VAL                           0UL
#define PBE_GENERIC_RAM_RFINTERVAL_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PRETXIFS
// 
#define PBE_GENERIC_RAM_PRETXIFS_ADR (PBE_GENERIC_RAM_BASE + 0x003EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PRETXIFS = (unsigned short*) PBE_GENERIC_RAM_PRETXIFS_ADR;
#define S_PBE_GENERIC_RAM_PRETXIFS (*SP_PBE_GENERIC_RAM_PRETXIFS)
// bitfield: PRETXIFS_VAL
#define PBE_GENERIC_RAM_PRETXIFS_VAL                             0UL
#define PBE_GENERIC_RAM_PRETXIFS_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// PRERXIFS
// 
#define PBE_GENERIC_RAM_PRERXIFS_ADR (PBE_GENERIC_RAM_BASE + 0x0040UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PRERXIFS = (unsigned short*) PBE_GENERIC_RAM_PRERXIFS_ADR;
#define S_PBE_GENERIC_RAM_PRERXIFS (*SP_PBE_GENERIC_RAM_PRERXIFS)
// bitfield: PRERXIFS_VAL
#define PBE_GENERIC_RAM_PRERXIFS_VAL                             0UL
#define PBE_GENERIC_RAM_PRERXIFS_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// OPCFG
// 
#define PBE_GENERIC_RAM_OPCFG_ADR (PBE_GENERIC_RAM_BASE + 0x0042UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_OPCFG = (unsigned short*) PBE_GENERIC_RAM_OPCFG_ADR;
#define S_PBE_GENERIC_RAM_OPCFG (*SP_PBE_GENERIC_RAM_OPCFG)
// bitfield: OPCFG_RXFILTEROP
#define PBE_GENERIC_RAM_OPCFG_RXFILTEROP                         14UL
#define PBE_GENERIC_RAM_OPCFG_RXFILTEROP_BM                      0x4000UL
// bitfield: OPCFG_RXINCLUDEHDR
#define PBE_GENERIC_RAM_OPCFG_RXINCLUDEHDR                       13UL
#define PBE_GENERIC_RAM_OPCFG_RXINCLUDEHDR_BM                    0x2000UL
// enums for bitfield OPCFG_RXINCLUDEHDR (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_RXINCLUDEHDR_NO                    0x0UL
#define PBE_GENERIC_RAM_OPCFG_RXINCLUDEHDR_YES                   0x1UL
// bitfield: OPCFG_RXREPEATOK
#define PBE_GENERIC_RAM_OPCFG_RXREPEATOK                         12UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATOK_BM                      0x1000UL
// enums for bitfield OPCFG_RXREPEATOK (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATOK_YES                     0x0UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATOK_NO                      0x1UL
// bitfield: OPCFG_RXREPEATNOK
#define PBE_GENERIC_RAM_OPCFG_RXREPEATNOK                        11UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATNOK_BM                     0x0800UL
// enums for bitfield OPCFG_RXREPEATNOK (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATNOK_NO                     0x0UL
#define PBE_GENERIC_RAM_OPCFG_RXREPEATNOK_YES                    0x1UL
// bitfield: OPCFG_TXINFINITE
#define PBE_GENERIC_RAM_OPCFG_TXINFINITE                         10UL
#define PBE_GENERIC_RAM_OPCFG_TXINFINITE_BM                      0x0400UL
// enums for bitfield OPCFG_TXINFINITE (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_TXINFINITE_NO                      0x0UL
#define PBE_GENERIC_RAM_OPCFG_TXINFINITE_YES                     0x1UL
// bitfield: OPCFG_TXPATTERN
#define PBE_GENERIC_RAM_OPCFG_TXPATTERN                          9UL
#define PBE_GENERIC_RAM_OPCFG_TXPATTERN_BM                       0x0200UL
// enums for bitfield OPCFG_TXPATTERN (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_TXPATTERN_NO                       0x0UL
#define PBE_GENERIC_RAM_OPCFG_TXPATTERN_YES                      0x1UL
// bitfield: OPCFG_TXFCMD
#define PBE_GENERIC_RAM_OPCFG_TXFCMD                             7UL
#define PBE_GENERIC_RAM_OPCFG_TXFCMD_BM                          0x0180UL
// enums for bitfield OPCFG_TXFCMD (width: 2)UL
#define PBE_GENERIC_RAM_OPCFG_TXFCMD_NONE                        0x0UL
#define PBE_GENERIC_RAM_OPCFG_TXFCMD_RETRY                       0x1UL
#define PBE_GENERIC_RAM_OPCFG_TXFCMD_DEALLOC                     0x2UL
// bitfield: OPCFG_START
#define PBE_GENERIC_RAM_OPCFG_START                              6UL
#define PBE_GENERIC_RAM_OPCFG_START_BM                           0x0040UL
// bitfield: OPCFG_FS_NOCAL
#define PBE_GENERIC_RAM_OPCFG_FS_NOCAL                           5UL
#define PBE_GENERIC_RAM_OPCFG_FS_NOCAL_BM                        0x0020UL
// enums for bitfield OPCFG_FS_NOCAL (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_FS_NOCAL_CAL                       0x0UL
#define PBE_GENERIC_RAM_OPCFG_FS_NOCAL_NOCAL                     0x1UL
// bitfield: OPCFG_FS_KEEPON
#define PBE_GENERIC_RAM_OPCFG_FS_KEEPON                          4UL
#define PBE_GENERIC_RAM_OPCFG_FS_KEEPON_BM                       0x0010UL
// enums for bitfield OPCFG_FS_KEEPON (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_FS_KEEPON_NO                       0x0UL
#define PBE_GENERIC_RAM_OPCFG_FS_KEEPON_YES                      0x1UL
// bitfield: OPCFG_NEXTOP
#define PBE_GENERIC_RAM_OPCFG_NEXTOP                             3UL
#define PBE_GENERIC_RAM_OPCFG_NEXTOP_BM                          0x0008UL
// enums for bitfield OPCFG_NEXTOP (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_NEXTOP_SWITCH                      0x0UL
#define PBE_GENERIC_RAM_OPCFG_NEXTOP_SAME                        0x1UL
// bitfield: OPCFG_SINGLE
#define PBE_GENERIC_RAM_OPCFG_SINGLE                             2UL
#define PBE_GENERIC_RAM_OPCFG_SINGLE_BM                          0x0004UL
// enums for bitfield OPCFG_SINGLE (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_SINGLE_DIS                         0x0UL
#define PBE_GENERIC_RAM_OPCFG_SINGLE_EN                          0x1UL
// bitfield: OPCFG_IFSPERIOD
#define PBE_GENERIC_RAM_OPCFG_IFSPERIOD                          1UL
#define PBE_GENERIC_RAM_OPCFG_IFSPERIOD_BM                       0x0002UL
// enums for bitfield OPCFG_IFSPERIOD (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_IFSPERIOD_DIS                      0x0UL
#define PBE_GENERIC_RAM_OPCFG_IFSPERIOD_EN                       0x1UL
// bitfield: OPCFG_RFINTERVAL
#define PBE_GENERIC_RAM_OPCFG_RFINTERVAL                         0UL
#define PBE_GENERIC_RAM_OPCFG_RFINTERVAL_BM                      0x0001UL
// enums for bitfield OPCFG_RFINTERVAL (width: 1)UL
#define PBE_GENERIC_RAM_OPCFG_RFINTERVAL_DIS                     0x0UL
#define PBE_GENERIC_RAM_OPCFG_RFINTERVAL_EN                      0x1UL
// --------------------------------------------------------------
// MAXLEN
// 
#define PBE_GENERIC_RAM_MAXLEN_ADR (PBE_GENERIC_RAM_BASE + 0x0044UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_MAXLEN = (unsigned short*) PBE_GENERIC_RAM_MAXLEN_ADR;
#define S_PBE_GENERIC_RAM_MAXLEN (*SP_PBE_GENERIC_RAM_MAXLEN)
// bitfield: MAXLEN_VAL
#define PBE_GENERIC_RAM_MAXLEN_VAL                               0UL
#define PBE_GENERIC_RAM_MAXLEN_VAL_BM                            0xFFFFUL
// --------------------------------------------------------------
// PATTERN
// 
#define PBE_GENERIC_RAM_PATTERN_ADR (PBE_GENERIC_RAM_BASE + 0x0046UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PATTERN = (unsigned short*) PBE_GENERIC_RAM_PATTERN_ADR;
#define S_PBE_GENERIC_RAM_PATTERN (*SP_PBE_GENERIC_RAM_PATTERN)
// bitfield: PATTERN_VAL
#define PBE_GENERIC_RAM_PATTERN_VAL                              0UL
#define PBE_GENERIC_RAM_PATTERN_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// ADDRCFG
// 
#define PBE_GENERIC_RAM_ADDRCFG_ADR (PBE_GENERIC_RAM_BASE + 0x0048UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADDRCFG = (unsigned short*) PBE_GENERIC_RAM_ADDRCFG_ADR;
#define S_PBE_GENERIC_RAM_ADDRCFG (*SP_PBE_GENERIC_RAM_ADDRCFG)
// bitfield: ADDRCFG_ADDRPOS
#define PBE_GENERIC_RAM_ADDRCFG_ADDRPOS                          6UL
#define PBE_GENERIC_RAM_ADDRCFG_ADDRPOS_BM                       0x07C0UL
// bitfield: ADDRCFG_ADDRSZ
#define PBE_GENERIC_RAM_ADDRCFG_ADDRSZ                           1UL
#define PBE_GENERIC_RAM_ADDRCFG_ADDRSZ_BM                        0x003EUL
// bitfield: ADDRCFG_ADDRTYPE
#define PBE_GENERIC_RAM_ADDRCFG_ADDRTYPE                         0UL
#define PBE_GENERIC_RAM_ADDRCFG_ADDRTYPE_BM                      0x0001UL
// --------------------------------------------------------------
// ADDRSW
// 
#define PBE_GENERIC_RAM_ADDRSW_ADR (PBE_GENERIC_RAM_BASE + 0x004AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADDRSW = (unsigned short*) PBE_GENERIC_RAM_ADDRSW_ADR;
#define S_PBE_GENERIC_RAM_ADDRSW (*SP_PBE_GENERIC_RAM_ADDRSW)
// bitfield: ADDRSW_ADD15SW
#define PBE_GENERIC_RAM_ADDRSW_ADD15SW                           15UL
#define PBE_GENERIC_RAM_ADDRSW_ADD15SW_BM                        0x8000UL
// enums for bitfield ADDRSW_ADD15SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD15SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD15SW_B                         0x1UL
// bitfield: ADDRSW_ADD14SW
#define PBE_GENERIC_RAM_ADDRSW_ADD14SW                           14UL
#define PBE_GENERIC_RAM_ADDRSW_ADD14SW_BM                        0x4000UL
// enums for bitfield ADDRSW_ADD14SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD14SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD14SW_B                         0x1UL
// bitfield: ADDRSW_ADD13SW
#define PBE_GENERIC_RAM_ADDRSW_ADD13SW                           13UL
#define PBE_GENERIC_RAM_ADDRSW_ADD13SW_BM                        0x2000UL
// enums for bitfield ADDRSW_ADD13SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD13SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD13SW_B                         0x1UL
// bitfield: ADDRSW_ADD12SW
#define PBE_GENERIC_RAM_ADDRSW_ADD12SW                           12UL
#define PBE_GENERIC_RAM_ADDRSW_ADD12SW_BM                        0x1000UL
// enums for bitfield ADDRSW_ADD12SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD12SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD12SW_B                         0x1UL
// bitfield: ADDRSW_ADD11SW
#define PBE_GENERIC_RAM_ADDRSW_ADD11SW                           11UL
#define PBE_GENERIC_RAM_ADDRSW_ADD11SW_BM                        0x0800UL
// enums for bitfield ADDRSW_ADD11SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD11SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD11SW_B                         0x1UL
// bitfield: ADDRSW_ADD10SW
#define PBE_GENERIC_RAM_ADDRSW_ADD10SW                           10UL
#define PBE_GENERIC_RAM_ADDRSW_ADD10SW_BM                        0x0400UL
// enums for bitfield ADDRSW_ADD10SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD10SW_A                         0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD10SW_B                         0x1UL
// bitfield: ADDRSW_ADD9SW
#define PBE_GENERIC_RAM_ADDRSW_ADD9SW                            9UL
#define PBE_GENERIC_RAM_ADDRSW_ADD9SW_BM                         0x0200UL
// enums for bitfield ADDRSW_ADD9SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD9SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD9SW_B                          0x1UL
// bitfield: ADDRSW_ADD8SW
#define PBE_GENERIC_RAM_ADDRSW_ADD8SW                            8UL
#define PBE_GENERIC_RAM_ADDRSW_ADD8SW_BM                         0x0100UL
// enums for bitfield ADDRSW_ADD8SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD8SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD8SW_B                          0x1UL
// bitfield: ADDRSW_ADD7SW
#define PBE_GENERIC_RAM_ADDRSW_ADD7SW                            7UL
#define PBE_GENERIC_RAM_ADDRSW_ADD7SW_BM                         0x0080UL
// enums for bitfield ADDRSW_ADD7SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD7SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD7SW_B                          0x1UL
// bitfield: ADDRSW_ADD6SW
#define PBE_GENERIC_RAM_ADDRSW_ADD6SW                            6UL
#define PBE_GENERIC_RAM_ADDRSW_ADD6SW_BM                         0x0040UL
// enums for bitfield ADDRSW_ADD6SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD6SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD6SW_B                          0x1UL
// bitfield: ADDRSW_ADD5SW
#define PBE_GENERIC_RAM_ADDRSW_ADD5SW                            5UL
#define PBE_GENERIC_RAM_ADDRSW_ADD5SW_BM                         0x0020UL
// enums for bitfield ADDRSW_ADD5SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD5SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD5SW_B                          0x1UL
// bitfield: ADDRSW_ADD4SW
#define PBE_GENERIC_RAM_ADDRSW_ADD4SW                            4UL
#define PBE_GENERIC_RAM_ADDRSW_ADD4SW_BM                         0x0010UL
// enums for bitfield ADDRSW_ADD4SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD4SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD4SW_B                          0x1UL
// bitfield: ADDRSW_ADD3SW
#define PBE_GENERIC_RAM_ADDRSW_ADD3SW                            3UL
#define PBE_GENERIC_RAM_ADDRSW_ADD3SW_BM                         0x0008UL
// enums for bitfield ADDRSW_ADD3SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD3SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD3SW_B                          0x1UL
// bitfield: ADDRSW_ADD2SW
#define PBE_GENERIC_RAM_ADDRSW_ADD2SW                            2UL
#define PBE_GENERIC_RAM_ADDRSW_ADD2SW_BM                         0x0004UL
// enums for bitfield ADDRSW_ADD2SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD2SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD2SW_B                          0x1UL
// bitfield: ADDRSW_ADD1SW
#define PBE_GENERIC_RAM_ADDRSW_ADD1SW                            1UL
#define PBE_GENERIC_RAM_ADDRSW_ADD1SW_BM                         0x0002UL
// enums for bitfield ADDRSW_ADD1SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD1SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD1SW_B                          0x1UL
// bitfield: ADDRSW_ADD0SW
#define PBE_GENERIC_RAM_ADDRSW_ADD0SW                            0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD0SW_BM                         0x0001UL
// enums for bitfield ADDRSW_ADD0SW (width: 1)UL
#define PBE_GENERIC_RAM_ADDRSW_ADD0SW_A                          0x0UL
#define PBE_GENERIC_RAM_ADDRSW_ADD0SW_B                          0x1UL
// --------------------------------------------------------------
// TESTCFG
// 
#define PBE_GENERIC_RAM_TESTCFG_ADR (PBE_GENERIC_RAM_BASE + 0x004CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TESTCFG = (unsigned short*) PBE_GENERIC_RAM_TESTCFG_ADR;
#define S_PBE_GENERIC_RAM_TESTCFG (*SP_PBE_GENERIC_RAM_TESTCFG)
// bitfield: TESTCFG_ENDCOND
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND                          8UL
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND_BM                       0x0300UL
// enums for bitfield TESTCFG_ENDCOND (width: 2)UL
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND_NEVER                    0x0UL
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND_MDMRFE                   0x1UL
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND_TIMEOUT                  0x2UL
#define PBE_GENERIC_RAM_TESTCFG_ENDCOND_TIMEOUT_DONE             0x3UL
// bitfield: TESTCFG_RESERVED1
#define PBE_GENERIC_RAM_TESTCFG_RESERVED1                        1UL
#define PBE_GENERIC_RAM_TESTCFG_RESERVED1_BM                     0x00FEUL
// bitfield: TESTCFG_START
#define PBE_GENERIC_RAM_TESTCFG_START                            0UL
#define PBE_GENERIC_RAM_TESTCFG_START_BM                         0x0001UL
// enums for bitfield TESTCFG_START (width: 1)UL
#define PBE_GENERIC_RAM_TESTCFG_START_SYNC                       0x0UL
#define PBE_GENERIC_RAM_TESTCFG_START_ASYNC                      0x1UL
// --------------------------------------------------------------
// TESTAPI
// 
#define PBE_GENERIC_RAM_TESTAPI_ADR (PBE_GENERIC_RAM_BASE + 0x004EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TESTAPI = (unsigned short*) PBE_GENERIC_RAM_TESTAPI_ADR;
#define S_PBE_GENERIC_RAM_TESTAPI (*SP_PBE_GENERIC_RAM_TESTAPI)
// bitfield: TESTAPI_MDMAPI
#define PBE_GENERIC_RAM_TESTAPI_MDMAPI                           8UL
#define PBE_GENERIC_RAM_TESTAPI_MDMAPI_BM                        0xFF00UL
// bitfield: TESTAPI_RFEAPI
#define PBE_GENERIC_RAM_TESTAPI_RFEAPI                           0UL
#define PBE_GENERIC_RAM_TESTAPI_RFEAPI_BM                        0x00FFUL
// --------------------------------------------------------------
// TESTTIMEOUT
// 
#define PBE_GENERIC_RAM_TESTTIMEOUT_ADR (PBE_GENERIC_RAM_BASE + 0x0050UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TESTTIMEOUT = (unsigned short*) PBE_GENERIC_RAM_TESTTIMEOUT_ADR;
#define S_PBE_GENERIC_RAM_TESTTIMEOUT (*SP_PBE_GENERIC_RAM_TESTTIMEOUT)
// bitfield: TESTTIMEOUT_VAL
#define PBE_GENERIC_RAM_TESTTIMEOUT_VAL                          0UL
#define PBE_GENERIC_RAM_TESTTIMEOUT_VAL_BM                       0xFFFFUL
// --------------------------------------------------------------
// ADD0
// 
#define PBE_GENERIC_RAM_ADD0_ADR (PBE_GENERIC_RAM_BASE + 0x0054UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD0 = (unsigned short*) PBE_GENERIC_RAM_ADD0_ADR;
#define S_PBE_GENERIC_RAM_ADD0 (*SP_PBE_GENERIC_RAM_ADD0)
// bitfield: ADD0_VAL
#define PBE_GENERIC_RAM_ADD0_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD0_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD1
// 
#define PBE_GENERIC_RAM_ADD1_ADR (PBE_GENERIC_RAM_BASE + 0x0056UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD1 = (unsigned short*) PBE_GENERIC_RAM_ADD1_ADR;
#define S_PBE_GENERIC_RAM_ADD1 (*SP_PBE_GENERIC_RAM_ADD1)
// bitfield: ADD1_VAL
#define PBE_GENERIC_RAM_ADD1_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD1_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD2
// 
#define PBE_GENERIC_RAM_ADD2_ADR (PBE_GENERIC_RAM_BASE + 0x0058UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD2 = (unsigned short*) PBE_GENERIC_RAM_ADD2_ADR;
#define S_PBE_GENERIC_RAM_ADD2 (*SP_PBE_GENERIC_RAM_ADD2)
// bitfield: ADD2_VAL
#define PBE_GENERIC_RAM_ADD2_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD2_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD3
// 
#define PBE_GENERIC_RAM_ADD3_ADR (PBE_GENERIC_RAM_BASE + 0x005AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD3 = (unsigned short*) PBE_GENERIC_RAM_ADD3_ADR;
#define S_PBE_GENERIC_RAM_ADD3 (*SP_PBE_GENERIC_RAM_ADD3)
// bitfield: ADD3_VAL
#define PBE_GENERIC_RAM_ADD3_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD3_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD4
// 
#define PBE_GENERIC_RAM_ADD4_ADR (PBE_GENERIC_RAM_BASE + 0x005CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD4 = (unsigned short*) PBE_GENERIC_RAM_ADD4_ADR;
#define S_PBE_GENERIC_RAM_ADD4 (*SP_PBE_GENERIC_RAM_ADD4)
// bitfield: ADD4_VAL
#define PBE_GENERIC_RAM_ADD4_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD4_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD5
// 
#define PBE_GENERIC_RAM_ADD5_ADR (PBE_GENERIC_RAM_BASE + 0x005EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD5 = (unsigned short*) PBE_GENERIC_RAM_ADD5_ADR;
#define S_PBE_GENERIC_RAM_ADD5 (*SP_PBE_GENERIC_RAM_ADD5)
// bitfield: ADD5_VAL
#define PBE_GENERIC_RAM_ADD5_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD5_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD6
// 
#define PBE_GENERIC_RAM_ADD6_ADR (PBE_GENERIC_RAM_BASE + 0x0060UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD6 = (unsigned short*) PBE_GENERIC_RAM_ADD6_ADR;
#define S_PBE_GENERIC_RAM_ADD6 (*SP_PBE_GENERIC_RAM_ADD6)
// bitfield: ADD6_VAL
#define PBE_GENERIC_RAM_ADD6_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD6_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD7
// 
#define PBE_GENERIC_RAM_ADD7_ADR (PBE_GENERIC_RAM_BASE + 0x0062UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD7 = (unsigned short*) PBE_GENERIC_RAM_ADD7_ADR;
#define S_PBE_GENERIC_RAM_ADD7 (*SP_PBE_GENERIC_RAM_ADD7)
// bitfield: ADD7_VAL
#define PBE_GENERIC_RAM_ADD7_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD7_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD8
// 
#define PBE_GENERIC_RAM_ADD8_ADR (PBE_GENERIC_RAM_BASE + 0x0064UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD8 = (unsigned short*) PBE_GENERIC_RAM_ADD8_ADR;
#define S_PBE_GENERIC_RAM_ADD8 (*SP_PBE_GENERIC_RAM_ADD8)
// bitfield: ADD8_VAL
#define PBE_GENERIC_RAM_ADD8_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD8_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD9
// 
#define PBE_GENERIC_RAM_ADD9_ADR (PBE_GENERIC_RAM_BASE + 0x0066UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD9 = (unsigned short*) PBE_GENERIC_RAM_ADD9_ADR;
#define S_PBE_GENERIC_RAM_ADD9 (*SP_PBE_GENERIC_RAM_ADD9)
// bitfield: ADD9_VAL
#define PBE_GENERIC_RAM_ADD9_VAL                                 0UL
#define PBE_GENERIC_RAM_ADD9_VAL_BM                              0xFFFFUL
// --------------------------------------------------------------
// ADD10
// 
#define PBE_GENERIC_RAM_ADD10_ADR (PBE_GENERIC_RAM_BASE + 0x0068UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD10 = (unsigned short*) PBE_GENERIC_RAM_ADD10_ADR;
#define S_PBE_GENERIC_RAM_ADD10 (*SP_PBE_GENERIC_RAM_ADD10)
// bitfield: ADD10_VAL
#define PBE_GENERIC_RAM_ADD10_VAL                                0UL
#define PBE_GENERIC_RAM_ADD10_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// ADD11
// 
#define PBE_GENERIC_RAM_ADD11_ADR (PBE_GENERIC_RAM_BASE + 0x006AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD11 = (unsigned short*) PBE_GENERIC_RAM_ADD11_ADR;
#define S_PBE_GENERIC_RAM_ADD11 (*SP_PBE_GENERIC_RAM_ADD11)
// bitfield: ADD11_VAL
#define PBE_GENERIC_RAM_ADD11_VAL                                0UL
#define PBE_GENERIC_RAM_ADD11_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// ADD12
// 
#define PBE_GENERIC_RAM_ADD12_ADR (PBE_GENERIC_RAM_BASE + 0x006CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD12 = (unsigned short*) PBE_GENERIC_RAM_ADD12_ADR;
#define S_PBE_GENERIC_RAM_ADD12 (*SP_PBE_GENERIC_RAM_ADD12)
// bitfield: ADD12_VAL
#define PBE_GENERIC_RAM_ADD12_VAL                                0UL
#define PBE_GENERIC_RAM_ADD12_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// ADD13
// 
#define PBE_GENERIC_RAM_ADD13_ADR (PBE_GENERIC_RAM_BASE + 0x006EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD13 = (unsigned short*) PBE_GENERIC_RAM_ADD13_ADR;
#define S_PBE_GENERIC_RAM_ADD13 (*SP_PBE_GENERIC_RAM_ADD13)
// bitfield: ADD13_VAL
#define PBE_GENERIC_RAM_ADD13_VAL                                0UL
#define PBE_GENERIC_RAM_ADD13_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// ADD15
// 
#define PBE_GENERIC_RAM_ADD15_ADR (PBE_GENERIC_RAM_BASE + 0x0070UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_ADD15 = (unsigned short*) PBE_GENERIC_RAM_ADD15_ADR;
#define S_PBE_GENERIC_RAM_ADD15 (*SP_PBE_GENERIC_RAM_ADD15)
// bitfield: ADD15_VAL
#define PBE_GENERIC_RAM_ADD15_VAL                                0UL
#define PBE_GENERIC_RAM_ADD15_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// NRXNOK
// 
#define PBE_GENERIC_RAM_NRXNOK_ADR (PBE_GENERIC_RAM_BASE + 0x0072UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXNOK = (unsigned short*) PBE_GENERIC_RAM_NRXNOK_ADR;
#define S_PBE_GENERIC_RAM_NRXNOK (*SP_PBE_GENERIC_RAM_NRXNOK)
// bitfield: NRXNOK_VAL
#define PBE_GENERIC_RAM_NRXNOK_VAL                               0UL
#define PBE_GENERIC_RAM_NRXNOK_VAL_BM                            0xFFFFUL
// --------------------------------------------------------------
// NRXIGNORED
// 
#define PBE_GENERIC_RAM_NRXIGNORED_ADR (PBE_GENERIC_RAM_BASE + 0x0074UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXIGNORED = (unsigned short*) PBE_GENERIC_RAM_NRXIGNORED_ADR;
#define S_PBE_GENERIC_RAM_NRXIGNORED (*SP_PBE_GENERIC_RAM_NRXIGNORED)
// bitfield: NRXIGNORED_VAL
#define PBE_GENERIC_RAM_NRXIGNORED_VAL                           0UL
#define PBE_GENERIC_RAM_NRXIGNORED_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// NRXEMPTY
// 
#define PBE_GENERIC_RAM_NRXEMPTY_ADR (PBE_GENERIC_RAM_BASE + 0x0076UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXEMPTY = (unsigned short*) PBE_GENERIC_RAM_NRXEMPTY_ADR;
#define S_PBE_GENERIC_RAM_NRXEMPTY (*SP_PBE_GENERIC_RAM_NRXEMPTY)
// bitfield: NRXEMPTY_VAL
#define PBE_GENERIC_RAM_NRXEMPTY_VAL                             0UL
#define PBE_GENERIC_RAM_NRXEMPTY_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// NRXFIFOFULL
// 
#define PBE_GENERIC_RAM_NRXFIFOFULL_ADR (PBE_GENERIC_RAM_BASE + 0x0078UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXFIFOFULL = (unsigned short*) PBE_GENERIC_RAM_NRXFIFOFULL_ADR;
#define S_PBE_GENERIC_RAM_NRXFIFOFULL (*SP_PBE_GENERIC_RAM_NRXFIFOFULL)
// bitfield: NRXFIFOFULL_VAL
#define PBE_GENERIC_RAM_NRXFIFOFULL_VAL                          0UL
#define PBE_GENERIC_RAM_NRXFIFOFULL_VAL_BM                       0xFFFFUL
// --------------------------------------------------------------
// NRXOK
// 
#define PBE_GENERIC_RAM_NRXOK_ADR (PBE_GENERIC_RAM_BASE + 0x007AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXOK = (unsigned short*) PBE_GENERIC_RAM_NRXOK_ADR;
#define S_PBE_GENERIC_RAM_NRXOK (*SP_PBE_GENERIC_RAM_NRXOK)
// bitfield: NRXOK_VAL
#define PBE_GENERIC_RAM_NRXOK_VAL                                0UL
#define PBE_GENERIC_RAM_NRXOK_VAL_BM                             0xFFFFUL
// --------------------------------------------------------------
// NTX
// 
#define PBE_GENERIC_RAM_NTX_ADR (PBE_GENERIC_RAM_BASE + 0x007CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NTX = (unsigned short*) PBE_GENERIC_RAM_NTX_ADR;
#define S_PBE_GENERIC_RAM_NTX (*SP_PBE_GENERIC_RAM_NTX)
// bitfield: NTX_VAL
#define PBE_GENERIC_RAM_NTX_VAL                                  0UL
#define PBE_GENERIC_RAM_NTX_VAL_BM                               0xFFFFUL
// --------------------------------------------------------------
// NRXTIMEOUT
// 
#define PBE_GENERIC_RAM_NRXTIMEOUT_ADR (PBE_GENERIC_RAM_BASE + 0x007EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NRXTIMEOUT = (unsigned short*) PBE_GENERIC_RAM_NRXTIMEOUT_ADR;
#define S_PBE_GENERIC_RAM_NRXTIMEOUT (*SP_PBE_GENERIC_RAM_NRXTIMEOUT)
// bitfield: NRXTIMEOUT_VAL
#define PBE_GENERIC_RAM_NRXTIMEOUT_VAL                           0UL
#define PBE_GENERIC_RAM_NRXTIMEOUT_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// LASTRSSI
// 
#define PBE_GENERIC_RAM_LASTRSSI_ADR (PBE_GENERIC_RAM_BASE + 0x0080UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LASTRSSI = (unsigned short*) PBE_GENERIC_RAM_LASTRSSI_ADR;
#define S_PBE_GENERIC_RAM_LASTRSSI (*SP_PBE_GENERIC_RAM_LASTRSSI)
// bitfield: LASTRSSI_VAL
#define PBE_GENERIC_RAM_LASTRSSI_VAL                             0UL
#define PBE_GENERIC_RAM_LASTRSSI_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// LASTFREQOFF
// 
#define PBE_GENERIC_RAM_LASTFREQOFF_ADR (PBE_GENERIC_RAM_BASE + 0x0082UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LASTFREQOFF = (unsigned short*) PBE_GENERIC_RAM_LASTFREQOFF_ADR;
#define S_PBE_GENERIC_RAM_LASTFREQOFF (*SP_PBE_GENERIC_RAM_LASTFREQOFF)
// bitfield: LASTFREQOFF_VAL
#define PBE_GENERIC_RAM_LASTFREQOFF_VAL                          0UL
#define PBE_GENERIC_RAM_LASTFREQOFF_VAL_BM                       0xFFFFUL
// --------------------------------------------------------------
// LASTLQI
// 
#define PBE_GENERIC_RAM_LASTLQI_ADR (PBE_GENERIC_RAM_BASE + 0x0084UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LASTLQI = (unsigned short*) PBE_GENERIC_RAM_LASTLQI_ADR;
#define S_PBE_GENERIC_RAM_LASTLQI (*SP_PBE_GENERIC_RAM_LASTLQI)
// bitfield: LASTLQI_VAL
#define PBE_GENERIC_RAM_LASTLQI_VAL                              0UL
#define PBE_GENERIC_RAM_LASTLQI_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// LASTTIMESTAMPL
// 
#define PBE_GENERIC_RAM_LASTTIMESTAMPL_ADR (PBE_GENERIC_RAM_BASE + 0x0088UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LASTTIMESTAMPL = (unsigned short*) PBE_GENERIC_RAM_LASTTIMESTAMPL_ADR;
#define S_PBE_GENERIC_RAM_LASTTIMESTAMPL (*SP_PBE_GENERIC_RAM_LASTTIMESTAMPL)
// bitfield: LASTTIMESTAMPL_VAL
#define PBE_GENERIC_RAM_LASTTIMESTAMPL_VAL                       0UL
#define PBE_GENERIC_RAM_LASTTIMESTAMPL_VAL_BM                    0xFFFFUL
// --------------------------------------------------------------
// LASTTIMESTAMPH
// 
#define PBE_GENERIC_RAM_LASTTIMESTAMPH_ADR (PBE_GENERIC_RAM_BASE + 0x008AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_LASTTIMESTAMPH = (unsigned short*) PBE_GENERIC_RAM_LASTTIMESTAMPH_ADR;
#define S_PBE_GENERIC_RAM_LASTTIMESTAMPH (*SP_PBE_GENERIC_RAM_LASTTIMESTAMPH)
// bitfield: LASTTIMESTAMPH_VAL
#define PBE_GENERIC_RAM_LASTTIMESTAMPH_VAL                       0UL
#define PBE_GENERIC_RAM_LASTTIMESTAMPH_VAL_BM                    0xFFFFUL
// --------------------------------------------------------------
// PEERADRINFO
// 
#define PBE_GENERIC_RAM_PEERADRINFO_ADR (PBE_GENERIC_RAM_BASE + 0x008CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADRINFO = (unsigned short*) PBE_GENERIC_RAM_PEERADRINFO_ADR;
#define S_PBE_GENERIC_RAM_PEERADRINFO (*SP_PBE_GENERIC_RAM_PEERADRINFO)
// bitfield: PEERADRINFO_VAL
#define PBE_GENERIC_RAM_PEERADRINFO_VAL                          0UL
#define PBE_GENERIC_RAM_PEERADRINFO_VAL_BM                       0xFFFFUL
// --------------------------------------------------------------
// PEERADR1AL
// 
#define PBE_GENERIC_RAM_PEERADR1AL_ADR (PBE_GENERIC_RAM_BASE + 0x008EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR1AL = (unsigned short*) PBE_GENERIC_RAM_PEERADR1AL_ADR;
#define S_PBE_GENERIC_RAM_PEERADR1AL (*SP_PBE_GENERIC_RAM_PEERADR1AL)
// bitfield: PEERADR1AL_VAL
#define PBE_GENERIC_RAM_PEERADR1AL_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR1AL_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR1AH
// 
#define PBE_GENERIC_RAM_PEERADR1AH_ADR (PBE_GENERIC_RAM_BASE + 0x0090UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR1AH = (unsigned short*) PBE_GENERIC_RAM_PEERADR1AH_ADR;
#define S_PBE_GENERIC_RAM_PEERADR1AH (*SP_PBE_GENERIC_RAM_PEERADR1AH)
// bitfield: PEERADR1AH_VAL
#define PBE_GENERIC_RAM_PEERADR1AH_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR1AH_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR0AL
// 
#define PBE_GENERIC_RAM_PEERADR0AL_ADR (PBE_GENERIC_RAM_BASE + 0x0092UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR0AL = (unsigned short*) PBE_GENERIC_RAM_PEERADR0AL_ADR;
#define S_PBE_GENERIC_RAM_PEERADR0AL (*SP_PBE_GENERIC_RAM_PEERADR0AL)
// bitfield: PEERADR0AL_VAL
#define PBE_GENERIC_RAM_PEERADR0AL_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR0AL_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR0AH
// 
#define PBE_GENERIC_RAM_PEERADR0AH_ADR (PBE_GENERIC_RAM_BASE + 0x0094UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR0AH = (unsigned short*) PBE_GENERIC_RAM_PEERADR0AH_ADR;
#define S_PBE_GENERIC_RAM_PEERADR0AH (*SP_PBE_GENERIC_RAM_PEERADR0AH)
// bitfield: PEERADR0AH_VAL
#define PBE_GENERIC_RAM_PEERADR0AH_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR0AH_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR1BL
// 
#define PBE_GENERIC_RAM_PEERADR1BL_ADR (PBE_GENERIC_RAM_BASE + 0x0096UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR1BL = (unsigned short*) PBE_GENERIC_RAM_PEERADR1BL_ADR;
#define S_PBE_GENERIC_RAM_PEERADR1BL (*SP_PBE_GENERIC_RAM_PEERADR1BL)
// bitfield: PEERADR1BL_VAL
#define PBE_GENERIC_RAM_PEERADR1BL_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR1BL_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR1BH
// 
#define PBE_GENERIC_RAM_PEERADR1BH_ADR (PBE_GENERIC_RAM_BASE + 0x0098UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR1BH = (unsigned short*) PBE_GENERIC_RAM_PEERADR1BH_ADR;
#define S_PBE_GENERIC_RAM_PEERADR1BH (*SP_PBE_GENERIC_RAM_PEERADR1BH)
// bitfield: PEERADR1BH_VAL
#define PBE_GENERIC_RAM_PEERADR1BH_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR1BH_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR0BL
// 
#define PBE_GENERIC_RAM_PEERADR0BL_ADR (PBE_GENERIC_RAM_BASE + 0x009AUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR0BL = (unsigned short*) PBE_GENERIC_RAM_PEERADR0BL_ADR;
#define S_PBE_GENERIC_RAM_PEERADR0BL (*SP_PBE_GENERIC_RAM_PEERADR0BL)
// bitfield: PEERADR0BL_VAL
#define PBE_GENERIC_RAM_PEERADR0BL_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR0BL_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// PEERADR0BH
// 
#define PBE_GENERIC_RAM_PEERADR0BH_ADR (PBE_GENERIC_RAM_BASE + 0x009CUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_PEERADR0BH = (unsigned short*) PBE_GENERIC_RAM_PEERADR0BH_ADR;
#define S_PBE_GENERIC_RAM_PEERADR0BH (*SP_PBE_GENERIC_RAM_PEERADR0BH)
// bitfield: PEERADR0BH_VAL
#define PBE_GENERIC_RAM_PEERADR0BH_VAL                           0UL
#define PBE_GENERIC_RAM_PEERADR0BH_VAL_BM                        0xFFFFUL
// --------------------------------------------------------------
// NESB
// 
#define PBE_GENERIC_RAM_NESB_ADR (PBE_GENERIC_RAM_BASE + 0x009EUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_NESB = (unsigned short*) PBE_GENERIC_RAM_NESB_ADR;
#define S_PBE_GENERIC_RAM_NESB (*SP_PBE_GENERIC_RAM_NESB)
// bitfield: NESB_RESERVED
#define PBE_GENERIC_RAM_NESB_RESERVED                            6UL
#define PBE_GENERIC_RAM_NESB_RESERVED_BM                         0xFFC0UL
// bitfield: NESB_PEERADRLEN
#define PBE_GENERIC_RAM_NESB_PEERADRLEN                          3UL
#define PBE_GENERIC_RAM_NESB_PEERADRLEN_BM                       0x0038UL
// bitfield: NESB_NESBMODE
#define PBE_GENERIC_RAM_NESB_NESBMODE                            2UL
#define PBE_GENERIC_RAM_NESB_NESBMODE_BM                         0x0004UL
// enums for bitfield NESB_NESBMODE (width: 1)UL
#define PBE_GENERIC_RAM_NESB_NESBMODE_OFF                        0x0UL
#define PBE_GENERIC_RAM_NESB_NESBMODE_ON                         0x1UL
// --------------------------------------------------------------
// CRCVAL0
// 
#define PBE_GENERIC_RAM_CRCVAL0_ADR (PBE_GENERIC_RAM_BASE + 0x00A0UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_CRCVAL0 = (unsigned short*) PBE_GENERIC_RAM_CRCVAL0_ADR;
#define S_PBE_GENERIC_RAM_CRCVAL0 (*SP_PBE_GENERIC_RAM_CRCVAL0)
// bitfield: CRCVAL0_VAL
#define PBE_GENERIC_RAM_CRCVAL0_VAL                              0UL
#define PBE_GENERIC_RAM_CRCVAL0_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// SEQSTAT0
// 
#define PBE_GENERIC_RAM_SEQSTAT0_ADR (PBE_GENERIC_RAM_BASE + 0x00A2UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_SEQSTAT0 = (unsigned short*) PBE_GENERIC_RAM_SEQSTAT0_ADR;
#define S_PBE_GENERIC_RAM_SEQSTAT0 (*SP_PBE_GENERIC_RAM_SEQSTAT0)
// bitfield: SEQSTAT0_RESERVED
#define PBE_GENERIC_RAM_SEQSTAT0_RESERVED                        5UL
#define PBE_GENERIC_RAM_SEQSTAT0_RESERVED_BM                     0xFFE0UL
// bitfield: SEQSTAT0_STOPAUTO
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO                        3UL
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO_BM                     0x0018UL
// enums for bitfield SEQSTAT0_STOPAUTO (width: 2)UL
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO_ALWAYS                 0x0UL
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO_POSNOA                 0x1UL
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO_NEGNOA                 0x2UL
#define PBE_GENERIC_RAM_SEQSTAT0_STOPAUTO_NEVER                  0x3UL
// bitfield: SEQSTAT0_PID
#define PBE_GENERIC_RAM_SEQSTAT0_PID                             1UL
#define PBE_GENERIC_RAM_SEQSTAT0_PID_BM                          0x0006UL
// bitfield: SEQSTAT0_VALID
#define PBE_GENERIC_RAM_SEQSTAT0_VALID                           0UL
#define PBE_GENERIC_RAM_SEQSTAT0_VALID_BM                        0x0001UL
// enums for bitfield SEQSTAT0_VALID (width: 1)UL
#define PBE_GENERIC_RAM_SEQSTAT0_VALID_NO                        0x0UL
#define PBE_GENERIC_RAM_SEQSTAT0_VALID_YES                       0x1UL
// --------------------------------------------------------------
// CRCVAL1
// 
#define PBE_GENERIC_RAM_CRCVAL1_ADR (PBE_GENERIC_RAM_BASE + 0x00A4UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_CRCVAL1 = (unsigned short*) PBE_GENERIC_RAM_CRCVAL1_ADR;
#define S_PBE_GENERIC_RAM_CRCVAL1 (*SP_PBE_GENERIC_RAM_CRCVAL1)
// bitfield: CRCVAL1_VAL
#define PBE_GENERIC_RAM_CRCVAL1_VAL                              0UL
#define PBE_GENERIC_RAM_CRCVAL1_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// SEQSTAT1
// 
#define PBE_GENERIC_RAM_SEQSTAT1_ADR (PBE_GENERIC_RAM_BASE + 0x00A6UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_SEQSTAT1 = (unsigned short*) PBE_GENERIC_RAM_SEQSTAT1_ADR;
#define S_PBE_GENERIC_RAM_SEQSTAT1 (*SP_PBE_GENERIC_RAM_SEQSTAT1)
// bitfield: SEQSTAT1_RESERVED
#define PBE_GENERIC_RAM_SEQSTAT1_RESERVED                        5UL
#define PBE_GENERIC_RAM_SEQSTAT1_RESERVED_BM                     0xFFE0UL
// bitfield: SEQSTAT1_STOPAUTO
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO                        3UL
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO_BM                     0x0018UL
// enums for bitfield SEQSTAT1_STOPAUTO (width: 2)UL
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO_ALWAYS                 0x0UL
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO_POSNOA                 0x1UL
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO_NEGNOA                 0x2UL
#define PBE_GENERIC_RAM_SEQSTAT1_STOPAUTO_NEVER                  0x3UL
// bitfield: SEQSTAT1_PID
#define PBE_GENERIC_RAM_SEQSTAT1_PID                             1UL
#define PBE_GENERIC_RAM_SEQSTAT1_PID_BM                          0x0006UL
// bitfield: SEQSTAT1_VALID
#define PBE_GENERIC_RAM_SEQSTAT1_VALID                           0UL
#define PBE_GENERIC_RAM_SEQSTAT1_VALID_BM                        0x0001UL
// enums for bitfield SEQSTAT1_VALID (width: 1)UL
#define PBE_GENERIC_RAM_SEQSTAT1_VALID_NO                        0x0UL
#define PBE_GENERIC_RAM_SEQSTAT1_VALID_YES                       0x1UL
// --------------------------------------------------------------
// STATUSBYTE
// 
#define PBE_GENERIC_RAM_STATUSBYTE_ADR (PBE_GENERIC_RAM_BASE + 0x00A8UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_STATUSBYTE = (unsigned short*) PBE_GENERIC_RAM_STATUSBYTE_ADR;
#define S_PBE_GENERIC_RAM_STATUSBYTE (*SP_PBE_GENERIC_RAM_STATUSBYTE)
// bitfield: STATUSBYTE_RESERVED
#define PBE_GENERIC_RAM_STATUSBYTE_RESERVED                      5UL
#define PBE_GENERIC_RAM_STATUSBYTE_RESERVED_BM                   0xFFE0UL
// bitfield: STATUSBYTE_SWSEL
#define PBE_GENERIC_RAM_STATUSBYTE_SWSEL                         4UL
#define PBE_GENERIC_RAM_STATUSBYTE_SWSEL_BM                      0x0010UL
// bitfield: STATUSBYTE_IGNORED
#define PBE_GENERIC_RAM_STATUSBYTE_IGNORED                       3UL
#define PBE_GENERIC_RAM_STATUSBYTE_IGNORED_BM                    0x0008UL
// bitfield: STATUSBYTE_CRCERROR
#define PBE_GENERIC_RAM_STATUSBYTE_CRCERROR                      2UL
#define PBE_GENERIC_RAM_STATUSBYTE_CRCERROR_BM                   0x0004UL
// bitfield: STATUSBYTE_PHY
#define PBE_GENERIC_RAM_STATUSBYTE_PHY                           0UL
#define PBE_GENERIC_RAM_STATUSBYTE_PHY_BM                        0x0003UL
// enums for bitfield STATUSBYTE_PHY (width: 2)UL
#define PBE_GENERIC_RAM_STATUSBYTE_PHY_1M                        0x0UL
#define PBE_GENERIC_RAM_STATUSBYTE_PHY_2M                        0x1UL
#define PBE_GENERIC_RAM_STATUSBYTE_PHY_CODED_125K                0x2UL
#define PBE_GENERIC_RAM_STATUSBYTE_PHY_CODED_500K                0x3UL
// --------------------------------------------------------------
// TMPBYTE1
// 
#define PBE_GENERIC_RAM_TMPBYTE1_ADR (PBE_GENERIC_RAM_BASE + 0x00AAUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPBYTE1 = (unsigned short*) PBE_GENERIC_RAM_TMPBYTE1_ADR;
#define S_PBE_GENERIC_RAM_TMPBYTE1 (*SP_PBE_GENERIC_RAM_TMPBYTE1)
// bitfield: TMPBYTE1_VAL
#define PBE_GENERIC_RAM_TMPBYTE1_VAL                             0UL
#define PBE_GENERIC_RAM_TMPBYTE1_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// TMPBYTE2
// 
#define PBE_GENERIC_RAM_TMPBYTE2_ADR (PBE_GENERIC_RAM_BASE + 0x00ACUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPBYTE2 = (unsigned short*) PBE_GENERIC_RAM_TMPBYTE2_ADR;
#define S_PBE_GENERIC_RAM_TMPBYTE2 (*SP_PBE_GENERIC_RAM_TMPBYTE2)
// bitfield: TMPBYTE2_VAL
#define PBE_GENERIC_RAM_TMPBYTE2_VAL                             0UL
#define PBE_GENERIC_RAM_TMPBYTE2_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// TMPBYTE3
// 
#define PBE_GENERIC_RAM_TMPBYTE3_ADR (PBE_GENERIC_RAM_BASE + 0x00AEUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPBYTE3 = (unsigned short*) PBE_GENERIC_RAM_TMPBYTE3_ADR;
#define S_PBE_GENERIC_RAM_TMPBYTE3 (*SP_PBE_GENERIC_RAM_TMPBYTE3)
// bitfield: TMPBYTE3_VAL
#define PBE_GENERIC_RAM_TMPBYTE3_VAL                             0UL
#define PBE_GENERIC_RAM_TMPBYTE3_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// TMPBYTE4
// 
#define PBE_GENERIC_RAM_TMPBYTE4_ADR (PBE_GENERIC_RAM_BASE + 0x00B0UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPBYTE4 = (unsigned short*) PBE_GENERIC_RAM_TMPBYTE4_ADR;
#define S_PBE_GENERIC_RAM_TMPBYTE4 (*SP_PBE_GENERIC_RAM_TMPBYTE4)
// bitfield: TMPBYTE4_VAL
#define PBE_GENERIC_RAM_TMPBYTE4_VAL                             0UL
#define PBE_GENERIC_RAM_TMPBYTE4_VAL_BM                          0xFFFFUL
// --------------------------------------------------------------
// TMPRSSI
// 
#define PBE_GENERIC_RAM_TMPRSSI_ADR (PBE_GENERIC_RAM_BASE + 0x00B2UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPRSSI = (unsigned short*) PBE_GENERIC_RAM_TMPRSSI_ADR;
#define S_PBE_GENERIC_RAM_TMPRSSI (*SP_PBE_GENERIC_RAM_TMPRSSI)
// bitfield: TMPRSSI_VAL
#define PBE_GENERIC_RAM_TMPRSSI_VAL                              0UL
#define PBE_GENERIC_RAM_TMPRSSI_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// TMPADR1
// 
#define PBE_GENERIC_RAM_TMPADR1_ADR (PBE_GENERIC_RAM_BASE + 0x00B4UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPADR1 = (unsigned short*) PBE_GENERIC_RAM_TMPADR1_ADR;
#define S_PBE_GENERIC_RAM_TMPADR1 (*SP_PBE_GENERIC_RAM_TMPADR1)
// bitfield: TMPADR1_VAL
#define PBE_GENERIC_RAM_TMPADR1_VAL                              0UL
#define PBE_GENERIC_RAM_TMPADR1_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// TMPADR2
// 
#define PBE_GENERIC_RAM_TMPADR2_ADR (PBE_GENERIC_RAM_BASE + 0x00B6UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPADR2 = (unsigned short*) PBE_GENERIC_RAM_TMPADR2_ADR;
#define S_PBE_GENERIC_RAM_TMPADR2 (*SP_PBE_GENERIC_RAM_TMPADR2)
// bitfield: TMPADR2_VAL
#define PBE_GENERIC_RAM_TMPADR2_VAL                              0UL
#define PBE_GENERIC_RAM_TMPADR2_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// TMPADR3
// 
#define PBE_GENERIC_RAM_TMPADR3_ADR (PBE_GENERIC_RAM_BASE + 0x00B8UL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPADR3 = (unsigned short*) PBE_GENERIC_RAM_TMPADR3_ADR;
#define S_PBE_GENERIC_RAM_TMPADR3 (*SP_PBE_GENERIC_RAM_TMPADR3)
// bitfield: TMPADR3_VAL
#define PBE_GENERIC_RAM_TMPADR3_VAL                              0UL
#define PBE_GENERIC_RAM_TMPADR3_VAL_BM                           0xFFFFUL
// --------------------------------------------------------------
// TMPADR4
// 
#define PBE_GENERIC_RAM_TMPADR4_ADR (PBE_GENERIC_RAM_BASE + 0x00BAUL)
static volatile unsigned short* const SP_PBE_GENERIC_RAM_TMPADR4 = (unsigned short*) PBE_GENERIC_RAM_TMPADR4_ADR;
#define S_PBE_GENERIC_RAM_TMPADR4 (*SP_PBE_GENERIC_RAM_TMPADR4)
// bitfield: TMPADR4_VAL
#define PBE_GENERIC_RAM_TMPADR4_VAL                              0UL
#define PBE_GENERIC_RAM_TMPADR4_VAL_BM                           0xFFFFUL

#endif
