// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:21
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40092000 -dat_sz 16 -sub 128 -ramreg -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/ble_cs/doc/regdef.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40092000 -dat_sz 16 -sub 128 -ramreg -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/ble_cs/doc/regdef.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/pbe/ble_cs/doc/regdef.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: bb089823e77080616445680a0df3112402488226
//
// ===========================================================================


#ifndef __PBE_BLE_CS_REGDEF_REGS_H
#define __PBE_BLE_CS_REGDEF_REGS_H

#define PBE_BLE_CS_REGDEF_BASE 0x40092000UL
// --------------------------------------------------------------
// API
// 
#define PBE_BLE_CS_REGDEF_API_ADR (PBE_BLE_CS_REGDEF_BASE + 0xFFFFFFFFFFFFFF18UL)
static volatile unsigned short* const SP_PBE_BLE_CS_REGDEF_API = (unsigned short*) PBE_BLE_CS_REGDEF_API_ADR;
#define S_PBE_BLE_CS_REGDEF_API (*SP_PBE_BLE_CS_REGDEF_API)
// bitfield: API_OP
#define PBE_BLE_CS_REGDEF_API_OP                                   0UL
#define PBE_BLE_CS_REGDEF_API_OP_BM                                0x001FUL
// enums for bitfield API_OP (width: 5)UL
#define PBE_BLE_CS_REGDEF_API_OP_PING                              0x00UL
#define PBE_BLE_CS_REGDEF_API_OP_STOP                              0x01UL
#define PBE_BLE_CS_REGDEF_API_OP_BLE_CS                            0x02UL

#endif
