// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:22
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x44000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/RFMODELSregs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x44000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/RFMODELSregs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/RFMODELSregs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: af3de6b7d9a09a4d879ab8769705f4d02f9ba358
//
// ===========================================================================


#ifndef __RFMODELS_REGS_H
#define __RFMODELS_REGS_H

#define RFMODELS_BASE 0x44000000UL
// --------------------------------------------------------------
// CHANNELCTRL
// 
#define RFMODELS_CHANNELCTRL_ADR (RFMODELS_BASE + 0x0000UL)
static volatile unsigned long* const SP_RFMODELS_CHANNELCTRL = (unsigned long*) RFMODELS_CHANNELCTRL_ADR;
#define S_RFMODELS_CHANNELCTRL (*SP_RFMODELS_CHANNELCTRL)
// bitfield: CHANNELCTRL_ENABLE
#define RFMODELS_CHANNELCTRL_ENABLE                       0UL
#define RFMODELS_CHANNELCTRL_ENABLE_BM                    0x00000001UL
// --------------------------------------------------------------
// TXSTRENGTH
// 
#define RFMODELS_TXSTRENGTH_ADR (RFMODELS_BASE + 0x0004UL)
static volatile unsigned long* const SP_RFMODELS_TXSTRENGTH = (unsigned long*) RFMODELS_TXSTRENGTH_ADR;
#define S_RFMODELS_TXSTRENGTH (*SP_RFMODELS_TXSTRENGTH)
// bitfield: TXSTRENGTH_VALUE
#define RFMODELS_TXSTRENGTH_VALUE                         0UL
#define RFMODELS_TXSTRENGTH_VALUE_BM                      0x000FFFFFUL
// --------------------------------------------------------------
// INTERFSTRENGTH
// 
#define RFMODELS_INTERFSTRENGTH_ADR (RFMODELS_BASE + 0x0008UL)
static volatile unsigned long* const SP_RFMODELS_INTERFSTRENGTH = (unsigned long*) RFMODELS_INTERFSTRENGTH_ADR;
#define S_RFMODELS_INTERFSTRENGTH (*SP_RFMODELS_INTERFSTRENGTH)
// bitfield: INTERFSTRENGTH_VALUE
#define RFMODELS_INTERFSTRENGTH_VALUE                     0UL
#define RFMODELS_INTERFSTRENGTH_VALUE_BM                  0x000FFFFFUL
// --------------------------------------------------------------
// AWGNSTRENGTH
// 
#define RFMODELS_AWGNSTRENGTH_ADR (RFMODELS_BASE + 0x000CUL)
static volatile unsigned long* const SP_RFMODELS_AWGNSTRENGTH = (unsigned long*) RFMODELS_AWGNSTRENGTH_ADR;
#define S_RFMODELS_AWGNSTRENGTH (*SP_RFMODELS_AWGNSTRENGTH)
// bitfield: AWGNSTRENGTH_VALUE
#define RFMODELS_AWGNSTRENGTH_VALUE                       0UL
#define RFMODELS_AWGNSTRENGTH_VALUE_BM                    0x000000FFUL
// --------------------------------------------------------------
// TXIFFREQ
// 
#define RFMODELS_TXIFFREQ_ADR (RFMODELS_BASE + 0x0010UL)
static volatile unsigned long* const SP_RFMODELS_TXIFFREQ = (unsigned long*) RFMODELS_TXIFFREQ_ADR;
#define S_RFMODELS_TXIFFREQ (*SP_RFMODELS_TXIFFREQ)
// bitfield: TXIFFREQ_VALUE
#define RFMODELS_TXIFFREQ_VALUE                           0UL
#define RFMODELS_TXIFFREQ_VALUE_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// INTERFIFFREQ
// 
#define RFMODELS_INTERFIFFREQ_ADR (RFMODELS_BASE + 0x0014UL)
static volatile unsigned long* const SP_RFMODELS_INTERFIFFREQ = (unsigned long*) RFMODELS_INTERFIFFREQ_ADR;
#define S_RFMODELS_INTERFIFFREQ (*SP_RFMODELS_INTERFIFFREQ)
// bitfield: INTERFIFFREQ_VALUE
#define RFMODELS_INTERFIFFREQ_VALUE                       0UL
#define RFMODELS_INTERFIFFREQ_VALUE_BM                    0x0000FFFFUL
// --------------------------------------------------------------
// AWGNSEED0
// 
#define RFMODELS_AWGNSEED0_ADR (RFMODELS_BASE + 0x0018UL)
static volatile unsigned long* const SP_RFMODELS_AWGNSEED0 = (unsigned long*) RFMODELS_AWGNSEED0_ADR;
#define S_RFMODELS_AWGNSEED0 (*SP_RFMODELS_AWGNSEED0)
// bitfield: AWGNSEED0_VALUE
#define RFMODELS_AWGNSEED0_VALUE                          0UL
#define RFMODELS_AWGNSEED0_VALUE_BM                       0xFFFFFFFFUL
// --------------------------------------------------------------
// AWGNSEED1
// 
#define RFMODELS_AWGNSEED1_ADR (RFMODELS_BASE + 0x001CUL)
static volatile unsigned long* const SP_RFMODELS_AWGNSEED1 = (unsigned long*) RFMODELS_AWGNSEED1_ADR;
#define S_RFMODELS_AWGNSEED1 (*SP_RFMODELS_AWGNSEED1)
// bitfield: AWGNSEED1_VALUE
#define RFMODELS_AWGNSEED1_VALUE                          0UL
#define RFMODELS_AWGNSEED1_VALUE_BM                       0xFFFFFFFFUL
// --------------------------------------------------------------
// RXGAINIMB
// 
#define RFMODELS_RXGAINIMB_ADR (RFMODELS_BASE + 0x0020UL)
static volatile unsigned long* const SP_RFMODELS_RXGAINIMB = (unsigned long*) RFMODELS_RXGAINIMB_ADR;
#define S_RFMODELS_RXGAINIMB (*SP_RFMODELS_RXGAINIMB)
// bitfield: RXGAINIMB_VALUE
#define RFMODELS_RXGAINIMB_VALUE                          0UL
#define RFMODELS_RXGAINIMB_VALUE_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// RXQUADSINSKEW
// 
#define RFMODELS_RXQUADSINSKEW_ADR (RFMODELS_BASE + 0x0024UL)
static volatile unsigned long* const SP_RFMODELS_RXQUADSINSKEW = (unsigned long*) RFMODELS_RXQUADSINSKEW_ADR;
#define S_RFMODELS_RXQUADSINSKEW (*SP_RFMODELS_RXQUADSINSKEW)
// bitfield: RXQUADSINSKEW_VALUE
#define RFMODELS_RXQUADSINSKEW_VALUE                      0UL
#define RFMODELS_RXQUADSINSKEW_VALUE_BM                   0x0000FFFFUL
// --------------------------------------------------------------
// RXQUADCOSSKEW
// 
#define RFMODELS_RXQUADCOSSKEW_ADR (RFMODELS_BASE + 0x0028UL)
static volatile unsigned long* const SP_RFMODELS_RXQUADCOSSKEW = (unsigned long*) RFMODELS_RXQUADCOSSKEW_ADR;
#define S_RFMODELS_RXQUADCOSSKEW (*SP_RFMODELS_RXQUADCOSSKEW)
// bitfield: RXQUADCOSSKEW_VALUE
#define RFMODELS_RXQUADCOSSKEW_VALUE                      0UL
#define RFMODELS_RXQUADCOSSKEW_VALUE_BM                   0x0000FFFFUL
// --------------------------------------------------------------
// RXLOLEAKI
// 
#define RFMODELS_RXLOLEAKI_ADR (RFMODELS_BASE + 0x002CUL)
static volatile unsigned long* const SP_RFMODELS_RXLOLEAKI = (unsigned long*) RFMODELS_RXLOLEAKI_ADR;
#define S_RFMODELS_RXLOLEAKI (*SP_RFMODELS_RXLOLEAKI)
// bitfield: RXLOLEAKI_VALUE
#define RFMODELS_RXLOLEAKI_VALUE                          0UL
#define RFMODELS_RXLOLEAKI_VALUE_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// RXLOLEAKQ
// 
#define RFMODELS_RXLOLEAKQ_ADR (RFMODELS_BASE + 0x0030UL)
static volatile unsigned long* const SP_RFMODELS_RXLOLEAKQ = (unsigned long*) RFMODELS_RXLOLEAKQ_ADR;
#define S_RFMODELS_RXLOLEAKQ (*SP_RFMODELS_RXLOLEAKQ)
// bitfield: RXLOLEAKQ_VALUE
#define RFMODELS_RXLOLEAKQ_VALUE                          0UL
#define RFMODELS_RXLOLEAKQ_VALUE_BM                       0x0000FFFFUL
// --------------------------------------------------------------
// RANDDELAY
// 
#define RFMODELS_RANDDELAY_ADR (RFMODELS_BASE + 0x0034UL)
static volatile unsigned long* const SP_RFMODELS_RANDDELAY = (unsigned long*) RFMODELS_RANDDELAY_ADR;
#define S_RFMODELS_RANDDELAY (*SP_RFMODELS_RANDDELAY)
// bitfield: RANDDELAY_DELAY
#define RFMODELS_RANDDELAY_DELAY                          0UL
#define RFMODELS_RANDDELAY_DELAY_BM                       0x000000FFUL
// --------------------------------------------------------------
// VCODIVIDER
// 
#define RFMODELS_VCODIVIDER_ADR (RFMODELS_BASE + 0x0038UL)
static volatile unsigned long* const SP_RFMODELS_VCODIVIDER = (unsigned long*) RFMODELS_VCODIVIDER_ADR;
#define S_RFMODELS_VCODIVIDER (*SP_RFMODELS_VCODIVIDER)
// bitfield: VCODIVIDER_VAL
#define RFMODELS_VCODIVIDER_VAL                           0UL
#define RFMODELS_VCODIVIDER_VAL_BM                        0x0000FFFFUL
// --------------------------------------------------------------
// ANTDIV
// 
#define RFMODELS_ANTDIV_ADR (RFMODELS_BASE + 0x003CUL)
static volatile unsigned long* const SP_RFMODELS_ANTDIV = (unsigned long*) RFMODELS_ANTDIV_ADR;
#define S_RFMODELS_ANTDIV (*SP_RFMODELS_ANTDIV)
// bitfield: ANTDIV_ENABLE
#define RFMODELS_ANTDIV_ENABLE                            7UL
#define RFMODELS_ANTDIV_ENABLE_BM                         0x00000080UL
// bitfield: ANTDIV_ANTSEL
#define RFMODELS_ANTDIV_ANTSEL                            6UL
#define RFMODELS_ANTDIV_ANTSEL_BM                         0x00000040UL
// bitfield: ANTDIV_SMI_CL
#define RFMODELS_ANTDIV_SMI_CL                            5UL
#define RFMODELS_ANTDIV_SMI_CL_BM                         0x00000020UL
// bitfield: ANTDIV_SMI_DL
#define RFMODELS_ANTDIV_SMI_DL                            4UL
#define RFMODELS_ANTDIV_SMI_DL_BM                         0x00000010UL
// bitfield: ANTDIV_RFC_GPO3
#define RFMODELS_ANTDIV_RFC_GPO3                          3UL
#define RFMODELS_ANTDIV_RFC_GPO3_BM                       0x00000008UL
// bitfield: ANTDIV_RFC_GPO2
#define RFMODELS_ANTDIV_RFC_GPO2                          2UL
#define RFMODELS_ANTDIV_RFC_GPO2_BM                       0x00000004UL
// bitfield: ANTDIV_RFC_GPO1
#define RFMODELS_ANTDIV_RFC_GPO1                          1UL
#define RFMODELS_ANTDIV_RFC_GPO1_BM                       0x00000002UL
// bitfield: ANTDIV_RFC_GPO0
#define RFMODELS_ANTDIV_RFC_GPO0                          0UL
#define RFMODELS_ANTDIV_RFC_GPO0_BM                       0x00000001UL
// --------------------------------------------------------------
// PAMODE
// 
#define RFMODELS_PAMODE_ADR (RFMODELS_BASE + 0x0040UL)
static volatile unsigned long* const SP_RFMODELS_PAMODE = (unsigned long*) RFMODELS_PAMODE_ADR;
#define S_RFMODELS_PAMODE (*SP_RFMODELS_PAMODE)
// bitfield: PAMODE_MODE
#define RFMODELS_PAMODE_MODE                              15UL
#define RFMODELS_PAMODE_MODE_BM                           0x00008000UL
// bitfield: PAMODE_ON_TIME
#define RFMODELS_PAMODE_ON_TIME                           0UL
#define RFMODELS_PAMODE_ON_TIME_BM                        0x00007FFFUL
// --------------------------------------------------------------
// INTFMODE
// 
#define RFMODELS_INTFMODE_ADR (RFMODELS_BASE + 0x0044UL)
static volatile unsigned long* const SP_RFMODELS_INTFMODE = (unsigned long*) RFMODELS_INTFMODE_ADR;
#define S_RFMODELS_INTFMODE (*SP_RFMODELS_INTFMODE)
// bitfield: INTFMODE_MODE
#define RFMODELS_INTFMODE_MODE                            15UL
#define RFMODELS_INTFMODE_MODE_BM                         0x00008000UL
// bitfield: INTFMODE_BAUD
#define RFMODELS_INTFMODE_BAUD                            0UL
#define RFMODELS_INTFMODE_BAUD_BM                         0x00007FFFUL
// --------------------------------------------------------------
// INTFMODISFCFG0
// 
#define RFMODELS_INTFMODISFCFG0_ADR (RFMODELS_BASE + 0x0048UL)
static volatile unsigned long* const SP_RFMODELS_INTFMODISFCFG0 = (unsigned long*) RFMODELS_INTFMODISFCFG0_ADR;
#define S_RFMODELS_INTFMODISFCFG0 (*SP_RFMODELS_INTFMODISFCFG0)
// bitfield: INTFMODISFCFG0_CFG_15_0
#define RFMODELS_INTFMODISFCFG0_CFG_15_0                  0UL
#define RFMODELS_INTFMODISFCFG0_CFG_15_0_BM               0x0000FFFFUL
// --------------------------------------------------------------
// INTFMODISFCFG1
// 
#define RFMODELS_INTFMODISFCFG1_ADR (RFMODELS_BASE + 0x004CUL)
static volatile unsigned long* const SP_RFMODELS_INTFMODISFCFG1 = (unsigned long*) RFMODELS_INTFMODISFCFG1_ADR;
#define S_RFMODELS_INTFMODISFCFG1 (*SP_RFMODELS_INTFMODISFCFG1)
// bitfield: INTFMODISFCFG1_CFG_31_16
#define RFMODELS_INTFMODISFCFG1_CFG_31_16                 0UL
#define RFMODELS_INTFMODISFCFG1_CFG_31_16_BM              0x0000FFFFUL

#endif
