// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:23
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x43000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/sdbell_regs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x43000000 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/sdbell_regs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/source/octopusble/doc/sdbell_regs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: eeacca0bfc38e09355f1135af033213dd344dcd1
//
// ===========================================================================


#ifndef __SDBELL_REGS_H
#define __SDBELL_REGS_H

#define SDBELL_BASE 0x43000000UL
// --------------------------------------------------------------
// ISMASTER
// 
#define SDBELL_ISMASTER_ADR (SDBELL_BASE + 0x0000UL)
static volatile unsigned long* const SP_SDBELL_ISMASTER = (unsigned long*) SDBELL_ISMASTER_ADR;
#define S_SDBELL_ISMASTER (*SP_SDBELL_ISMASTER)
// bitfield: ISMASTER_MASTER
#define SDBELL_ISMASTER_MASTER                          0UL
#define SDBELL_ISMASTER_MASTER_BM                       0x00000001UL
// enums for bitfield ISMASTER_MASTER (width: 1)UL
#define SDBELL_ISMASTER_MASTER_SLV                      0x0UL
#define SDBELL_ISMASTER_MASTER_MST                      0x1UL
// --------------------------------------------------------------
// MSTCMD
// 
#define SDBELL_MSTCMD_ADR (SDBELL_BASE + 0x0004UL)
static volatile unsigned long* const SP_SDBELL_MSTCMD = (unsigned long*) SDBELL_MSTCMD_ADR;
#define S_SDBELL_MSTCMD (*SP_SDBELL_MSTCMD)
// bitfield: MSTCMD_MBOXLEN
#define SDBELL_MSTCMD_MBOXLEN                           24UL
#define SDBELL_MSTCMD_MBOXLEN_BM                        0xFF000000UL
// bitfield: MSTCMD_CMD
#define SDBELL_MSTCMD_CMD                               0UL
#define SDBELL_MSTCMD_CMD_BM                            0x00FFFFFFUL
// --------------------------------------------------------------
// MSTCMDACK
// 
#define SDBELL_MSTCMDACK_ADR (SDBELL_BASE + 0x0008UL)
static volatile unsigned long* const SP_SDBELL_MSTCMDACK = (unsigned long*) SDBELL_MSTCMDACK_ADR;
#define S_SDBELL_MSTCMDACK (*SP_SDBELL_MSTCMDACK)
// bitfield: MSTCMDACK_MBOXLEN
#define SDBELL_MSTCMDACK_MBOXLEN                        24UL
#define SDBELL_MSTCMDACK_MBOXLEN_BM                     0xFF000000UL
// bitfield: MSTCMDACK_CMDACK
#define SDBELL_MSTCMDACK_CMDACK                         9UL
#define SDBELL_MSTCMDACK_CMDACK_BM                      0x00FFFE00UL
// --------------------------------------------------------------
// SLVCMD
// 
#define SDBELL_SLVCMD_ADR (SDBELL_BASE + 0x000CUL)
static volatile unsigned long* const SP_SDBELL_SLVCMD = (unsigned long*) SDBELL_SLVCMD_ADR;
#define S_SDBELL_SLVCMD (*SP_SDBELL_SLVCMD)
// bitfield: SLVCMD_MBOXLEN
#define SDBELL_SLVCMD_MBOXLEN                           24UL
#define SDBELL_SLVCMD_MBOXLEN_BM                        0xFF000000UL
// bitfield: SLVCMD_CMD
#define SDBELL_SLVCMD_CMD                               0UL
#define SDBELL_SLVCMD_CMD_BM                            0x00FFFFFFUL
// --------------------------------------------------------------
// SLVCMDACK
// 
#define SDBELL_SLVCMDACK_ADR (SDBELL_BASE + 0x0010UL)
static volatile unsigned long* const SP_SDBELL_SLVCMDACK = (unsigned long*) SDBELL_SLVCMDACK_ADR;
#define S_SDBELL_SLVCMDACK (*SP_SDBELL_SLVCMDACK)
// bitfield: SLVCMDACK_MBOXLEN
#define SDBELL_SLVCMDACK_MBOXLEN                        24UL
#define SDBELL_SLVCMDACK_MBOXLEN_BM                     0xFF000000UL
// bitfield: SLVCMDACK_CMDACK
#define SDBELL_SLVCMDACK_CMDACK                         0UL
#define SDBELL_SLVCMDACK_CMDACK_BM                      0x00FFFFFFUL
// --------------------------------------------------------------
// SLATEMODE
// 
#define SDBELL_SLATEMODE_ADR (SDBELL_BASE + 0x0014UL)
static volatile unsigned long* const SP_SDBELL_SLATEMODE = (unsigned long*) SDBELL_SLATEMODE_ADR;
#define S_SDBELL_SLATEMODE (*SP_SDBELL_SLATEMODE)
// bitfield: SLATEMODE_SLATE
#define SDBELL_SLATEMODE_SLATE                          0UL
#define SDBELL_SLATEMODE_SLATE_BM                       0x00000001UL
// enums for bitfield SLATEMODE_SLATE (width: 1)UL
#define SDBELL_SLATEMODE_SLATE_DIS                      0x0UL
#define SDBELL_SLATEMODE_SLATE_ENA                      0x1UL
// --------------------------------------------------------------
// MBOX0
// 
#define SDBELL_MBOX0_ADR (SDBELL_BASE + 0x0020UL)
static volatile unsigned long* const SP_SDBELL_MBOX0 = (unsigned long*) SDBELL_MBOX0_ADR;
#define S_SDBELL_MBOX0 (*SP_SDBELL_MBOX0)
// bitfield: MBOX0_DATA
#define SDBELL_MBOX0_DATA                               0UL
#define SDBELL_MBOX0_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX1
// 
#define SDBELL_MBOX1_ADR (SDBELL_BASE + 0x0024UL)
static volatile unsigned long* const SP_SDBELL_MBOX1 = (unsigned long*) SDBELL_MBOX1_ADR;
#define S_SDBELL_MBOX1 (*SP_SDBELL_MBOX1)
// bitfield: MBOX1_DATA
#define SDBELL_MBOX1_DATA                               0UL
#define SDBELL_MBOX1_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX2
// 
#define SDBELL_MBOX2_ADR (SDBELL_BASE + 0x0028UL)
static volatile unsigned long* const SP_SDBELL_MBOX2 = (unsigned long*) SDBELL_MBOX2_ADR;
#define S_SDBELL_MBOX2 (*SP_SDBELL_MBOX2)
// bitfield: MBOX2_DATA
#define SDBELL_MBOX2_DATA                               0UL
#define SDBELL_MBOX2_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX3
// 
#define SDBELL_MBOX3_ADR (SDBELL_BASE + 0x002CUL)
static volatile unsigned long* const SP_SDBELL_MBOX3 = (unsigned long*) SDBELL_MBOX3_ADR;
#define S_SDBELL_MBOX3 (*SP_SDBELL_MBOX3)
// bitfield: MBOX3_DATA
#define SDBELL_MBOX3_DATA                               0UL
#define SDBELL_MBOX3_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX4
// 
#define SDBELL_MBOX4_ADR (SDBELL_BASE + 0x0030UL)
static volatile unsigned long* const SP_SDBELL_MBOX4 = (unsigned long*) SDBELL_MBOX4_ADR;
#define S_SDBELL_MBOX4 (*SP_SDBELL_MBOX4)
// bitfield: MBOX4_DATA
#define SDBELL_MBOX4_DATA                               0UL
#define SDBELL_MBOX4_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX5
// 
#define SDBELL_MBOX5_ADR (SDBELL_BASE + 0x0034UL)
static volatile unsigned long* const SP_SDBELL_MBOX5 = (unsigned long*) SDBELL_MBOX5_ADR;
#define S_SDBELL_MBOX5 (*SP_SDBELL_MBOX5)
// bitfield: MBOX5_DATA
#define SDBELL_MBOX5_DATA                               0UL
#define SDBELL_MBOX5_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX6
// 
#define SDBELL_MBOX6_ADR (SDBELL_BASE + 0x0038UL)
static volatile unsigned long* const SP_SDBELL_MBOX6 = (unsigned long*) SDBELL_MBOX6_ADR;
#define S_SDBELL_MBOX6 (*SP_SDBELL_MBOX6)
// bitfield: MBOX6_DATA
#define SDBELL_MBOX6_DATA                               0UL
#define SDBELL_MBOX6_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX7
// 
#define SDBELL_MBOX7_ADR (SDBELL_BASE + 0x003CUL)
static volatile unsigned long* const SP_SDBELL_MBOX7 = (unsigned long*) SDBELL_MBOX7_ADR;
#define S_SDBELL_MBOX7 (*SP_SDBELL_MBOX7)
// bitfield: MBOX7_DATA
#define SDBELL_MBOX7_DATA                               0UL
#define SDBELL_MBOX7_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX8
// 
#define SDBELL_MBOX8_ADR (SDBELL_BASE + 0x0040UL)
static volatile unsigned long* const SP_SDBELL_MBOX8 = (unsigned long*) SDBELL_MBOX8_ADR;
#define S_SDBELL_MBOX8 (*SP_SDBELL_MBOX8)
// bitfield: MBOX8_DATA
#define SDBELL_MBOX8_DATA                               0UL
#define SDBELL_MBOX8_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX9
// 
#define SDBELL_MBOX9_ADR (SDBELL_BASE + 0x0044UL)
static volatile unsigned long* const SP_SDBELL_MBOX9 = (unsigned long*) SDBELL_MBOX9_ADR;
#define S_SDBELL_MBOX9 (*SP_SDBELL_MBOX9)
// bitfield: MBOX9_DATA
#define SDBELL_MBOX9_DATA                               0UL
#define SDBELL_MBOX9_DATA_BM                            0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX10
// 
#define SDBELL_MBOX10_ADR (SDBELL_BASE + 0x0048UL)
static volatile unsigned long* const SP_SDBELL_MBOX10 = (unsigned long*) SDBELL_MBOX10_ADR;
#define S_SDBELL_MBOX10 (*SP_SDBELL_MBOX10)
// bitfield: MBOX10_DATA
#define SDBELL_MBOX10_DATA                              0UL
#define SDBELL_MBOX10_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX11
// 
#define SDBELL_MBOX11_ADR (SDBELL_BASE + 0x004CUL)
static volatile unsigned long* const SP_SDBELL_MBOX11 = (unsigned long*) SDBELL_MBOX11_ADR;
#define S_SDBELL_MBOX11 (*SP_SDBELL_MBOX11)
// bitfield: MBOX11_DATA
#define SDBELL_MBOX11_DATA                              0UL
#define SDBELL_MBOX11_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX12
// 
#define SDBELL_MBOX12_ADR (SDBELL_BASE + 0x0050UL)
static volatile unsigned long* const SP_SDBELL_MBOX12 = (unsigned long*) SDBELL_MBOX12_ADR;
#define S_SDBELL_MBOX12 (*SP_SDBELL_MBOX12)
// bitfield: MBOX12_DATA
#define SDBELL_MBOX12_DATA                              0UL
#define SDBELL_MBOX12_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX13
// 
#define SDBELL_MBOX13_ADR (SDBELL_BASE + 0x0054UL)
static volatile unsigned long* const SP_SDBELL_MBOX13 = (unsigned long*) SDBELL_MBOX13_ADR;
#define S_SDBELL_MBOX13 (*SP_SDBELL_MBOX13)
// bitfield: MBOX13_DATA
#define SDBELL_MBOX13_DATA                              0UL
#define SDBELL_MBOX13_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX14
// 
#define SDBELL_MBOX14_ADR (SDBELL_BASE + 0x0058UL)
static volatile unsigned long* const SP_SDBELL_MBOX14 = (unsigned long*) SDBELL_MBOX14_ADR;
#define S_SDBELL_MBOX14 (*SP_SDBELL_MBOX14)
// bitfield: MBOX14_DATA
#define SDBELL_MBOX14_DATA                              0UL
#define SDBELL_MBOX14_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX15
// 
#define SDBELL_MBOX15_ADR (SDBELL_BASE + 0x005CUL)
static volatile unsigned long* const SP_SDBELL_MBOX15 = (unsigned long*) SDBELL_MBOX15_ADR;
#define S_SDBELL_MBOX15 (*SP_SDBELL_MBOX15)
// bitfield: MBOX15_DATA
#define SDBELL_MBOX15_DATA                              0UL
#define SDBELL_MBOX15_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX16
// 
#define SDBELL_MBOX16_ADR (SDBELL_BASE + 0x0060UL)
static volatile unsigned long* const SP_SDBELL_MBOX16 = (unsigned long*) SDBELL_MBOX16_ADR;
#define S_SDBELL_MBOX16 (*SP_SDBELL_MBOX16)
// bitfield: MBOX16_DATA
#define SDBELL_MBOX16_DATA                              0UL
#define SDBELL_MBOX16_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX17
// 
#define SDBELL_MBOX17_ADR (SDBELL_BASE + 0x0064UL)
static volatile unsigned long* const SP_SDBELL_MBOX17 = (unsigned long*) SDBELL_MBOX17_ADR;
#define S_SDBELL_MBOX17 (*SP_SDBELL_MBOX17)
// bitfield: MBOX17_DATA
#define SDBELL_MBOX17_DATA                              0UL
#define SDBELL_MBOX17_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX18
// 
#define SDBELL_MBOX18_ADR (SDBELL_BASE + 0x0068UL)
static volatile unsigned long* const SP_SDBELL_MBOX18 = (unsigned long*) SDBELL_MBOX18_ADR;
#define S_SDBELL_MBOX18 (*SP_SDBELL_MBOX18)
// bitfield: MBOX18_DATA
#define SDBELL_MBOX18_DATA                              0UL
#define SDBELL_MBOX18_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX19
// 
#define SDBELL_MBOX19_ADR (SDBELL_BASE + 0x006CUL)
static volatile unsigned long* const SP_SDBELL_MBOX19 = (unsigned long*) SDBELL_MBOX19_ADR;
#define S_SDBELL_MBOX19 (*SP_SDBELL_MBOX19)
// bitfield: MBOX19_DATA
#define SDBELL_MBOX19_DATA                              0UL
#define SDBELL_MBOX19_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX20
// 
#define SDBELL_MBOX20_ADR (SDBELL_BASE + 0x0070UL)
static volatile unsigned long* const SP_SDBELL_MBOX20 = (unsigned long*) SDBELL_MBOX20_ADR;
#define S_SDBELL_MBOX20 (*SP_SDBELL_MBOX20)
// bitfield: MBOX20_DATA
#define SDBELL_MBOX20_DATA                              0UL
#define SDBELL_MBOX20_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX21
// 
#define SDBELL_MBOX21_ADR (SDBELL_BASE + 0x0074UL)
static volatile unsigned long* const SP_SDBELL_MBOX21 = (unsigned long*) SDBELL_MBOX21_ADR;
#define S_SDBELL_MBOX21 (*SP_SDBELL_MBOX21)
// bitfield: MBOX21_DATA
#define SDBELL_MBOX21_DATA                              0UL
#define SDBELL_MBOX21_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX22
// 
#define SDBELL_MBOX22_ADR (SDBELL_BASE + 0x0078UL)
static volatile unsigned long* const SP_SDBELL_MBOX22 = (unsigned long*) SDBELL_MBOX22_ADR;
#define S_SDBELL_MBOX22 (*SP_SDBELL_MBOX22)
// bitfield: MBOX22_DATA
#define SDBELL_MBOX22_DATA                              0UL
#define SDBELL_MBOX22_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX23
// 
#define SDBELL_MBOX23_ADR (SDBELL_BASE + 0x007CUL)
static volatile unsigned long* const SP_SDBELL_MBOX23 = (unsigned long*) SDBELL_MBOX23_ADR;
#define S_SDBELL_MBOX23 (*SP_SDBELL_MBOX23)
// bitfield: MBOX23_DATA
#define SDBELL_MBOX23_DATA                              0UL
#define SDBELL_MBOX23_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX24
// 
#define SDBELL_MBOX24_ADR (SDBELL_BASE + 0x0080UL)
static volatile unsigned long* const SP_SDBELL_MBOX24 = (unsigned long*) SDBELL_MBOX24_ADR;
#define S_SDBELL_MBOX24 (*SP_SDBELL_MBOX24)
// bitfield: MBOX24_DATA
#define SDBELL_MBOX24_DATA                              0UL
#define SDBELL_MBOX24_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX25
// 
#define SDBELL_MBOX25_ADR (SDBELL_BASE + 0x0084UL)
static volatile unsigned long* const SP_SDBELL_MBOX25 = (unsigned long*) SDBELL_MBOX25_ADR;
#define S_SDBELL_MBOX25 (*SP_SDBELL_MBOX25)
// bitfield: MBOX25_DATA
#define SDBELL_MBOX25_DATA                              0UL
#define SDBELL_MBOX25_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX26
// 
#define SDBELL_MBOX26_ADR (SDBELL_BASE + 0x0088UL)
static volatile unsigned long* const SP_SDBELL_MBOX26 = (unsigned long*) SDBELL_MBOX26_ADR;
#define S_SDBELL_MBOX26 (*SP_SDBELL_MBOX26)
// bitfield: MBOX26_DATA
#define SDBELL_MBOX26_DATA                              0UL
#define SDBELL_MBOX26_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX27
// 
#define SDBELL_MBOX27_ADR (SDBELL_BASE + 0x008CUL)
static volatile unsigned long* const SP_SDBELL_MBOX27 = (unsigned long*) SDBELL_MBOX27_ADR;
#define S_SDBELL_MBOX27 (*SP_SDBELL_MBOX27)
// bitfield: MBOX27_DATA
#define SDBELL_MBOX27_DATA                              0UL
#define SDBELL_MBOX27_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX28
// 
#define SDBELL_MBOX28_ADR (SDBELL_BASE + 0x0090UL)
static volatile unsigned long* const SP_SDBELL_MBOX28 = (unsigned long*) SDBELL_MBOX28_ADR;
#define S_SDBELL_MBOX28 (*SP_SDBELL_MBOX28)
// bitfield: MBOX28_DATA
#define SDBELL_MBOX28_DATA                              0UL
#define SDBELL_MBOX28_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX29
// 
#define SDBELL_MBOX29_ADR (SDBELL_BASE + 0x0094UL)
static volatile unsigned long* const SP_SDBELL_MBOX29 = (unsigned long*) SDBELL_MBOX29_ADR;
#define S_SDBELL_MBOX29 (*SP_SDBELL_MBOX29)
// bitfield: MBOX29_DATA
#define SDBELL_MBOX29_DATA                              0UL
#define SDBELL_MBOX29_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX30
// 
#define SDBELL_MBOX30_ADR (SDBELL_BASE + 0x0098UL)
static volatile unsigned long* const SP_SDBELL_MBOX30 = (unsigned long*) SDBELL_MBOX30_ADR;
#define S_SDBELL_MBOX30 (*SP_SDBELL_MBOX30)
// bitfield: MBOX30_DATA
#define SDBELL_MBOX30_DATA                              0UL
#define SDBELL_MBOX30_DATA_BM                           0xFFFFFFFFUL
// --------------------------------------------------------------
// MBOX31
// 
#define SDBELL_MBOX31_ADR (SDBELL_BASE + 0x009CUL)
static volatile unsigned long* const SP_SDBELL_MBOX31 = (unsigned long*) SDBELL_MBOX31_ADR;
#define S_SDBELL_MBOX31 (*SP_SDBELL_MBOX31)
// bitfield: MBOX31_DATA
#define SDBELL_MBOX31_DATA                              0UL
#define SDBELL_MBOX31_DATA_BM                           0xFFFFFFFFUL

#endif
