// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:22
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x41000000 -dat_sz 32 -i srat_regs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x41000000 -dat_sz 32 -i srat_regs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc/srat_regs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 3b5f7a46494bf76f36844df11987c4c3e9d29b29
//
// ===========================================================================


#ifndef __SRAT_REGS_H
#define __SRAT_REGS_H

#define SRAT_BASE 0x41000000UL
// --------------------------------------------------------------
// SCFG
// 
#define SRAT_SCFG_ADR (SRAT_BASE + 0x0000UL)
static volatile unsigned long* const SP_SRAT_SCFG = (unsigned long*) SRAT_SCFG_ADR;
#define S_SRAT_SCFG (*SP_SRAT_SCFG)
// bitfield: SCFG_RTCTRACKINT
#define SRAT_SCFG_RTCTRACKINT                         8UL
#define SRAT_SCFG_RTCTRACKINT_BM                      0x00000F00UL
// enums for bitfield SCFG_RTCTRACKINT (width: 4)UL
#define SRAT_SCFG_RTCTRACKINT__32US                   0x0UL
#define SRAT_SCFG_RTCTRACKINT__64US                   0x1UL
#define SRAT_SCFG_RTCTRACKINT__128US                  0x2UL
#define SRAT_SCFG_RTCTRACKINT__256US                  0x3UL
#define SRAT_SCFG_RTCTRACKINT__512US                  0x4UL
#define SRAT_SCFG_RTCTRACKINT__1MS                    0x5UL
#define SRAT_SCFG_RTCTRACKINT__2MS                    0x6UL
#define SRAT_SCFG_RTCTRACKINT__4MS                    0x7UL
#define SRAT_SCFG_RTCTRACKINT__8MS                    0x8UL
#define SRAT_SCFG_RTCTRACKINT__16MS                   0x9UL
#define SRAT_SCFG_RTCTRACKINT__32MS                   0xAUL
#define SRAT_SCFG_RTCTRACKINT__64MS                   0xBUL
#define SRAT_SCFG_RTCTRACKINT__128MS                  0xCUL
#define SRAT_SCFG_RTCTRACKINT__256MS                  0xDUL
#define SRAT_SCFG_RTCTRACKINT__512MS                  0xEUL
#define SRAT_SCFG_RTCTRACKINT__1S                     0xFUL
// bitfield: SCFG_RTCTRACKSPEED
#define SRAT_SCFG_RTCTRACKSPEED                       6UL
#define SRAT_SCFG_RTCTRACKSPEED_BM                    0x000000C0UL
// enums for bitfield SCFG_RTCTRACKSPEED (width: 2)UL
#define SRAT_SCFG_RTCTRACKSPEED_USE_976PPM            0x0UL
#define SRAT_SCFG_RTCTRACKSPEED_USE_1353PPM           0x1UL
#define SRAT_SCFG_RTCTRACKSPEED_USE_3906PPM           0x2UL
#define SRAT_SCFG_RTCTRACKSPEED_USE_7812PPM           0x3UL
// bitfield: SCFG_RTCTRACKPREC
#define SRAT_SCFG_RTCTRACKPREC                        4UL
#define SRAT_SCFG_RTCTRACKPREC_BM                     0x00000030UL
// enums for bitfield SCFG_RTCTRACKPREC (width: 2)UL
#define SRAT_SCFG_RTCTRACKPREC__0P25US                0x0UL
#define SRAT_SCFG_RTCTRACKPREC__0P5US                 0x1UL
#define SRAT_SCFG_RTCTRACKPREC__1US                   0x2UL
#define SRAT_SCFG_RTCTRACKPREC__2US                   0x3UL
// bitfield: SCFG_RTCTRACK
#define SRAT_SCFG_RTCTRACK                            3UL
#define SRAT_SCFG_RTCTRACK_BM                         0x00000008UL
// enums for bitfield SCFG_RTCTRACK (width: 1)UL
#define SRAT_SCFG_RTCTRACK_DISABLE                    0x0UL
#define SRAT_SCFG_RTCTRACK_ENABLE                     0x1UL
// bitfield: SCFG_RTCCAPT
#define SRAT_SCFG_RTCCAPT                             2UL
#define SRAT_SCFG_RTCCAPT_BM                          0x00000004UL
// enums for bitfield SCFG_RTCCAPT (width: 1)UL
#define SRAT_SCFG_RTCCAPT_DISABLE                     0x0UL
#define SRAT_SCFG_RTCCAPT_ENABLE                      0x1UL
// bitfield: SCFG_FRACRAT
#define SRAT_SCFG_FRACRAT                             1UL
#define SRAT_SCFG_FRACRAT_BM                          0x00000002UL
// enums for bitfield SCFG_FRACRAT (width: 1)UL
#define SRAT_SCFG_FRACRAT_DISABLE                     0x0UL
#define SRAT_SCFG_FRACRAT_ENABLE                      0x1UL
// bitfield: SCFG_TIMEN
#define SRAT_SCFG_TIMEN                               0UL
#define SRAT_SCFG_TIMEN_BM                            0x00000001UL
// enums for bitfield SCFG_TIMEN (width: 1)UL
#define SRAT_SCFG_TIMEN_DISABLE                       0x0UL
#define SRAT_SCFG_TIMEN_ENABLE                        0x1UL
// --------------------------------------------------------------
// SCNT
// 
#define SRAT_SCNT_ADR (SRAT_BASE + 0x0004UL)
static volatile unsigned long* const SP_SRAT_SCNT = (unsigned long*) SRAT_SCNT_ADR;
#define S_SRAT_SCNT (*SP_SRAT_SCNT)
// bitfield: SCNT_VAL
#define SRAT_SCNT_VAL                                 0UL
#define SRAT_SCNT_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCNT_VAL (width: 32)UL
#define SRAT_SCNT_VAL_ALLZEROS                        0x00000000UL
#define SRAT_SCNT_VAL_ALLONES                         0xFFFFFFFFUL
// --------------------------------------------------------------
// SADJ
// 
#define SRAT_SADJ_ADR (SRAT_BASE + 0x0008UL)
static volatile unsigned long* const SP_SRAT_SADJ = (unsigned long*) SRAT_SADJ_ADR;
#define S_SRAT_SADJ (*SP_SRAT_SADJ)
// bitfield: SADJ_VAL
#define SRAT_SADJ_VAL                                 0UL
#define SRAT_SADJ_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SADJ_VAL (width: 32)UL
#define SRAT_SADJ_VAL_ALLZEROS                        0x00000000UL
#define SRAT_SADJ_VAL_ALLONES                         0xFFFFFFFFUL
// --------------------------------------------------------------
// SARMSET
// 
#define SRAT_SARMSET_ADR (SRAT_BASE + 0x000CUL)
static volatile unsigned long* const SP_SRAT_SARMSET = (unsigned long*) SRAT_SARMSET_ADR;
#define S_SRAT_SARMSET (*SP_SRAT_SARMSET)
// bitfield: SARMSET_ARM
#define SRAT_SARMSET_ARM                              0UL
#define SRAT_SARMSET_ARM_BM                           0x000000FFUL
// enums for bitfield SARMSET_ARM (width: 8)UL
#define SRAT_SARMSET_ARM_IGNORED                      0x00UL
#define SRAT_SARMSET_ARM_ARM                          0x01UL
// --------------------------------------------------------------
// SARMCLR
// 
#define SRAT_SARMCLR_ADR (SRAT_BASE + 0x0010UL)
static volatile unsigned long* const SP_SRAT_SARMCLR = (unsigned long*) SRAT_SARMCLR_ADR;
#define S_SRAT_SARMCLR (*SP_SRAT_SARMCLR)
// bitfield: SARMCLR_ARM
#define SRAT_SARMCLR_ARM                              0UL
#define SRAT_SARMCLR_ARM_BM                           0x000000FFUL
// enums for bitfield SARMCLR_ARM (width: 8)UL
#define SRAT_SARMCLR_ARM_DISARM                       0x00UL
#define SRAT_SARMCLR_ARM_IGNORED                      0x01UL
// --------------------------------------------------------------
// SEVT
// 
#define SRAT_SEVT_ADR (SRAT_BASE + 0x0014UL)
static volatile unsigned long* const SP_SRAT_SEVT = (unsigned long*) SRAT_SEVT_ADR;
#define S_SRAT_SEVT (*SP_SRAT_SEVT)
// bitfield: SEVT_OEVT7
#define SRAT_SEVT_OEVT7                               28UL
#define SRAT_SEVT_OEVT7_BM                            0xF0000000UL
// enums for bitfield SEVT_OEVT7 (width: 4)UL
#define SRAT_SEVT_OEVT7_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT7_ALLONES                       0xFUL
// bitfield: SEVT_OEVT6
#define SRAT_SEVT_OEVT6                               24UL
#define SRAT_SEVT_OEVT6_BM                            0x0F000000UL
// enums for bitfield SEVT_OEVT6 (width: 4)UL
#define SRAT_SEVT_OEVT6_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT6_ALLONES                       0xFUL
// bitfield: SEVT_OEVT5
#define SRAT_SEVT_OEVT5                               20UL
#define SRAT_SEVT_OEVT5_BM                            0x00F00000UL
// enums for bitfield SEVT_OEVT5 (width: 4)UL
#define SRAT_SEVT_OEVT5_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT5_ALLONES                       0xFUL
// bitfield: SEVT_OEVT4
#define SRAT_SEVT_OEVT4                               16UL
#define SRAT_SEVT_OEVT4_BM                            0x000F0000UL
// enums for bitfield SEVT_OEVT4 (width: 4)UL
#define SRAT_SEVT_OEVT4_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT4_ALLONES                       0xFUL
// bitfield: SEVT_OEVT3
#define SRAT_SEVT_OEVT3                               12UL
#define SRAT_SEVT_OEVT3_BM                            0x0000F000UL
// enums for bitfield SEVT_OEVT3 (width: 4)UL
#define SRAT_SEVT_OEVT3_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT3_ALLONES                       0xFUL
// bitfield: SEVT_OEVT2
#define SRAT_SEVT_OEVT2                               8UL
#define SRAT_SEVT_OEVT2_BM                            0x00000F00UL
// enums for bitfield SEVT_OEVT2 (width: 4)UL
#define SRAT_SEVT_OEVT2_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT2_ALLONES                       0xFUL
// bitfield: SEVT_OEVT1
#define SRAT_SEVT_OEVT1                               4UL
#define SRAT_SEVT_OEVT1_BM                            0x000000F0UL
// enums for bitfield SEVT_OEVT1 (width: 4)UL
#define SRAT_SEVT_OEVT1_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT1_ALLONES                       0xFUL
// bitfield: SEVT_OEVT0
#define SRAT_SEVT_OEVT0                               0UL
#define SRAT_SEVT_OEVT0_BM                            0x0000000FUL
// enums for bitfield SEVT_OEVT0 (width: 4)UL
#define SRAT_SEVT_OEVT0_ALLZEROS                      0x0UL
#define SRAT_SEVT_OEVT0_ALLONES                       0xFUL
// --------------------------------------------------------------
// SOUT
// 
#define SRAT_SOUT_ADR (SRAT_BASE + 0x0018UL)
static volatile unsigned long* const SP_SRAT_SOUT = (unsigned long*) SRAT_SOUT_ADR;
#define S_SRAT_SOUT (*SP_SRAT_SOUT)
// bitfield: SOUT_OUT7
#define SRAT_SOUT_OUT7                                31UL
#define SRAT_SOUT_OUT7_BM                             0x80000000UL
// enums for bitfield SOUT_OUT7 (width: 1)UL
#define SRAT_SOUT_OUT7_ZERO                           0x0UL
#define SRAT_SOUT_OUT7_ONE                            0x1UL
// bitfield: SOUT_OMODE7
#define SRAT_SOUT_OMODE7                              28UL
#define SRAT_SOUT_OMODE7_BM                           0x70000000UL
// enums for bitfield SOUT_OMODE7 (width: 3)UL
#define SRAT_SOUT_OMODE7_PULSE                        0x0UL
#define SRAT_SOUT_OMODE7_SET                          0x1UL
#define SRAT_SOUT_OMODE7_CLR                          0x2UL
#define SRAT_SOUT_OMODE7_TGL                          0x3UL
#define SRAT_SOUT_OMODE7_LOW                          0x4UL
#define SRAT_SOUT_OMODE7_HIGH                         0x5UL
// bitfield: SOUT_OUT6
#define SRAT_SOUT_OUT6                                27UL
#define SRAT_SOUT_OUT6_BM                             0x08000000UL
// enums for bitfield SOUT_OUT6 (width: 1)UL
#define SRAT_SOUT_OUT6_ZERO                           0x0UL
#define SRAT_SOUT_OUT6_ONE                            0x1UL
// bitfield: SOUT_OMODE6
#define SRAT_SOUT_OMODE6                              24UL
#define SRAT_SOUT_OMODE6_BM                           0x07000000UL
// enums for bitfield SOUT_OMODE6 (width: 3)UL
#define SRAT_SOUT_OMODE6_PULSE                        0x0UL
#define SRAT_SOUT_OMODE6_SET                          0x1UL
#define SRAT_SOUT_OMODE6_CLR                          0x2UL
#define SRAT_SOUT_OMODE6_TGL                          0x3UL
#define SRAT_SOUT_OMODE6_LOW                          0x4UL
#define SRAT_SOUT_OMODE6_HIGH                         0x5UL
// bitfield: SOUT_OUT5
#define SRAT_SOUT_OUT5                                23UL
#define SRAT_SOUT_OUT5_BM                             0x00800000UL
// enums for bitfield SOUT_OUT5 (width: 1)UL
#define SRAT_SOUT_OUT5_ZERO                           0x0UL
#define SRAT_SOUT_OUT5_ONE                            0x1UL
// bitfield: SOUT_OMODE5
#define SRAT_SOUT_OMODE5                              20UL
#define SRAT_SOUT_OMODE5_BM                           0x00700000UL
// enums for bitfield SOUT_OMODE5 (width: 3)UL
#define SRAT_SOUT_OMODE5_PULSE                        0x0UL
#define SRAT_SOUT_OMODE5_SET                          0x1UL
#define SRAT_SOUT_OMODE5_CLR                          0x2UL
#define SRAT_SOUT_OMODE5_TGL                          0x3UL
#define SRAT_SOUT_OMODE5_LOW                          0x4UL
#define SRAT_SOUT_OMODE5_HIGH                         0x5UL
// bitfield: SOUT_OUT4
#define SRAT_SOUT_OUT4                                19UL
#define SRAT_SOUT_OUT4_BM                             0x00080000UL
// enums for bitfield SOUT_OUT4 (width: 1)UL
#define SRAT_SOUT_OUT4_ZERO                           0x0UL
#define SRAT_SOUT_OUT4_ONE                            0x1UL
// bitfield: SOUT_OMODE4
#define SRAT_SOUT_OMODE4                              16UL
#define SRAT_SOUT_OMODE4_BM                           0x00070000UL
// enums for bitfield SOUT_OMODE4 (width: 3)UL
#define SRAT_SOUT_OMODE4_PULSE                        0x0UL
#define SRAT_SOUT_OMODE4_SET                          0x1UL
#define SRAT_SOUT_OMODE4_CLR                          0x2UL
#define SRAT_SOUT_OMODE4_TGL                          0x3UL
#define SRAT_SOUT_OMODE4_LOW                          0x4UL
#define SRAT_SOUT_OMODE4_HIGH                         0x5UL
// bitfield: SOUT_OUT3
#define SRAT_SOUT_OUT3                                15UL
#define SRAT_SOUT_OUT3_BM                             0x00008000UL
// enums for bitfield SOUT_OUT3 (width: 1)UL
#define SRAT_SOUT_OUT3_ZERO                           0x0UL
#define SRAT_SOUT_OUT3_ONE                            0x1UL
// bitfield: SOUT_OMODE3
#define SRAT_SOUT_OMODE3                              12UL
#define SRAT_SOUT_OMODE3_BM                           0x00007000UL
// enums for bitfield SOUT_OMODE3 (width: 3)UL
#define SRAT_SOUT_OMODE3_PULSE                        0x0UL
#define SRAT_SOUT_OMODE3_SET                          0x1UL
#define SRAT_SOUT_OMODE3_CLR                          0x2UL
#define SRAT_SOUT_OMODE3_TGL                          0x3UL
#define SRAT_SOUT_OMODE3_LOW                          0x4UL
#define SRAT_SOUT_OMODE3_HIGH                         0x5UL
// bitfield: SOUT_OUT2
#define SRAT_SOUT_OUT2                                11UL
#define SRAT_SOUT_OUT2_BM                             0x00000800UL
// enums for bitfield SOUT_OUT2 (width: 1)UL
#define SRAT_SOUT_OUT2_ZERO                           0x0UL
#define SRAT_SOUT_OUT2_ONE                            0x1UL
// bitfield: SOUT_OMODE2
#define SRAT_SOUT_OMODE2                              8UL
#define SRAT_SOUT_OMODE2_BM                           0x00000700UL
// enums for bitfield SOUT_OMODE2 (width: 3)UL
#define SRAT_SOUT_OMODE2_PULSE                        0x0UL
#define SRAT_SOUT_OMODE2_SET                          0x1UL
#define SRAT_SOUT_OMODE2_CLR                          0x2UL
#define SRAT_SOUT_OMODE2_TGL                          0x3UL
#define SRAT_SOUT_OMODE2_LOW                          0x4UL
#define SRAT_SOUT_OMODE2_HIGH                         0x5UL
// bitfield: SOUT_OUT1
#define SRAT_SOUT_OUT1                                7UL
#define SRAT_SOUT_OUT1_BM                             0x00000080UL
// enums for bitfield SOUT_OUT1 (width: 1)UL
#define SRAT_SOUT_OUT1_ZERO                           0x0UL
#define SRAT_SOUT_OUT1_ONE                            0x1UL
// bitfield: SOUT_OMODE1
#define SRAT_SOUT_OMODE1                              4UL
#define SRAT_SOUT_OMODE1_BM                           0x00000070UL
// enums for bitfield SOUT_OMODE1 (width: 3)UL
#define SRAT_SOUT_OMODE1_PULSE                        0x0UL
#define SRAT_SOUT_OMODE1_SET                          0x1UL
#define SRAT_SOUT_OMODE1_CLR                          0x2UL
#define SRAT_SOUT_OMODE1_TGL                          0x3UL
#define SRAT_SOUT_OMODE1_LOW                          0x4UL
#define SRAT_SOUT_OMODE1_HIGH                         0x5UL
// bitfield: SOUT_OUT0
#define SRAT_SOUT_OUT0                                3UL
#define SRAT_SOUT_OUT0_BM                             0x00000008UL
// enums for bitfield SOUT_OUT0 (width: 1)UL
#define SRAT_SOUT_OUT0_ZERO                           0x0UL
#define SRAT_SOUT_OUT0_ONE                            0x1UL
// bitfield: SOUT_OMODE0
#define SRAT_SOUT_OMODE0                              0UL
#define SRAT_SOUT_OMODE0_BM                           0x00000007UL
// enums for bitfield SOUT_OMODE0 (width: 3)UL
#define SRAT_SOUT_OMODE0_PULSE                        0x0UL
#define SRAT_SOUT_OMODE0_SET                          0x1UL
#define SRAT_SOUT_OMODE0_CLR                          0x2UL
#define SRAT_SOUT_OMODE0_TGL                          0x3UL
#define SRAT_SOUT_OMODE0_LOW                          0x4UL
#define SRAT_SOUT_OMODE0_HIGH                         0x5UL
// --------------------------------------------------------------
// SCOMPENSATION
// 
#define SRAT_SCOMPENSATION_ADR (SRAT_BASE + 0x001CUL)
static volatile unsigned long* const SP_SRAT_SCOMPENSATION = (unsigned long*) SRAT_SCOMPENSATION_ADR;
#define S_SRAT_SCOMPENSATION (*SP_SRAT_SCOMPENSATION)
// bitfield: SCOMPENSATION_VAL
#define SRAT_SCOMPENSATION_VAL                        0UL
#define SRAT_SCOMPENSATION_VAL_BM                     0x0000FFFFUL
// enums for bitfield SCOMPENSATION_VAL (width: 16)UL
#define SRAT_SCOMPENSATION_VAL_ALLZEROS               0x0000UL
#define SRAT_SCOMPENSATION_VAL_ALLONES                0xFFFFUL
// --------------------------------------------------------------
// SRTCCAPT
// 
#define SRAT_SRTCCAPT_ADR (SRAT_BASE + 0x0020UL)
static volatile unsigned long* const SP_SRAT_SRTCCAPT = (unsigned long*) SRAT_SRTCCAPT_ADR;
#define S_SRAT_SRTCCAPT (*SP_SRAT_SRTCCAPT)
// bitfield: SRTCCAPT_VAL
#define SRAT_SRTCCAPT_VAL                             0UL
#define SRAT_SRTCCAPT_VAL_BM                          0xFFFFFFFFUL
// enums for bitfield SRTCCAPT_VAL (width: 32)UL
#define SRAT_SRTCCAPT_VAL_ALLZEROS                    0x00000000UL
#define SRAT_SRTCCAPT_VAL_ALLONES                     0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH0CFG
// 
#define SRAT_SCH0CFG_ADR (SRAT_BASE + 0x0040UL)
static volatile unsigned long* const SP_SRAT_SCH0CFG = (unsigned long*) SRAT_SCH0CFG_ADR;
#define S_SRAT_SCH0CFG (*SP_SRAT_SCH0CFG)
// bitfield: SCH0CFG_SRC
#define SRAT_SCH0CFG_SRC                              8UL
#define SRAT_SCH0CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH0CFG_SRC (width: 5)UL
#define SRAT_SCH0CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH0CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH0CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH0CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH0CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH0CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH0CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH0CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH0CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH0CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH0CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH0CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH0CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH0CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH0CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH0CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH0CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH0CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH0CFG_SRC_RFE2                         0x13UL
// bitfield: SCH0CFG_INP
#define SRAT_SCH0CFG_INP                              2UL
#define SRAT_SCH0CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH0CFG_INP (width: 2)UL
#define SRAT_SCH0CFG_INP_RISE                         0x0UL
#define SRAT_SCH0CFG_INP_FALL                         0x1UL
#define SRAT_SCH0CFG_INP_BOTH                         0x2UL
// bitfield: SCH0CFG_MODE
#define SRAT_SCH0CFG_MODE                             0UL
#define SRAT_SCH0CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH0CFG_MODE (width: 2)UL
#define SRAT_SCH0CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH0CFG_MODE_COMP                        0x1UL
#define SRAT_SCH0CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH0CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH1CFG
// 
#define SRAT_SCH1CFG_ADR (SRAT_BASE + 0x0044UL)
static volatile unsigned long* const SP_SRAT_SCH1CFG = (unsigned long*) SRAT_SCH1CFG_ADR;
#define S_SRAT_SCH1CFG (*SP_SRAT_SCH1CFG)
// bitfield: SCH1CFG_SRC
#define SRAT_SCH1CFG_SRC                              8UL
#define SRAT_SCH1CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH1CFG_SRC (width: 5)UL
#define SRAT_SCH1CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH1CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH1CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH1CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH1CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH1CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH1CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH1CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH1CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH1CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH1CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH1CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH1CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH1CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH1CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH1CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH1CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH1CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH1CFG_SRC_RFE2                         0x13UL
// bitfield: SCH1CFG_INP
#define SRAT_SCH1CFG_INP                              2UL
#define SRAT_SCH1CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH1CFG_INP (width: 2)UL
#define SRAT_SCH1CFG_INP_RISE                         0x0UL
#define SRAT_SCH1CFG_INP_FALL                         0x1UL
#define SRAT_SCH1CFG_INP_BOTH                         0x2UL
// bitfield: SCH1CFG_MODE
#define SRAT_SCH1CFG_MODE                             0UL
#define SRAT_SCH1CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH1CFG_MODE (width: 2)UL
#define SRAT_SCH1CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH1CFG_MODE_COMP                        0x1UL
#define SRAT_SCH1CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH1CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH2CFG
// 
#define SRAT_SCH2CFG_ADR (SRAT_BASE + 0x0048UL)
static volatile unsigned long* const SP_SRAT_SCH2CFG = (unsigned long*) SRAT_SCH2CFG_ADR;
#define S_SRAT_SCH2CFG (*SP_SRAT_SCH2CFG)
// bitfield: SCH2CFG_SRC
#define SRAT_SCH2CFG_SRC                              8UL
#define SRAT_SCH2CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH2CFG_SRC (width: 5)UL
#define SRAT_SCH2CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH2CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH2CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH2CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH2CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH2CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH2CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH2CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH2CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH2CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH2CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH2CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH2CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH2CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH2CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH2CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH2CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH2CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH2CFG_SRC_RFE2                         0x13UL
// bitfield: SCH2CFG_INP
#define SRAT_SCH2CFG_INP                              2UL
#define SRAT_SCH2CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH2CFG_INP (width: 2)UL
#define SRAT_SCH2CFG_INP_POSDGE                       0x0UL
#define SRAT_SCH2CFG_INP_FALL                         0x1UL
#define SRAT_SCH2CFG_INP_BOTH                         0x2UL
// bitfield: SCH2CFG_MODE
#define SRAT_SCH2CFG_MODE                             0UL
#define SRAT_SCH2CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH2CFG_MODE (width: 2)UL
#define SRAT_SCH2CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH2CFG_MODE_COMP                        0x1UL
#define SRAT_SCH2CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH2CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH3CFG
// 
#define SRAT_SCH3CFG_ADR (SRAT_BASE + 0x004CUL)
static volatile unsigned long* const SP_SRAT_SCH3CFG = (unsigned long*) SRAT_SCH3CFG_ADR;
#define S_SRAT_SCH3CFG (*SP_SRAT_SCH3CFG)
// bitfield: SCH3CFG_SRC
#define SRAT_SCH3CFG_SRC                              8UL
#define SRAT_SCH3CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH3CFG_SRC (width: 5)UL
#define SRAT_SCH3CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH3CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH3CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH3CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH3CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH3CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH3CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH3CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH3CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH3CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH3CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH3CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH3CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH3CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH3CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH3CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH3CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH3CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH3CFG_SRC_RFE2                         0x13UL
// bitfield: SCH3CFG_INP
#define SRAT_SCH3CFG_INP                              2UL
#define SRAT_SCH3CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH3CFG_INP (width: 2)UL
#define SRAT_SCH3CFG_INP_RISE                         0x0UL
#define SRAT_SCH3CFG_INP_FALL                         0x1UL
#define SRAT_SCH3CFG_INP_BOTH                         0x2UL
// bitfield: SCH3CFG_MODE
#define SRAT_SCH3CFG_MODE                             0UL
#define SRAT_SCH3CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH3CFG_MODE (width: 2)UL
#define SRAT_SCH3CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH3CFG_MODE_COMP                        0x1UL
#define SRAT_SCH3CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH3CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH4CFG
// 
#define SRAT_SCH4CFG_ADR (SRAT_BASE + 0x0050UL)
static volatile unsigned long* const SP_SRAT_SCH4CFG = (unsigned long*) SRAT_SCH4CFG_ADR;
#define S_SRAT_SCH4CFG (*SP_SRAT_SCH4CFG)
// bitfield: SCH4CFG_SRC
#define SRAT_SCH4CFG_SRC                              8UL
#define SRAT_SCH4CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH4CFG_SRC (width: 5)UL
#define SRAT_SCH4CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH4CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH4CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH4CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH4CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH4CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH4CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH4CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH4CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH4CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH4CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH4CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH4CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH4CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH4CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH4CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH4CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH4CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH4CFG_SRC_RFE2                         0x13UL
// bitfield: SCH4CFG_INP
#define SRAT_SCH4CFG_INP                              2UL
#define SRAT_SCH4CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH4CFG_INP (width: 2)UL
#define SRAT_SCH4CFG_INP_RISE                         0x0UL
#define SRAT_SCH4CFG_INP_FALL                         0x1UL
#define SRAT_SCH4CFG_INP_BOTH                         0x2UL
// bitfield: SCH4CFG_MODE
#define SRAT_SCH4CFG_MODE                             0UL
#define SRAT_SCH4CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH4CFG_MODE (width: 2)UL
#define SRAT_SCH4CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH4CFG_MODE_COMP                        0x1UL
#define SRAT_SCH4CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH4CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH5CFG
// 
#define SRAT_SCH5CFG_ADR (SRAT_BASE + 0x0054UL)
static volatile unsigned long* const SP_SRAT_SCH5CFG = (unsigned long*) SRAT_SCH5CFG_ADR;
#define S_SRAT_SCH5CFG (*SP_SRAT_SCH5CFG)
// bitfield: SCH5CFG_SRC
#define SRAT_SCH5CFG_SRC                              8UL
#define SRAT_SCH5CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH5CFG_SRC (width: 5)UL
#define SRAT_SCH5CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH5CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH5CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH5CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH5CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH5CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH5CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH5CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH5CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH5CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH5CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH5CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH5CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH5CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH5CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH5CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH5CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH5CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH5CFG_SRC_RFE2                         0x13UL
// bitfield: SCH5CFG_INP
#define SRAT_SCH5CFG_INP                              2UL
#define SRAT_SCH5CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH5CFG_INP (width: 2)UL
#define SRAT_SCH5CFG_INP_RISE                         0x0UL
#define SRAT_SCH5CFG_INP_FALL                         0x1UL
#define SRAT_SCH5CFG_INP_BOTH                         0x2UL
// bitfield: SCH5CFG_MODE
#define SRAT_SCH5CFG_MODE                             0UL
#define SRAT_SCH5CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH5CFG_MODE (width: 2)UL
#define SRAT_SCH5CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH5CFG_MODE_COMP                        0x1UL
#define SRAT_SCH5CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH5CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH6CFG
// 
#define SRAT_SCH6CFG_ADR (SRAT_BASE + 0x0058UL)
static volatile unsigned long* const SP_SRAT_SCH6CFG = (unsigned long*) SRAT_SCH6CFG_ADR;
#define S_SRAT_SCH6CFG (*SP_SRAT_SCH6CFG)
// bitfield: SCH6CFG_SRC
#define SRAT_SCH6CFG_SRC                              8UL
#define SRAT_SCH6CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH6CFG_SRC (width: 5)UL
#define SRAT_SCH6CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH6CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH6CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH6CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH6CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH6CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH6CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH6CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH6CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH6CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH6CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH6CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH6CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH6CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH6CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH6CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH6CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH6CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH6CFG_SRC_RFE2                         0x13UL
// bitfield: SCH6CFG_INP
#define SRAT_SCH6CFG_INP                              2UL
#define SRAT_SCH6CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH6CFG_INP (width: 2)UL
#define SRAT_SCH6CFG_INP_RISE                         0x0UL
#define SRAT_SCH6CFG_INP_FALL                         0x1UL
#define SRAT_SCH6CFG_INP_BOTH                         0x2UL
// bitfield: SCH6CFG_MODE
#define SRAT_SCH6CFG_MODE                             0UL
#define SRAT_SCH6CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH6CFG_MODE (width: 2)UL
#define SRAT_SCH6CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH6CFG_MODE_COMP                        0x1UL
#define SRAT_SCH6CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH6CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH7CFG
// 
#define SRAT_SCH7CFG_ADR (SRAT_BASE + 0x005CUL)
static volatile unsigned long* const SP_SRAT_SCH7CFG = (unsigned long*) SRAT_SCH7CFG_ADR;
#define S_SRAT_SCH7CFG (*SP_SRAT_SCH7CFG)
// bitfield: SCH7CFG_SRC
#define SRAT_SCH7CFG_SRC                              8UL
#define SRAT_SCH7CFG_SRC_BM                           0x00001F00UL
// enums for bitfield SCH7CFG_SRC (width: 5)UL
#define SRAT_SCH7CFG_SRC_GPI0                         0x00UL
#define SRAT_SCH7CFG_SRC_GPI1                         0x01UL
#define SRAT_SCH7CFG_SRC_GPI2                         0x02UL
#define SRAT_SCH7CFG_SRC_GPI3                         0x03UL
#define SRAT_SCH7CFG_SRC_GPI4                         0x04UL
#define SRAT_SCH7CFG_SRC_GPI5                         0x05UL
#define SRAT_SCH7CFG_SRC_GPI6                         0x06UL
#define SRAT_SCH7CFG_SRC_GPI7                         0x07UL
#define SRAT_SCH7CFG_SRC_MDM0                         0x08UL
#define SRAT_SCH7CFG_SRC_MDM1                         0x09UL
#define SRAT_SCH7CFG_SRC_MDM2                         0x0AUL
#define SRAT_SCH7CFG_SRC_MDM3                         0x0BUL
#define SRAT_SCH7CFG_SRC_MDM4                         0x0CUL
#define SRAT_SCH7CFG_SRC_MDM5                         0x0DUL
#define SRAT_SCH7CFG_SRC_CORR                         0x0FUL
#define SRAT_SCH7CFG_SRC_RFECMDDONE                   0x10UL
#define SRAT_SCH7CFG_SRC_RFE0                         0x11UL
#define SRAT_SCH7CFG_SRC_RFE1                         0x12UL
#define SRAT_SCH7CFG_SRC_RFE2                         0x13UL
// bitfield: SCH7CFG_INP
#define SRAT_SCH7CFG_INP                              2UL
#define SRAT_SCH7CFG_INP_BM                           0x0000000CUL
// enums for bitfield SCH7CFG_INP (width: 2)UL
#define SRAT_SCH7CFG_INP_RISE                         0x0UL
#define SRAT_SCH7CFG_INP_FALL                         0x1UL
#define SRAT_SCH7CFG_INP_BOTH                         0x2UL
// bitfield: SCH7CFG_MODE
#define SRAT_SCH7CFG_MODE                             0UL
#define SRAT_SCH7CFG_MODE_BM                          0x00000003UL
// enums for bitfield SCH7CFG_MODE (width: 2)UL
#define SRAT_SCH7CFG_MODE_DISABLE                     0x0UL
#define SRAT_SCH7CFG_MODE_COMP                        0x1UL
#define SRAT_SCH7CFG_MODE_SINGLECAPT                  0x2UL
#define SRAT_SCH7CFG_MODE_REPEATCAPT                  0x3UL
// --------------------------------------------------------------
// SCH0
// 
#define SRAT_SCH0_ADR (SRAT_BASE + 0x0080UL)
static volatile unsigned long* const SP_SRAT_SCH0 = (unsigned long*) SRAT_SCH0_ADR;
#define S_SRAT_SCH0 (*SP_SRAT_SCH0)
// bitfield: SCH0_VAL
#define SRAT_SCH0_VAL                                 0UL
#define SRAT_SCH0_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH0_VAL (width: 32)UL
#define SRAT_SCH0_VAL_MIN                             0x00000000UL
#define SRAT_SCH0_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH1
// 
#define SRAT_SCH1_ADR (SRAT_BASE + 0x0084UL)
static volatile unsigned long* const SP_SRAT_SCH1 = (unsigned long*) SRAT_SCH1_ADR;
#define S_SRAT_SCH1 (*SP_SRAT_SCH1)
// bitfield: SCH1_VAL
#define SRAT_SCH1_VAL                                 0UL
#define SRAT_SCH1_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH1_VAL (width: 32)UL
#define SRAT_SCH1_VAL_MIN                             0x00000000UL
#define SRAT_SCH1_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH2
// 
#define SRAT_SCH2_ADR (SRAT_BASE + 0x0088UL)
static volatile unsigned long* const SP_SRAT_SCH2 = (unsigned long*) SRAT_SCH2_ADR;
#define S_SRAT_SCH2 (*SP_SRAT_SCH2)
// bitfield: SCH2_VAL
#define SRAT_SCH2_VAL                                 0UL
#define SRAT_SCH2_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH2_VAL (width: 32)UL
#define SRAT_SCH2_VAL_MIN                             0x00000000UL
#define SRAT_SCH2_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH3
// 
#define SRAT_SCH3_ADR (SRAT_BASE + 0x008CUL)
static volatile unsigned long* const SP_SRAT_SCH3 = (unsigned long*) SRAT_SCH3_ADR;
#define S_SRAT_SCH3 (*SP_SRAT_SCH3)
// bitfield: SCH3_VAL
#define SRAT_SCH3_VAL                                 0UL
#define SRAT_SCH3_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH3_VAL (width: 32)UL
#define SRAT_SCH3_VAL_MIN                             0x00000000UL
#define SRAT_SCH3_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH4
// 
#define SRAT_SCH4_ADR (SRAT_BASE + 0x0090UL)
static volatile unsigned long* const SP_SRAT_SCH4 = (unsigned long*) SRAT_SCH4_ADR;
#define S_SRAT_SCH4 (*SP_SRAT_SCH4)
// bitfield: SCH4_VAL
#define SRAT_SCH4_VAL                                 0UL
#define SRAT_SCH4_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH4_VAL (width: 32)UL
#define SRAT_SCH4_VAL_MIN                             0x00000000UL
#define SRAT_SCH4_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH5
// 
#define SRAT_SCH5_ADR (SRAT_BASE + 0x0094UL)
static volatile unsigned long* const SP_SRAT_SCH5 = (unsigned long*) SRAT_SCH5_ADR;
#define S_SRAT_SCH5 (*SP_SRAT_SCH5)
// bitfield: SCH5_VAL
#define SRAT_SCH5_VAL                                 0UL
#define SRAT_SCH5_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH5_VAL (width: 32)UL
#define SRAT_SCH5_VAL_MIN                             0x00000000UL
#define SRAT_SCH5_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH6
// 
#define SRAT_SCH6_ADR (SRAT_BASE + 0x0098UL)
static volatile unsigned long* const SP_SRAT_SCH6 = (unsigned long*) SRAT_SCH6_ADR;
#define S_SRAT_SCH6 (*SP_SRAT_SCH6)
// bitfield: SCH6_VAL
#define SRAT_SCH6_VAL                                 0UL
#define SRAT_SCH6_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH6_VAL (width: 32)UL
#define SRAT_SCH6_VAL_MIN                             0x00000000UL
#define SRAT_SCH6_VAL_MAX                             0xFFFFFFFFUL
// --------------------------------------------------------------
// SCH7
// 
#define SRAT_SCH7_ADR (SRAT_BASE + 0x009CUL)
static volatile unsigned long* const SP_SRAT_SCH7 = (unsigned long*) SRAT_SCH7_ADR;
#define S_SRAT_SCH7 (*SP_SRAT_SCH7)
// bitfield: SCH7_VAL
#define SRAT_SCH7_VAL                                 0UL
#define SRAT_SCH7_VAL_BM                              0xFFFFFFFFUL
// enums for bitfield SCH7_VAL (width: 32)UL
#define SRAT_SCH7_VAL_MIN                             0x00000000UL
#define SRAT_SCH7_VAL_MAX                             0xFFFFFFFFUL

#endif
