// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-04-18 13:27:20
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/inc
// Commandline:  /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40081800 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/doc/TXFregs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl -target c -base 0x40081800 -dat_sz 32 -i /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/doc/TXFregs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tools/topsm/topsmregs.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 0d11a0ea4ba55ba3ef648be18aeec231d5314753
//
// /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/tc/octopus/regs/doc/TXFregs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: a4e533a5ddd72218513ee282987ba4536d7db944
//
// ===========================================================================


#ifndef __TXF_REGS_H
#define __TXF_REGS_H

#ifndef __HW_TYPES_H__ 
  #ifndef HWREG
    #define HWREG(x) (*((volatile unsigned long *)(x)))
  #endif
#endif
#define TXF_BASE 0x40081800UL
#define RF24_TXF_BASE 0x40081800UL
// --------------------------------------------------------------
// TXD
// 
#define TXF_TXD_ADR (TXF_BASE + 0x0000UL)
static volatile unsigned long* const SP_TXF_TXD = (unsigned long*) TXF_TXD_ADR;
#define S_TXF_TXD (*SP_TXF_TXD)
#define RF24_TXF_O_TXD                           0
// bitfield: TXD_DATA
#define TXF_TXD_DATA                                 0UL
#define RF24_TXF_TXD_DATA_S                      0UL
#define TXF_TXD_DATA_BM                              0xFFFFFFFFUL
#define RF24_TXF_TXD_DATA_M                      0xFFFFFFFFUL

#endif
