// This code snippet was auto-generated on Tue Apr 18 13:22:12 2023 using command: 
// perl $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEo$DSYNC_WORKSPACEl$DSYNC_WORKSPACEs$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEs$DSYNC_WORKSPACEm$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE2$DSYNC_WORKSPACEc$DSYNC_WORKSPACE.$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEi$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEM$DSYNC_WORKSPACED$DSYNC_WORKSPACEM$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEs$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEi$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE_$DSYNC_WORKSPACEm$DSYNC_WORKSPACEd$DSYNC_WORKSPACEm$DSYNC_WORKSPACE_$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEg$DSYNC_WORKSPACE_$DSYNC_WORKSPACEi$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACEe$DSYNC_WORKSPACE_$DSYNC_WORKSPACEd$DSYNC_WORKSPACEi$DSYNC_WORKSPACEf$DSYNC_WORKSPACEf$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE


// Source file: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/mce/ieee/doc/lrf_mdm_cfg_ieee_diff.txt
// Source last modified: 18-Apr-2023 13:20

#include "lrf_mdm_cfg_ieee_diff.h" 

const uint32_t lrf_mdm_cfg_ieee_diff[LRF_MDM_CFG_IEEE_DIFF_LENGTH] = {
    0x0000000F,                        // LRF_MDM_CFG_IEEE_DIFF_LENGTH-1
    0x20C0101A,                        // WSTART0 WREGIONID0
    0x00000003,                        //  MODPRECTRL     ADCDIGCONF    
    0x0000001F,                        //  MODSYMMAP1     MODSYMMAP0    
    0x80000000,                        //  BAUD           MODSOFTTX     
    0x0004000C,                        //  MODMAIN        BAUDPRE       
    0x00110000,                        //  DEMMISC1       DEMMISC0      
    0x10810009,                        //  DEMMISC3       DEMMISC2      
    0x00000000,                        //  DEMDSBU        DEMIQMC0      
    0x002B0670,                        //  DEMFIDC0       DEMCODC0      
    0x00050200,                        //  DEMDSXB0       DEMFEXB0      
    0x00000B60,                        //  DEMMAFI0       DEMFIFE0      
    0x00404010,                        //  DEMMAFI2       DEMMAFI1      
    0x20200006,                        //  DEMC1BE1       DEMC1BE0      
    0x0A2C0020,                        //  SPARE0         DEMC1BE2      
    0x00000014                         //  NOREG          SPARE1        
};

// This configuration assigns values to the following register bitfields:

//  REGISTER       REG VALUE        ADDRESS        BITFIELD NAME             BITFIELD VALUE           
// -----------------------------------------------------------------------------------------------
//  ADCDIGCONF      0x0003          0x20C0         qbranchen[1]              =    1 (bin)
//  ADCDIGCONF      0x0003          0x20C0         ibranchen[0]              =    1 (bin)
//  MODSYMMAP0      0x001F          0x20C8         sym1[7:4]                 =    1 (hex)
//  MODSYMMAP0      0x001F          0x20C8         sym0[3:0]                 =    F (hex)
//  BAUD            0x8000          0x20D4         rateword[15:0]            = 8000 (hex)
//  BAUDPRE         0x000C          0x20D8         prescaler[7:0]            =   0C (hex)
//  MODMAIN         0x0004          0x20DC         fecselect[3:2]            =   01 (bin)
//  DEMMISC1        0x0011          0x20E4         cdccolrst[4]              =    1 (bin)
//  DEMMISC1        0x0011          0x20E4         chfibw[1:0]               =   01 (bin)
//  DEMMISC2        0x0009          0x20E8         pdiflinpreden[3]          =    1 (bin)
//  DEMMISC2        0x0009          0x20E8         pdiflimitrange[0]         =    1 (bin)
//  DEMMISC3        0x1081          0x20EC         bde1filtmode[12]          =    1 (bin)
//  DEMMISC3        0x1081          0x20EC         bde1numstages[7]          =    1 (bin)
//  DEMMISC3        0x1081          0x20EC         bde2decratio[4:0]         =   01 (hex)
//  DEMCODC0        0x0670          0x20F8         compsel[10:9]             =   11 (bin)
//  DEMCODC0        0x0670          0x20F8         iirgain[7:5]              =  011 (bin)
//  DEMCODC0        0x0670          0x20F8         iiren[4]                  =    1 (bin)
//  DEMFIDC0        0x002B          0x20FC         compsel[5:4]              =   10 (bin)
//  DEMFIDC0        0x002B          0x20FC         accperiod[3:2]            =   10 (bin)
//  DEMFIDC0        0x002B          0x20FC         accmode[1]                =    1 (bin)
//  DEMFIDC0        0x002B          0x20FC         accen[0]                  =    1 (bin)
//  DEMFEXB0        0x0200          0x2100         out1srcsel[9:8]           =   10 (bin)
//  DEMDSXB0        0x0005          0x2104         outsrcsel1[2]             =    1 (bin)
//  DEMDSXB0        0x0005          0x2104         b1srcsel[0]               =    1 (bin)
//  DEMFIFE0        0x0B60          0x2108         finefoesel[11]            =    1 (bin)
//  DEMFIFE0        0x0B60          0x2108         focffsel[10:9]            =   01 (bin)
//  DEMFIFE0        0x0B60          0x2108         acccntmode[8]             =    1 (bin)
//  DEMFIFE0        0x0B60          0x2108         accperiod[7:6]            =   01 (bin)
//  DEMFIFE0        0x0B60          0x2108         accen[5]                  =    1 (bin)
//  DEMMAFI1        0x4010          0x2110         c3c5[15:8]                =   40 (hex)
//  DEMMAFI1        0x4010          0x2110         c2c6[7:0]                 =   10 (hex)
//  DEMMAFI2        0x0040          0x2114         c4[8:0]                   =  040 (hex)
//  DEMC1BE0        0x0006          0x2118         copyconf[3:0]             =    6 (hex)
//  DEMC1BE1        0x2020          0x211C         thresholdb[15:8]          =   20 (hex)
//  DEMC1BE1        0x2020          0x211C         thresholda[7:0]           =   20 (hex)
//  DEMC1BE2        0x0020          0x2120         thresholdc[7:0]           =   20 (hex)
//  SPARE0          0x0A2C          0x2124         val[15:0]                 = 0A2C (hex)
//  SPARE1          0x0014          0x2128         val[15:0]                 = 0014 (hex)

