// This code snippet was auto-generated on Tue Apr 18 13:21:36 2023 using command: 
// perl $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEo$DSYNC_WORKSPACEl$DSYNC_WORKSPACEs$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEs$DSYNC_WORKSPACEm$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE2$DSYNC_WORKSPACEc$DSYNC_WORKSPACE.$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEl$DSYNC_WORKSPACEe$DSYNC_WORKSPACE5$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEM$DSYNC_WORKSPACED$DSYNC_WORKSPACEM$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEs$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEl$DSYNC_WORKSPACEe$DSYNC_WORKSPACE5$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE_$DSYNC_WORKSPACEm$DSYNC_WORKSPACEd$DSYNC_WORKSPACEm$DSYNC_WORKSPACE_$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEg$DSYNC_WORKSPACE_$DSYNC_WORKSPACEb$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE


// Source file: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/mce/ble5/doc/lrf_mdm_cfg_blr.txt
// Source last modified: 18-Apr-2023 13:20

#include "lrf_mdm_cfg_blr.h" 

const uint32_t lrf_mdm_cfg_blr[LRF_MDM_CFG_BLR_LENGTH] = {
    0x0000000E,                        // LRF_MDM_CFG_BLR_LENGTH-1
    0x20C01019,                        // WSTART0 WREGIONID0
    0x00000003,                        //  MODPRECTRL     ADCDIGCONF    
    0x0000001F,                        //  MODSYMMAP1     MODSYMMAP0    
    0x40000000,                        //  BAUD           MODSOFTTX     
    0x0000000C,                        //  MODMAIN        BAUDPRE       
    0x00010000,                        //  DEMMISC1       DEMMISC0      
    0x158210D9,                        //  DEMMISC3       DEMMISC2      
    0x808D0000,                        //  DEMDSBU        DEMIQMC0      
    0x000006F0,                        //  DEMFIDC0       DEMCODC0      
    0x00060A24,                        //  DEMDSXB0       DEMFEXB0      
    0x0000000C,                        //  DEMMAFI0       DEMFIFE0      
    0x00783C14,                        //  DEMMAFI2       DEMMAFI1      
    0x7F7F001F,                        //  DEMC1BE1       DEMC1BE0      
    0x0A18014C                         //  SPARE0         DEMC1BE2      
};

// This configuration assigns values to the following register bitfields:

//  REGISTER       REG VALUE        ADDRESS        BITFIELD NAME             BITFIELD VALUE           
// -----------------------------------------------------------------------------------------------
//  ADCDIGCONF      0x0003          0x20C0         qbranchen[1]              =    1 (bin)
//  ADCDIGCONF      0x0003          0x20C0         ibranchen[0]              =    1 (bin)
//  MODSYMMAP0      0x001F          0x20C8         sym1[7:4]                 =    1 (hex)
//  MODSYMMAP0      0x001F          0x20C8         sym0[3:0]                 =    F (hex)
//  BAUD            0x4000          0x20D4         rateword[15:0]            = 4000 (hex)
//  BAUDPRE         0x000C          0x20D8         prescaler[7:0]            =   0C (hex)
//  DEMMISC1        0x0001          0x20E4         chfibw[1:0]               =   01 (bin)
//  DEMMISC2        0x10D9          0x20E8         mafcgain[13:12]           =   01 (bin)
//  DEMMISC2        0x10D9          0x20E8         stimteaperiod[9:7]        =  001 (bin)
//  DEMMISC2        0x10D9          0x20E8         stimteagain[6:4]          =  101 (bin)
//  DEMMISC2        0x10D9          0x20E8         pdiflinpreden[3]          =    1 (bin)
//  DEMMISC2        0x10D9          0x20E8         pdiflimitrange[0]         =    1 (bin)
//  DEMMISC3        0x1582          0x20EC         bde1filtmode[12]          =    1 (bin)
//  DEMMISC3        0x1582          0x20EC         lqiperiod[11:10]          =   01 (bin)
//  DEMMISC3        0x1582          0x20EC         bde1dvga[9:8]             =   01 (bin)
//  DEMMISC3        0x1582          0x20EC         bde1numstages[7]          =    1 (bin)
//  DEMMISC3        0x1582          0x20EC         bde2decratio[4:0]         =   02 (hex)
//  DEMDSBU         0x808D          0x20F4         dsbuavglength[15:8]       =   80 (hex)
//  DEMDSBU         0x808D          0x20F4         dsbudelay[7:0]            =   8D (hex)
//  DEMCODC0        0x06F0          0x20F8         compsel[10:9]             =   11 (bin)
//  DEMCODC0        0x06F0          0x20F8         iirgain[7:5]              =  111 (bin)
//  DEMCODC0        0x06F0          0x20F8         iiren[4]                  =    1 (bin)
//  DEMFEXB0        0x0A24          0x2100         out2srcsel[12:11]         =   01 (bin)
//  DEMFEXB0        0x0A24          0x2100         out1srcsel[9:8]           =   10 (bin)
//  DEMFEXB0        0x0A24          0x2100         b3srcsel[5:4]             =   10 (bin)
//  DEMFEXB0        0x0A24          0x2100         b2srcsel[3:2]             =   01 (bin)
//  DEMDSXB0        0x0006          0x2104         outsrcsel1[2]             =    1 (bin)
//  DEMDSXB0        0x0006          0x2104         b2srcsel[1]               =    1 (bin)
//  DEMFIFE0        0x000C          0x2108         iirgain[3:1]              =  110 (bin)
//  DEMMAFI1        0x3C14          0x2110         c3c5[15:8]                =   3C (hex)
//  DEMMAFI1        0x3C14          0x2110         c2c6[7:0]                 =   14 (hex)
//  DEMMAFI2        0x0078          0x2114         c4[8:0]                   =  078 (hex)
//  DEMC1BE0        0x001F          0x2118         cascconf[5:4]             =   01 (bin)
//  DEMC1BE0        0x001F          0x2118         copyconf[3:0]             =    F (hex)
//  DEMC1BE1        0x7F7F          0x211C         thresholdb[15:8]          =   7F (hex)
//  DEMC1BE1        0x7F7F          0x211C         thresholda[7:0]           =   7F (hex)
//  DEMC1BE2        0x014C          0x2120         peakconf[9:8]             =   01 (bin)
//  DEMC1BE2        0x014C          0x2120         thresholdc[7:0]           =   4C (hex)
//  SPARE0          0x0A18          0x2124         val[15:0]                 = 0A18 (hex)

