// This code snippet was auto-generated on Tue Apr 18 13:22:01 2023 using command: 
// perl $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEo$DSYNC_WORKSPACEl$DSYNC_WORKSPACEs$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEs$DSYNC_WORKSPACEm$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE2$DSYNC_WORKSPACEc$DSYNC_WORKSPACE.$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEg$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACEs$DSYNC_WORKSPACEk$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEM$DSYNC_WORKSPACED$DSYNC_WORKSPACEM$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEs$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEm$DSYNC_WORKSPACEc$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEg$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACEs$DSYNC_WORKSPACEk$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE_$DSYNC_WORKSPACEm$DSYNC_WORKSPACEd$DSYNC_WORKSPACEm$DSYNC_WORKSPACE_$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEg$DSYNC_WORKSPACE_$DSYNC_WORKSPACEg$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACEs$DSYNC_WORKSPACEk$DSYNC_WORKSPACE_$DSYNC_WORKSPACE5$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACEk$DSYNC_WORKSPACEb$DSYNC_WORKSPACEp$DSYNC_WORKSPACEs$DSYNC_WORKSPACE_$DSYNC_WORKSPACEf$DSYNC_WORKSPACEr$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE


// Source file: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/mce/genfsk/doc/lrf_mdm_cfg_genfsk_500kbps_fr.txt
// Source last modified: 18-Apr-2023 13:20

#include "lrf_mdm_cfg_genfsk_500kbps_fr.h" 

const uint32_t lrf_mdm_cfg_genfsk_500kbps_fr[LRF_MDM_CFG_GENFSK_500KBPS_FR_LENGTH] = {
    0x00000013,                        // LRF_MDM_CFG_GENFSK_500KBPS_FR_LENGTH-1
    0x20C0101D,                        // WSTART0 WREGIONID0
    0x00000003,                        //  MODPRECTRL     ADCDIGCONF    
    0x3D1F3D1F,                        //  MODSYMMAP1     MODSYMMAP0    
    0x30000000,                        //  BAUD           MODSOFTTX     
    0x0000000F,                        //  MODMAIN        BAUDPRE       
    0x00190000,                        //  DEMMISC1       DEMMISC0      
    0x048100F4,                        //  DEMMISC3       DEMMISC2      
    0x800E0000,                        //  DEMDSBU        DEMIQMC0      
    0x00000670,                        //  DEMFIDC0       DEMCODC0      
    0x000C0905,                        //  DEMDSXB0       DEMFEXB0      
    0x04000005,                        //  DEMMAFI0       DEMFIFE0      
    0x00C27C20,                        //  DEMMAFI2       DEMMAFI1      
    0x3030002F,                        //  DEMC1BE1       DEMC1BE0      
    0x0A18027F,                        //  SPARE0         DEMC1BE2      
    0x00004000,                        //  SPARE2         SPARE1        
    0x001F0000,                        //  DEMSWQU0       SPARE3        
    0x21981003,                        // WSTART1 WREGIONID1
    0x0E300670,                        //  VITBRMETRIC32  VITBRMETRIC10 
    0x06700630                         //  VITBRMETRIC76  VITBRMETRIC54 
};

// This configuration assigns values to the following register bitfields:

//  REGISTER       REG VALUE        ADDRESS        BITFIELD NAME             BITFIELD VALUE           
// -----------------------------------------------------------------------------------------------
//  ADCDIGCONF      0x0003          0x20C0         qbranchen[1]              =    1 (bin)
//  ADCDIGCONF      0x0003          0x20C0         ibranchen[0]              =    1 (bin)
//  MODSYMMAP0      0x3D1F          0x20C8         sym3[15:12]               =    3 (hex)
//  MODSYMMAP0      0x3D1F          0x20C8         sym2[11:8]                =    D (hex)
//  MODSYMMAP0      0x3D1F          0x20C8         sym1[7:4]                 =    1 (hex)
//  MODSYMMAP0      0x3D1F          0x20C8         sym0[3:0]                 =    F (hex)
//  MODSYMMAP1      0x3D1F          0x20CC         sym7[15:12]               =    3 (hex)
//  MODSYMMAP1      0x3D1F          0x20CC         sym6[11:8]                =    D (hex)
//  MODSYMMAP1      0x3D1F          0x20CC         sym5[7:4]                 =    1 (hex)
//  MODSYMMAP1      0x3D1F          0x20CC         sym4[3:0]                 =    F (hex)
//  BAUD            0x3000          0x20D4         rateword[15:0]            = 3000 (hex)
//  BAUDPRE         0x000F          0x20D8         prescaler[7:0]            =   0F (hex)
//  DEMMISC1        0x0019          0x20E4         cdccolrst[4]              =    1 (bin)
//  DEMMISC1        0x0019          0x20E4         mge1srcsel[3:2]           =   10 (bin)
//  DEMMISC1        0x0019          0x20E4         chfibw[1:0]               =   01 (bin)
//  DEMMISC2        0x00F4          0x20E8         stimteaperiod[9:7]        =  001 (bin)
//  DEMMISC2        0x00F4          0x20E8         stimteagain[6:4]          =  111 (bin)
//  DEMMISC2        0x00F4          0x20E8         pdifdespeck[2]            =    1 (bin)
//  DEMMISC3        0x0481          0x20EC         lqiperiod[11:10]          =   01 (bin)
//  DEMMISC3        0x0481          0x20EC         bde1numstages[7]          =    1 (bin)
//  DEMMISC3        0x0481          0x20EC         bde2decratio[4:0]         =   01 (hex)
//  DEMDSBU         0x800E          0x20F4         dsbuavglength[15:8]       =   80 (hex)
//  DEMDSBU         0x800E          0x20F4         dsbudelay[7:0]            =   0E (hex)
//  DEMCODC0        0x0670          0x20F8         compsel[10:9]             =   11 (bin)
//  DEMCODC0        0x0670          0x20F8         iirgain[7:5]              =  011 (bin)
//  DEMCODC0        0x0670          0x20F8         iiren[4]                  =    1 (bin)
//  DEMFEXB0        0x0905          0x2100         out2srcsel[12:11]         =   01 (bin)
//  DEMFEXB0        0x0905          0x2100         out1srcsel[9:8]           =   01 (bin)
//  DEMFEXB0        0x0905          0x2100         b2srcsel[3:2]             =   01 (bin)
//  DEMFEXB0        0x0905          0x2100         b1srcsel[1:0]             =   01 (bin)
//  DEMDSXB0        0x000C          0x2104         outsrcsel2[3]             =    1 (bin)
//  DEMDSXB0        0x000C          0x2104         outsrcsel1[2]             =    1 (bin)
//  DEMFIFE0        0x0005          0x2108         iirgain[3:1]              =  010 (bin)
//  DEMFIFE0        0x0005          0x2108         iiren[0]                  =    1 (bin)
//  DEMMAFI0        0x0400          0x210C         c1c7[15:8]                =   04 (hex)
//  DEMMAFI1        0x7C20          0x2110         c3c5[15:8]                =   7C (hex)
//  DEMMAFI1        0x7C20          0x2110         c2c6[7:0]                 =   20 (hex)
//  DEMMAFI2        0x00C2          0x2114         c4[8:0]                   =  0C2 (hex)
//  DEMC1BE0        0x002F          0x2118         cascconf[5:4]             =   10 (bin)
//  DEMC1BE0        0x002F          0x2118         copyconf[3:0]             =    F (hex)
//  DEMC1BE1        0x3030          0x211C         thresholdb[15:8]          =   30 (hex)
//  DEMC1BE1        0x3030          0x211C         thresholda[7:0]           =   30 (hex)
//  DEMC1BE2        0x027F          0x2120         peakconf[9:8]             =   10 (bin)
//  DEMC1BE2        0x027F          0x2120         thresholdc[7:0]           =   7F (hex)
//  SPARE0          0x0A18          0x2124         val[15:0]                 = 0A18 (hex)
//  SPARE1          0x4000          0x2128         val[15:0]                 = 4000 (hex)
//  DEMSWQU0        0x001F          0x2134         reflen[4:0]               =   1F (hex)
//  VITBRMETRIC10   0x0670          0x2198         met1[15:8]                =   06 (hex)
//  VITBRMETRIC10   0x0670          0x2198         met0[7:0]                 =   70 (hex)
//  VITBRMETRIC32   0x0E30          0x219C         met3[15:8]                =   0E (hex)
//  VITBRMETRIC32   0x0E30          0x219C         met2[7:0]                 =   30 (hex)
//  VITBRMETRIC54   0x0630          0x21A0         met5[15:8]                =   06 (hex)
//  VITBRMETRIC54   0x0630          0x21A0         met4[7:0]                 =   30 (hex)
//  VITBRMETRIC76   0x0670          0x21A4         met7[15:8]                =   06 (hex)
//  VITBRMETRIC76   0x0670          0x21A4         met6[7:0]                 =   70 (hex)

