// This code snippet was auto-generated on Tue Apr 18 13:25:24 2023 using command: 
// perl $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEo$DSYNC_WORKSPACEl$DSYNC_WORKSPACEs$DSYNC_WORKSPACE/$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEs$DSYNC_WORKSPACEm$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE2$DSYNC_WORKSPACEc$DSYNC_WORKSPACE.$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEm$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEm$DSYNC_WORKSPACE_$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEg$DSYNC_WORKSPACEi$DSYNC_WORKSPACEs$DSYNC_WORKSPACEt$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACEs$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE $DSYNC_WORKSPACE-$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEf$DSYNC_WORKSPACE $DSYNC_WORKSPACE/$DSYNC_WORKSPACEh$DSYNC_WORKSPACEo$DSYNC_WORKSPACEm$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEe$DSYNC_WORKSPACEv$DSYNC_WORKSPACEe$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEp$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACE/$DSYNC_WORKSPACE.$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEn$DSYNC_WORKSPACEa$DSYNC_WORKSPACEn$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACEt$DSYNC_WORKSPACEa$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEo$DSYNC_WORKSPACEk$DSYNC_WORKSPACEi$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE1$DSYNC_WORKSPACE.$DSYNC_WORKSPACE0$DSYNC_WORKSPACE0$DSYNC_WORKSPACE.$DSYNC_WORKSPACE1$DSYNC_WORKSPACE8$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEi$DSYNC_WORKSPACEb$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEr$DSYNC_WORKSPACEy$DSYNC_WORKSPACE-$DSYNC_WORKSPACEl$DSYNC_WORKSPACEp$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE/$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEg$DSYNC_WORKSPACE/$DSYNC_WORKSPACEb$DSYNC_WORKSPACEu$DSYNC_WORKSPACEi$DSYNC_WORKSPACEl$DSYNC_WORKSPACEd$DSYNC_WORKSPACE/$DSYNC_WORKSPACE7$DSYNC_WORKSPACEc$DSYNC_WORKSPACE9$DSYNC_WORKSPACE2$DSYNC_WORKSPACE8$DSYNC_WORKSPACE0$DSYNC_WORKSPACE6$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE4$DSYNC_WORKSPACEe$DSYNC_WORKSPACE4$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACE9$DSYNC_WORKSPACEd$DSYNC_WORKSPACEf$DSYNC_WORKSPACE8$DSYNC_WORKSPACEe$DSYNC_WORKSPACE8$DSYNC_WORKSPACEc$DSYNC_WORKSPACE5$DSYNC_WORKSPACE3$DSYNC_WORKSPACEe$DSYNC_WORKSPACE3$DSYNC_WORKSPACE7$DSYNC_WORKSPACE4$DSYNC_WORKSPACE6$DSYNC_WORKSPACE8$DSYNC_WORKSPACE1$DSYNC_WORKSPACE3$DSYNC_WORKSPACE0$DSYNC_WORKSPACEa$DSYNC_WORKSPACEd$DSYNC_WORKSPACEd$DSYNC_WORKSPACEa$DSYNC_WORKSPACE9$DSYNC_WORKSPACE0$DSYNC_WORKSPACE/$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACEe$DSYNC_WORKSPACE/$DSYNC_WORKSPACEc$DSYNC_WORKSPACEo$DSYNC_WORKSPACEh$DSYNC_WORKSPACEe$DSYNC_WORKSPACEr$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACEt$DSYNC_WORKSPACE_$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACEl$DSYNC_WORKSPACE/$DSYNC_WORKSPACEd$DSYNC_WORKSPACEo$DSYNC_WORKSPACEc$DSYNC_WORKSPACE/$DSYNC_WORKSPACEl$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACE_$DSYNC_WORKSPACEr$DSYNC_WORKSPACEf$DSYNC_WORKSPACEe$DSYNC_WORKSPACE_$DSYNC_WORKSPACEc$DSYNC_WORKSPACEf$DSYNC_WORKSPACEg$DSYNC_WORKSPACE_$DSYNC_WORKSPACEs$DSYNC_WORKSPACEy$DSYNC_WORKSPACEn$DSYNC_WORKSPACEt$DSYNC_WORKSPACEh$DSYNC_WORKSPACE_$DSYNC_WORKSPACEc$DSYNC_WORKSPACEp$DSYNC_WORKSPACEl$DSYNC_WORKSPACEl$DSYNC_WORKSPACE_$DSYNC_WORKSPACEr$DSYNC_WORKSPACEa$DSYNC_WORKSPACEm$DSYNC_WORKSPACE.$DSYNC_WORKSPACEt$DSYNC_WORKSPACEx$DSYNC_WORKSPACEt$DSYNC_WORKSPACE.$DSYNC_WORKSPACEa$DSYNC_WORKSPACEu$DSYNC_WORKSPACEt$DSYNC_WORKSPACEo$DSYNC_WORKSPACE_$DSYNC_WORKSPACEg$DSYNC_WORKSPACEe$DSYNC_WORKSPACEn$DSYNC_WORKSPACE


// Source file: /home/developer/.conan/data/loki-lrf/7.11.00.18/library-lprf/eng/build/7c92806c54e4cfdd9df8e8c53e37468130adda90/rfe/coherent_pll/doc/lrf_rfe_cfg_synth_cpll_ram.txt.auto_gen
// Source last modified: 18-Apr-2023 13:24

#include "lrf_rfe_cfg_synth_cpll_ram.h" 

const uint32_t lrf_rfe_cfg_synth_cpll_ram[LRF_RFE_CFG_SYNTH_CPLL_RAM_LENGTH] = {
    0x0000000E,                        // LRF_RFE_CFG_SYNTH_CPLL_RAM_LENGTH-1
    0x68045019,                        // WSTART0 WREGIONID0
    0x03000020,                        //  TDCCAL0        SYNTHCTL      
    0x00100000,                        //  TDCCAL2        TDCCAL1       
    0x569B0000,                        //  K1LSB          TDCPLL        
    0x0969010A,                        //  K2BL           K1MSB         
    0x5FDF0969,                        //  K3BL           K2AL          
    0x916F5FDF,                        //  K5             K3AL          
    0x00000000,                        //  TXIF           RXIF          
    0x00080000,                        //  RTRIMMIN       RTRIMOFF      
    0x48080008,                        //  DIVF           DIVI          
    0x00000000,                        //  DIVLDOF        DIVLDOI       
    0x00470014,                        //  LDOSETTLE      DIVLDOIOFF    
    0x0005002E,                        //  DCOSETTLE      CHRGSETTLE    
    0x0000FE00                         //  IFAMPRFLDODEFAULT  IFAMPRFLDOTX  
};

// This configuration assigns values to the following register bitfields:

//  REGISTER       REG VALUE        ADDRESS        BITFIELD NAME             BITFIELD VALUE           
// -----------------------------------------------------------------------------------------------
//  SYNTHCTL        0x0020          0x16808        chrgfilt[7]               =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        vrefbp[6]                 =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        txwaitmod[5]              =    1 (bin)
//  SYNTHCTL        0x0020          0x16808        phedisc[4]                =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        rtrimtst[3]               =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        iir[2]                    =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        refdthr[1]                =    0 (bin)
//  SYNTHCTL        0x0020          0x16808        fcdem[0]                  =    0 (bin)
//  TDCCAL0         0x0300          0x1680C        stop[10:8]                =  011 (bin)
//  TDCCAL1         0x0000          0x16810        sub[7:0]                  =   00 (hex)
//  TDCCAL2         0x0010          0x16814        avg[5:0]                  =   10 (hex)
//  TDCPLL          0x0000          0x16818        stop[10:8]                =  000 (bin)
//  K1LSB           0x569B          0x1681C        val[15:0]                 = 569B (hex)
//  K1MSB           0x010A          0x16820        val[15:0]                 = 010A (hex)
//  K2BL            0x0969          0x16824        hpm[15]                   =    0 (bin)
//  K2BL            0x0969          0x16824        val[14:0]                 = 0969 (hex)
//  K2AL            0x0969          0x16828        hpm[15]                   =    0 (bin)
//  K2AL            0x0969          0x16828        val[14:0]                 = 0969 (hex)
//  K3BL            0x5FDF          0x1682C        val[15:0]                 = 5FDF (hex)
//  K3AL            0x5FDF          0x16830        val[15:0]                 = 5FDF (hex)
//  K5              0x916F          0x16834        val[15:0]                 = 916F (hex)
//  RXIF            0x0000          0x16838        foff[11:0]                =  000 (hex)
//  TXIF            0x0000          0x1683C        foff[11:0]                =  000 (hex)
//  RTRIMOFF        0x0000          0x16840        val[3:0]                  =    0 (hex)
//  RTRIMMIN        0x0008          0x16844        val[3:0]                  =    8 (hex)
//  DIVI            0x0008          0x16848        pdet[15]                  =    0 (bin)
//  DIVI            0x0008          0x16848        nmireftrim[14:12]         =  000 (bin)
//  DIVI            0x0008          0x16848        pmireftrim[11:9]          =  000 (bin)
//  DIVI            0x0008          0x16848        txboost[8]                =    0 (bin)
//  DIVI            0x0008          0x16848        s1gfrc[7]                 =    0 (bin)
//  DIVI            0x0008          0x16848        bufgain[6:5]              =   00 (bin)
//  DIVI            0x0008          0x16848        bias[4]                   =    0 (bin)
//  DIVI            0x0008          0x16848        out[3]                    =    1 (bin)
//  DIVI            0x0008          0x16848        ratio[2:0]                =  000 (bin)
//  DIVF            0x4808          0x1684C        pdet[15]                  =    0 (bin)
//  DIVF            0x4808          0x1684C        nmireftrim[14:12]         =  100 (bin)
//  DIVF            0x4808          0x1684C        pmireftrim[11:9]          =  100 (bin)
//  DIVF            0x4808          0x1684C        txboost[8]                =    0 (bin)
//  DIVF            0x4808          0x1684C        s1gfrc[7]                 =    0 (bin)
//  DIVF            0x4808          0x1684C        bufgain[6:5]              =   00 (bin)
//  DIVF            0x4808          0x1684C        bias[4]                   =    0 (bin)
//  DIVF            0x4808          0x1684C        out[3]                    =    1 (bin)
//  DIVF            0x4808          0x1684C        ratio[2:0]                =  000 (bin)
//  DIVLDOI         0x0000          0x16850        itest[15]                 =    0 (bin)
//  DIVLDOI         0x0000          0x16850        vouttrim[14:8]            =   00 (hex)
//  DIVLDOI         0x0000          0x16850        itst[7]                   =    0 (bin)
//  DIVLDOI         0x0000          0x16850        tmux[6:4]                 =  000 (bin)
//  DIVLDOI         0x0000          0x16850        mode[2]                   =    0 (bin)
//  DIVLDOI         0x0000          0x16850        bypass[1]                 =    0 (bin)
//  DIVLDOI         0x0000          0x16850        ctl[0]                    =    0 (bin)
//  DIVLDOF         0x0000          0x16854        itest[15]                 =    0 (bin)
//  DIVLDOF         0x0000          0x16854        vouttrim[14:8]            =   00 (hex)
//  DIVLDOF         0x0000          0x16854        itst[7]                   =    0 (bin)
//  DIVLDOF         0x0000          0x16854        tmux[6:4]                 =  000 (bin)
//  DIVLDOF         0x0000          0x16854        mode[2]                   =    0 (bin)
//  DIVLDOF         0x0000          0x16854        bypass[1]                 =    0 (bin)
//  DIVLDOF         0x0000          0x16854        ctl[0]                    =    0 (bin)
//  DIVLDOIOFF      0x0014          0x16858        val[6:0]                  =   14 (hex)
//  LDOSETTLE       0x0047          0x1685C        val[9:0]                  =  047 (hex)
//  CHRGSETTLE      0x002E          0x16860        val[9:0]                  =  02E (hex)
//  DCOSETTLE       0x0005          0x16864        val[9:0]                  =  005 (hex)
//  IFAMPRFLDOTX    0xFE00          0x16868        trim[15:9]                =   7F (hex)
//  IFAMPRFLDODEFAULT   0x0000          0x1686C        trim[15:9]                =   00 (hex)

