#!/usr/bin/env python3
"""
MS-OAD Post-build Script

Executes all post-build steps for MS-OAD (Multistep Over-the-Air Download):
  1-2. Extract bootable and non-bootable images from .out file
       - TI-Clang: uses tiarmhex with tiarmreadelf for segment sizes
       - IAR: uses ielftool with computed slot boundaries
  3-6. Sign bootable and non-bootable images with MCUBoot (v1 and v2)
  7-8. Assemble final flash images (v1 and v2)

This script consolidates all MS-OAD post-build commands into a single executable,
making it easier to manage and allowing the build to fail properly if any step fails.

Usage:
    msoad_postbuild [--compiler ticlang|iar]
                    --build_dir <path> --base_name <name> --cg_tool_root <path> --sdk_dir <path>
                    --app1_origin <hex> --app2_origin <hex> --app_size <hex>
                    --swap_size <bytes> --state_size <bytes> --key <path> --version <ver>
                    [--version2 <ver>]

Arguments:
    --compiler      Compiler toolchain: ticlang (default) or iar
    --build_dir     Build output directory (where .out file is located)
    --base_name     Build artifact base name (e.g., basic_ble_multistep_oad)
    --cg_tool_root  Path to compiler root (TI-Clang CG_TOOL_ROOT or IAR TOOLKIT_DIR)
    --sdk_dir       Path to SDK installation directory
    --app1_origin   APP_1_SLOT origin address in hex (e.g., 0x6100)
    --app2_origin   APP_2_SLOT origin address in hex (e.g., 0x41900)
    --app_size      Application slot size in hex (e.g., 0x3B000)
    --swap_size     Swap slot size in bytes (e.g., 2048)
    --state_size    MS-OAD state slot size in bytes (e.g., 2048)
    --key           Path to MCUBoot signing key (.pem file)
    --version       Image version for V1 (e.g., 1.2.3)
    --version2      Image version for V2 (optional, e.g., 2.3.4). If not provided,
                    only V1 images are generated.

Example (TI-Clang, two versions):
    msoad_postbuild --build_dir ./Release --base_name basic_ble_multistep_oad \\
                    --cg_tool_root /ti/compiler --sdk_dir /ti/sdk \\
                    --app1_origin 0x6100 --app2_origin 0x41900 --app_size 0x3B000 \\
                    --swap_size 2048 --state_size 2048 --version 1.0.0 --version2 2.0.0 \\
                    --key /ti/sdk/source/third_party/mcuboot/root-ec-p256.pem

Example (IAR, two versions):
    msoad_postbuild --compiler iar \\
                    --build_dir "$TARGET_DIR$" \\
                    --base_name "$TARGET_BNAME$" \\
                    --cg_tool_root "$TOOLKIT_DIR$" --sdk_dir /ti/sdk \\
                    --app1_origin 0x6100 --app2_origin 0x41900 --app_size 0x3B000 \\
                    --swap_size 2048 --state_size 2048 --version 1.0.0 --version2 2.0.0 \\
                    --key /ti/sdk/source/third_party/mcuboot/root-ec-p256.pem

Compiling to Standalone Executable:
    This script can be compiled into a standalone executable using PyInstaller.

    Prerequisites:
        pip install pyinstaller

    Linux:
        cd <SDK>/tools/ble/oad
        pyinstaller --onefile --name msoad_postbuild msoad_postbuild.py
        mv dist/msoad_postbuild .
        rm -rf dist build msoad_postbuild.spec

    Windows (run in Command Prompt or PowerShell):
        cd <SDK>\\tools\\ble\\oad
        pyinstaller --onefile --name msoad_postbuild msoad_postbuild.py
        move dist\\msoad_postbuild.exe .
        rmdir /s /q dist build
        del msoad_postbuild.spec
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Tuple, Optional

# Environment variable set by msoad_prebuild during test build
# When this is set, we skip post-build steps since we're in prebuild phase
MSOAD_PREBUILD_ENV = "MSOAD_PREBUILD_RUNNING"

# MS-OAD memory layout constants
MCU_HDR_SIZE = 0x100
MCUBOOT_SIZE = 0x6000


def log(message: str, flush: bool = True) -> None:
    """Print a message with prefix."""
    print(f"[MS-OAD Postbuild] {message}", flush=flush)


def clean_generated_files(build_dir: Path, base_name: str) -> bool:
    """
    Clean all generated files from previous MS-OAD post-build runs.

    This function removes all output files that are generated by the post-build
    script, ensuring a clean state before generating new files.

    Args:
        build_dir: Build output directory
        base_name: Base name of build artifact

    Returns:
        True if all files were cleaned successfully, False if any removal failed
    """
    # List of all generated file patterns
    generated_files = [
        # Extracted images (steps 1-2)
        f"{base_name}_bootable.bin",
        f"{base_name}_nonbootable.bin",
        # Signed images (steps 3-6)
        f"{base_name}_bootable_signed_v1.bin",
        f"{base_name}_nonbootable_signed_v1.bin",
        f"{base_name}_bootable_signed_v2.bin",
        f"{base_name}_nonbootable_signed_v2.bin",
        # Final flash images (steps 7-8)
        f"{base_name}_to_flash_v1.bin",
        f"{base_name}_to_flash_v2.bin",
        # Temporary files (normally cleaned up, but ensure removal)
        "extractRegions.cmd",
        f"{base_name}_erased_swap.bin",
        f"{base_name}_erased_msoad.bin",
    ]

    cleaned_count = 0
    failed = False
    for filename in generated_files:
        filepath = build_dir / filename
        if filepath.exists():
            try:
                filepath.unlink()
                log(f"  Removed: {filename}")
                cleaned_count += 1
            except Exception as e:
                log(f"  ERROR: Could not remove {filename}: {e}")
                failed = True

    if cleaned_count == 0:
        log(f"  No previous generated files found")
    else:
        log(f"  Cleaned {cleaned_count} file(s)")

    return not failed


def get_segment_size_from_readelf(readelf: Path, out_file: Path, phys_addr: int,
                                   end_addr: Optional[int] = None) -> Optional[int]:
    """
    Get total span of LOAD segments from ELF program headers using tiarmreadelf.

    Finds all LOAD segments whose PhysAddr falls within [phys_addr, end_addr)
    and returns the total span from phys_addr to the end of the last segment.
    This handles cases where a memory range is split into multiple linker
    regions (e.g., INIT_SLOT + APP_1_SLOT) that produce separate ELF segments.

    If end_addr is not provided, only matches an exact PhysAddr (legacy behavior).

    Args:
        readelf: Path to tiarmreadelf executable
        out_file: Path to the .out (ELF) file
        phys_addr: Start address of the range (e.g., 0x6100)
        end_addr: End address of the range (exclusive), or None for exact match

    Returns:
        Total span in bytes from phys_addr to end of last segment,
        or None if no segment found in the range

    Raises:
        RuntimeError: If readelf command fails
    """
    result = subprocess.run(
        [str(readelf), '-l', str(out_file)],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        log(f"  ERROR: tiarmreadelf failed: {result.stderr}")
        raise RuntimeError(f"tiarmreadelf failed: {result.stderr}")

    # Parse all LOAD segments
    # Format: "LOAD  0x000040 0x00006100 0x00006100 0x30744 0x30744 R E 0x10"
    #         Type  Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
    matched_segments = []
    max_end = None
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 6 and parts[0] == 'LOAD':
            seg_addr = int(parts[3], 16)
            seg_size = int(parts[5], 16)

            if end_addr is not None:
                # Range mode: match any segment within [phys_addr, end_addr)
                if phys_addr <= seg_addr < end_addr and seg_size > 0:
                    matched_segments.append((seg_addr, seg_size))
                    seg_end = seg_addr + seg_size
                    if max_end is None or seg_end > max_end:
                        max_end = seg_end
            else:
                # Exact match mode (legacy)
                if seg_addr == phys_addr:
                    log(f"    Segment at 0x{seg_addr:X}, size 0x{seg_size:X} ({seg_size} bytes)")
                    return seg_size

    if matched_segments:
        total_span = max_end - phys_addr
        log(f"    Found {len(matched_segments)} segment(s) in range [0x{phys_addr:X}, 0x{end_addr:X}):")
        for seg_addr, seg_size in sorted(matched_segments):
            log(f"      Segment at 0x{seg_addr:X}, size 0x{seg_size:X} ({seg_size} bytes)")
        log(f"    Total span: 0x{phys_addr:X} - 0x{max_end:X} = 0x{total_span:X} ({total_span} bytes)")
        return total_span

    return None


def extract_slot_images_iar(out_file: Path, cg_tool_root: Path,
                            app1_origin: int, app2_origin: int,
                            app_size: int,
                            base_name: str, build_dir: Path) -> Tuple[int, Path, Path]:
    """
    Extract bootable and non-bootable images using IAR ielftool.

    Uses ielftool --bin to extract each slot's memory region directly.
    The slot boundaries are computed from the origin addresses and slot size.
    ielftool extracts only the ELF content within the specified range.

    If APP_2_SLOT is empty (no content at that address range), creates an empty
    nonbootable.bin file.

    Args:
        out_file: Path to the .out (ELF) file
        cg_tool_root: Path to IAR TOOLKIT_DIR (contains bin/ directory)
        app1_origin: Origin address of APP_1_SLOT (bootable)
        app2_origin: Origin address of APP_2_SLOT (non-bootable)
        app_size: Slot size in bytes (the imgtool --slot-size value)
        base_name: Base name for output files
        build_dir: Build directory

    Returns:
        Tuple of (return_code, bootable_path, nonbootable_path)

    Raises:
        RuntimeError: If tools not found or extraction fails
    """
    bootable_bin = build_dir / f"{base_name}_bootable.bin"
    nonbootable_bin = build_dir / f"{base_name}_nonbootable.bin"

    # Tool path
    ielftool = cg_tool_root / "bin" / "ielftool"

    # Verify tool exists
    if not ielftool.exists() and not Path(str(ielftool) + ".exe").exists():
        log(f"  ERROR: Tool not found: {ielftool}")
        raise RuntimeError(f"Tool not found: {ielftool}")

    # Compute slot end addresses (inclusive for ielftool)
    # Each slot is app_size total; code starts after MCU_HDR_SIZE header
    max_code_size = app_size - MCU_HDR_SIZE
    app1_end = app1_origin + max_code_size - 1
    app2_end = app2_origin + max_code_size - 1

    log(f"  APP_1_SLOT: 0x{app1_origin:X} - 0x{app1_end:X}")
    log(f"  APP_2_SLOT: 0x{app2_origin:X} - 0x{app2_end:X}")

    # Extract APP_1_SLOT using ielftool --bin
    cmd = f'"{ielftool}" --bin=0x{app1_origin:X}-0x{app1_end:X} "{out_file}" "{bootable_bin}"'
    log(f"  Running ielftool for bootable image...")
    result = subprocess.run(cmd, shell=True, cwd=build_dir, capture_output=True, text=True)
    if result.returncode != 0:
        log(f"  ERROR: ielftool failed: {result.stderr}")
        raise RuntimeError(f"ielftool failed for bootable image: {result.stderr}")

    if not bootable_bin.exists():
        log(f"  ERROR: Bootable image not created: {bootable_bin}")
        raise RuntimeError(f"Bootable image not created: {bootable_bin}")

    # Extract APP_2_SLOT - may be empty if all code fits in APP_1_SLOT
    cmd = f'"{ielftool}" --bin=0x{app2_origin:X}-0x{app2_end:X} "{out_file}" "{nonbootable_bin}"'
    log(f"  Running ielftool for non-bootable image...")
    result = subprocess.run(cmd, shell=True, cwd=build_dir, capture_output=True, text=True)
    if result.returncode != 0 or not nonbootable_bin.exists() or nonbootable_bin.stat().st_size == 0:
        log(f"  APP_2_SLOT: empty (no content in range)")
        log(f"  Creating empty non-bootable image")
        nonbootable_bin.touch()

    log(f"  Bootable image: {bootable_bin.stat().st_size} bytes (0x{bootable_bin.stat().st_size:X})")
    log(f"  Non-bootable image: {nonbootable_bin.stat().st_size} bytes (0x{nonbootable_bin.stat().st_size:X})")

    return (0, bootable_bin, nonbootable_bin)


def generate_extract_regions_cmd(cmd_file: Path, slot1_origin: int, slot1_size: int,
                                  slot1_file: str,
                                  slot2_origin: Optional[int] = None,
                                  slot2_size: Optional[int] = None,
                                  slot2_file: Optional[str] = None) -> None:
    """
    Generate tiarmhex command file for extracting memory regions.

    Args:
        cmd_file: Path to write the command file
        slot1_origin: Origin address of APP_1_SLOT
        slot1_size: Size of APP_1_SLOT content in bytes
        slot1_file: Output filename for slot 1
        slot2_origin: Origin address of APP_2_SLOT (optional)
        slot2_size: Size of APP_2_SLOT content in bytes (optional)
        slot2_file: Output filename for slot 2 (optional)
    """
    # Build ROMS section - always include slot 1
    roms_content = f"""    APP_1_SLOT: origin=0x{slot1_origin:X} length=0x{slot1_size:X}
               files={{{slot1_file}}}"""

    # Only include slot 2 if it has content
    if slot2_origin is not None and slot2_size is not None and slot2_file is not None:
        roms_content += f"""

    APP_2_SLOT: origin=0x{slot2_origin:X} length=0x{slot2_size:X}
               files={{{slot2_file}}}"""

    content = f"""--memwidth=8
--romwidth=8
--binary
--image
--fill=0x00

ROMS
{{
{roms_content}
}}
"""
    with open(cmd_file, 'w') as f:
        f.write(content)

def extract_slot_images(out_file: Path, cg_tool_root: Path,
                        app1_origin: int, app2_origin: int,
                        base_name: str, build_dir: Path) -> Tuple[int, Path, Path]:
    """
    Extract bootable and non-bootable images using tiarmhex with tiarmreadelf for sizes.

    Uses tiarmreadelf to get exact segment sizes from ELF program headers,
    then generates a tiarmhex command file to extract each slot with proper
    gap filling and no trailing padding.

    If APP_2_SLOT is empty (no segment at that address), creates an empty
    nonbootable.bin file.

    Args:
        out_file: Path to the .out (ELF) file
        cg_tool_root: Path to TI-CLANG compiler root (contains bin/ directory)
        app1_origin: Origin address of APP_1_SLOT (bootable)
        app2_origin: Origin address of APP_2_SLOT (non-bootable)
        base_name: Base name for output files
        build_dir: Build directory

    Returns:
        Tuple of (return_code, bootable_path, nonbootable_path)

    Raises:
        RuntimeError: If tools not found or extraction fails
    """
    bootable_bin = build_dir / f"{base_name}_bootable.bin"
    nonbootable_bin = build_dir / f"{base_name}_nonbootable.bin"

    # Tool paths
    readelf = cg_tool_root / "bin" / "tiarmreadelf"
    tiarmhex = cg_tool_root / "bin" / "tiarmhex"

    # Verify tools exist
    for tool in [readelf, tiarmhex]:
        if not tool.exists() and not Path(str(tool) + ".exe").exists():
            log(f"  ERROR: Tool not found: {tool}")
            raise RuntimeError(f"Tool not found: {tool}")

    log(f"  APP_1_SLOT: origin=0x{app1_origin:X}")
    log(f"  APP_2_SLOT: origin=0x{app2_origin:X}")

    # Get actual segment sizes from ELF program headers using tiarmreadelf
    # Use range mode to capture all segments within each slot's address range
    # (e.g., INIT_SLOT + APP_1_SLOT both contribute to the bootable image)
    log(f"  Reading segment sizes from ELF program headers...")

    app1_size = get_segment_size_from_readelf(readelf, out_file, app1_origin, end_addr=app2_origin)
    app2_size = get_segment_size_from_readelf(readelf, out_file, app2_origin)

    # APP_1_SLOT must exist
    if app1_size is None:
        log(f"  ERROR: Segment not found at address 0x{app1_origin:X}")
        raise RuntimeError(f"Segment not found at address 0x{app1_origin:X}")

    log(f"  APP_1_SLOT actual size: 0x{app1_size:X} ({app1_size} bytes)")

    # APP_2_SLOT may be empty if all code fits in APP_1_SLOT
    if app2_size is None:
        log(f"  APP_2_SLOT: empty (no segment at this address)")
        log(f"  Creating empty non-bootable image")
    else:
        log(f"  APP_2_SLOT actual size: 0x{app2_size:X} ({app2_size} bytes)")

    # Generate tiarmhex command file
    cmd_file = build_dir / "extractRegions.cmd"
    if app2_size is not None:
        # Both slots have content
        generate_extract_regions_cmd(
            cmd_file,
            app1_origin, app1_size, bootable_bin.name,
            app2_origin, app2_size, nonbootable_bin.name
        )
    else:
        # Only APP_1_SLOT has content
        generate_extract_regions_cmd(
            cmd_file,
            app1_origin, app1_size, bootable_bin.name
        )
    log(f"  Generated {cmd_file.name}")

    # Run tiarmhex to extract slot(s)
    cmd = f'"{tiarmhex}" "{out_file}" "{cmd_file}"'
    log(f"  Running tiarmhex...")

    result = subprocess.run(cmd, shell=True, cwd=build_dir, capture_output=True, text=True)
    if result.returncode != 0:
        log(f"  ERROR: tiarmhex failed: {result.stderr}")
        raise RuntimeError(f"tiarmhex failed: {result.stderr}")

    # Verify bootable output file was created
    if not bootable_bin.exists():
        log(f"  ERROR: Bootable image not created: {bootable_bin}")
        raise RuntimeError(f"Bootable image not created: {bootable_bin}")

    # Create empty nonbootable.bin if APP_2_SLOT was empty
    if app2_size is None:
        nonbootable_bin.touch()

    # Verify nonbootable output file exists
    if not nonbootable_bin.exists():
        log(f"  ERROR: Non-bootable image not created: {nonbootable_bin}")
        raise RuntimeError(f"Non-bootable image not created: {nonbootable_bin}")

    log(f"  Bootable image: {bootable_bin.stat().st_size} bytes (0x{bootable_bin.stat().st_size:X})")
    log(f"  Non-bootable image: {nonbootable_bin.stat().st_size} bytes (0x{nonbootable_bin.stat().st_size:X})")

    # Cleanup temporary command file
    cmd_file.unlink()

    return (0, bootable_bin, nonbootable_bin)


def create_filled_file(filepath: Path, size: int, fill_byte: int) -> None:
    """Create a file filled with a specified byte value."""
    with open(filepath, 'wb') as f:
        f.write(bytes([fill_byte]) * size)


def concatenate_files(output_path: Path, input_paths: list) -> bool:
    """
    Concatenate multiple binary files into one.

    Returns:
        True on success, False on failure
    """
    try:
        with open(output_path, 'wb') as outfile:
            for input_path in input_paths:
                if not input_path.exists():
                    log(f"ERROR: Input file not found: {input_path}")
                    return False
                with open(input_path, 'rb') as infile:
                    outfile.write(infile.read())
        return True
    except Exception as e:
        log(f"ERROR: Failed to concatenate files: {e}")
        return False


def assemble_flash_image(build_dir: Path, base_name: str, version: str,
                         swap_size: int, state_size: int) -> int:
    """
    Assemble MS-OAD flash image by combining:
      - bootable_signed binary
      - erased swap slot (0xFF filled)
      - nonbootable_signed binary
      - erased ms-oad state slot (0xFF filled)

    Layout: bootable_signed + erased_swap + nonbootable_signed + erased_msoad

    Args:
        build_dir: Build output directory
        base_name: Base name of build artifact
        version: Version string (v1 or v2)
        swap_size: Size of swap slot in bytes
        state_size: Size of MS-OAD state slot in bytes

    Returns:
        0 on success, 1 on failure
    """
    # Define file paths
    bootable_signed = build_dir / f"{base_name}_bootable_signed_{version}.bin"
    nonbootable_signed = build_dir / f"{base_name}_nonbootable_signed_{version}.bin"
    erased_swap = build_dir / f"{base_name}_erased_swap.bin"
    erased_state = build_dir / f"{base_name}_erased_msoad.bin"
    output_file = build_dir / f"{base_name}_to_flash_{version}.bin"

    # Create filler files
    log(f"  Creating erased swap ({swap_size} bytes, 0xFF filled)")
    create_filled_file(erased_swap, swap_size, 0xFF)

    log(f"  Creating erased state ({state_size} bytes, 0xFF filled)")
    create_filled_file(erased_state, state_size, 0xFF)

    # Concatenate all files
    log(f"  Concatenating: bootable + swap + nonbootable + state")
    if not concatenate_files(output_file, [
        bootable_signed,
        erased_swap,
        nonbootable_signed,
        erased_state
    ]):
        return 1

    # Report size
    total_size = output_file.stat().st_size
    log(f"  Created {output_file.name} ({total_size} bytes, 0x{total_size:X})")

    # Cleanup temporary files
    erased_swap.unlink()
    erased_state.unlink()

    return 0


def run_command(cmd: str, description: str, cwd: Path) -> int:
    """
    Run a shell command and return the exit code.

    Args:
        cmd: Command string to execute
        description: Human-readable description of the step
        cwd: Working directory for the command

    Returns:
        0 on success, non-zero on failure
    """
    log(f"Step: {description}")
    log(f"  Command: {cmd}")

    try:
        # Use shell=True to handle command strings with spaces and special characters
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd,
            capture_output=False
        )

        if result.returncode != 0:
            log(f"  FAILED with exit code {result.returncode}")
            return result.returncode

        log(f"  SUCCESS")
        return 0

    except Exception as e:
        log(f"  ERROR: {e}")
        return 1


def main():
    # Check if we're in prebuild mode - skip all post-build steps
    if os.environ.get(MSOAD_PREBUILD_ENV):
        log("Prebuild mode detected (MSOAD_PREBUILD_RUNNING is set) - skipping post-build steps")
        return 0

    parser = argparse.ArgumentParser(
        description='MS-OAD Post-build: Extract, sign, and assemble MS-OAD images'
    )
    parser.add_argument('--compiler', choices=['ticlang', 'iar'], default='ticlang',
                        help='Compiler toolchain (default: ticlang)')
    parser.add_argument('--build_dir', required=True, help='Build output directory (where .out file is)')
    parser.add_argument('--base_name', required=True, help='Build artifact base name (e.g., basic_ble_multistep_oad)')
    parser.add_argument('--cg_tool_root', required=True, help='Path to compiler root (TI-Clang CG_TOOL_ROOT or IAR TOOLKIT_DIR)')
    parser.add_argument('--sdk_dir', required=True, help='Path to SDK installation directory')
    parser.add_argument('--app1_origin', required=True, help='APP_1_SLOT origin address in hex (e.g., 0x6100)')
    parser.add_argument('--app2_origin', required=True, help='APP_2_SLOT origin address in hex (e.g., 0x41900)')
    parser.add_argument('--app_size', required=True, help='Application slot size in hex (e.g., 0x3B000)')
    parser.add_argument('--swap_size', required=True, type=int, help='Swap slot size in bytes (e.g., 2048)')
    parser.add_argument('--state_size', required=True, type=int, help='MS-OAD state slot size in bytes (e.g., 2048)')
    parser.add_argument('--key', required=True, help='Path to MCUBoot signing key (.pem file)')
    parser.add_argument('--version', required=True, help='Image version for V1 (e.g., 1.2.3)')
    parser.add_argument('--version2', required=False, default=None, help='Image version for V2 (optional). If not provided, only V1 images are generated.')

    args = parser.parse_args()

    compiler = args.compiler
    build_dir = Path(args.build_dir).resolve()
    base_name = args.base_name
    cg_tool_root = Path(args.cg_tool_root)
    sdk_dir = Path(args.sdk_dir)
    app1_origin = int(args.app1_origin, 16) if args.app1_origin.startswith('0x') else int(args.app1_origin, 16)
    app2_origin = int(args.app2_origin, 16) if args.app2_origin.startswith('0x') else int(args.app2_origin, 16)
    app_size = args.app_size
    swap_size = args.swap_size
    state_size = args.state_size
    key_path = Path(args.key)
    version1 = args.version
    version2 = args.version2
    dual_version_mode = version2 is not None

    log("")
    log("=" * 60)
    log(">>> MS-OAD Post-build Script <<<")
    log("=" * 60)
    log(f"Build directory: {build_dir}")
    log(f"Base name: {base_name}")
    log(f"Compiler: {compiler}")
    log(f"Compiler root: {cg_tool_root}")
    log(f"SDK: {sdk_dir}")
    log(f"APP_1_SLOT origin: 0x{app1_origin:X}")
    log(f"APP_2_SLOT origin: 0x{app2_origin:X}")
    log(f"App size: {app_size}")
    log(f"Swap size: {swap_size}")
    log(f"State size: {state_size}")
    log(f"Key: {key_path}")
    log(f"Version (V1): {version1}")
    if dual_version_mode:
        log(f"Version (V2): {version2}")
    else:
        log(f"Version (V2): Not specified (single version mode)")
    log("")

    # Verify paths exist
    out_file = build_dir / f"{base_name}.out"
    if not out_file.exists():
        log(f"ERROR: Output file not found: {out_file}")
        return 1

    imgtool = sdk_dir / "tools/common/mcuboot/imgtool"
    if not imgtool.exists() and not Path(str(imgtool) + ".exe").exists():
        log(f"ERROR: imgtool not found: {imgtool}")
        return 1

    # Total steps: 1 clean, 2-3 extract, 4-5 sign V1, (6-7 sign V2), 8 assemble V1, (9 assemble V2)
    total_steps = 6 if not dual_version_mode else 9

    # Step 1: Clean previous generated files
    log("-" * 60)
    log("")
    log(f"[1/{total_steps}] Clean previous generated files")
    if not clean_generated_files(build_dir, base_name):
        log("")
        log("=" * 60)
        log(f">>> MS-OAD Post-build FAILED at step 1/{total_steps} <<<")
        log("=" * 60)
        return 1
    log("  SUCCESS")

    # Step 2 & 3: Extract bootable and non-bootable images
    # Uses tiarmreadelf to get segment sizes and tiarmhex to extract memory regions
    log("-" * 60)
    log("")
    log(f"[2-3/{total_steps}] Extract bootable and non-bootable images")

    log(f"  Using {'ielftool' if compiler == 'iar' else 'tiarmhex'} extraction")
    try:
        if compiler == 'iar':
            app_size_int = int(app_size, 16)
            result, bootable_path, nonbootable_path = extract_slot_images_iar(
                out_file, cg_tool_root, app1_origin, app2_origin, app_size_int, base_name, build_dir
            )
        else:
            result, bootable_path, nonbootable_path = extract_slot_images(
                out_file, cg_tool_root, app1_origin, app2_origin, base_name, build_dir
            )
    except RuntimeError as e:
        log("")
        log("=" * 60)
        log(f">>> MS-OAD Post-build FAILED at step 2-3/{total_steps} <<<")
        log("=" * 60)
        return 1
    if result != 0:
        log("")
        log("=" * 60)
        log(f">>> MS-OAD Post-build FAILED at step 2-3/{total_steps} <<<")
        log("=" * 60)
        return result
    log("  SUCCESS")

    # Define signing steps (steps 4-5 for V1, 6-7 for V2 if dual_version_mode)
    sign_steps = [
        # Step 4: Sign bootable V1
        {
            "description": f"Sign bootable image (V1, version {version1})",
            "command": f'"{imgtool}" sign --header-size 0x100 --align 4 --slot-size {app_size} '
                       f'--version {version1} --pad-header --pad --key "{key_path}" '
                       f'{base_name}_bootable.bin {base_name}_bootable_signed_v1.bin'
        },
        # Step 5: Sign non-bootable V1
        {
            "description": f"Sign non-bootable image (V1, version {version1})",
            "command": f'"{imgtool}" sign --header-size 0x100 --align 4 --slot-size {app_size} '
                       f'--version {version1} --pad-header --pad --non-bootable --key "{key_path}" '
                       f'{base_name}_nonbootable.bin {base_name}_nonbootable_signed_v1.bin'
        },
    ]

    # Add V2 signing steps only if dual_version_mode
    if dual_version_mode:
        sign_steps.extend([
            # Step 6: Sign bootable V2
            {
                "description": f"Sign bootable image (V2, version {version2})",
                "command": f'"{imgtool}" sign --header-size 0x100 --align 4 --slot-size {app_size} '
                           f'--version {version2} --pad-header --pad --key "{key_path}" '
                           f'{base_name}_bootable.bin {base_name}_bootable_signed_v2.bin'
            },
            # Step 7: Sign non-bootable V2
            {
                "description": f"Sign non-bootable image (V2, version {version2})",
                "command": f'"{imgtool}" sign --header-size 0x100 --align 4 --slot-size {app_size} '
                           f'--version {version2} --pad-header --pad --non-bootable --key "{key_path}" '
                           f'{base_name}_nonbootable.bin {base_name}_nonbootable_signed_v2.bin'
            },
        ])

    # Execute signing steps (4-5 for single version, 4-7 for dual version)
    for i, step in enumerate(sign_steps, 4):
        log(f"")
        log(f"[{i}/{total_steps}] {step['description']}")
        result = run_command(step["command"], step["description"], build_dir)
        if result != 0:
            log("")
            log("=" * 60)
            log(f">>> MS-OAD Post-build FAILED at step {i}/{total_steps} <<<")
            log("=" * 60)
            return result

    # Step 6 (single) or 8 (dual): Assemble V1 flash image
    assemble_v1_step = 6 if not dual_version_mode else 8
    log(f"")
    log(f"[{assemble_v1_step}/{total_steps}] Assemble V1 flash image")
    result = assemble_flash_image(build_dir, base_name, "v1", swap_size, state_size)
    if result != 0:
        log("")
        log("=" * 60)
        log(f">>> MS-OAD Post-build FAILED at step {assemble_v1_step}/{total_steps} <<<")
        log("=" * 60)
        return result
    log(f"  SUCCESS")

    # Step 9: Assemble V2 flash image (only if dual_version_mode)
    if dual_version_mode:
        log(f"")
        log(f"[9/{total_steps}] Assemble V2 flash image")
        result = assemble_flash_image(build_dir, base_name, "v2", swap_size, state_size)
        if result != 0:
            log("")
            log("=" * 60)
            log(f">>> MS-OAD Post-build FAILED at step 9/{total_steps} <<<")
            log("=" * 60)
            return result
        log(f"  SUCCESS")

    log("")
    log("-" * 60)
    log("All post-build steps completed successfully!")
    log(f"Output files:")
    log(f"  {base_name}_bootable_signed_v1.bin")
    log(f"  {base_name}_nonbootable_signed_v1.bin")
    if dual_version_mode:
        log(f"  {base_name}_bootable_signed_v2.bin")
        log(f"  {base_name}_nonbootable_signed_v2.bin")
    log(f"  {base_name}_to_flash_v1.bin")
    if dual_version_mode:
        log(f"  {base_name}_to_flash_v2.bin")
    log("-" * 60)
    log("")
    log("=" * 60)
    log(">>> MS-OAD Post-build Script Completed <<<")
    log("=" * 60)
    log("")

    return 0


if __name__ == '__main__':
    sys.exit(main())
