// ===========================================================================
// This file is autogenerated, please DO NOT modify!
//
// Generated on  2023-12-05 12:18:16
// by user:      developer
// on machine:   swtools
// CWD:          /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/build/highlrfbledig/iar/pbe/ieee
// Commandline:  /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/../tools/topsm/regtxtconv.pl -x /home/developer/.conan/data/f65lokihighlrfbledig/1.3.7-3/library-lprf/eng/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/source/ti.com_LOKI_LRFBLEDIG_1.0.xml -f acr --devices CC2745P10Q1:A (1.0) /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/pbe/ieee/doc/pbe_ble5_regdef_regs.txt /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/pbe/ieee/doc/pbe_ieee_ram_regs.txt
// C&P friendly: /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/../tools/topsm/regtxtconv.pl -x /home/developer/.conan/data/f65lokihighlrfbledig/1.3.7-3/library-lprf/eng/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/source/ti.com_LOKI_LRFBLEDIG_1.0.xml -f acr --devices CC2745P10Q1:A (1.0) /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/pbe/ieee/doc/pbe_ble5_regdef_regs.txt /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/pbe/ieee/doc/pbe_ieee_ram_regs.txt
//
// Relevant file version(s):
//
// /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/../tools/topsm/regtxtconv.pl
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: 68a752a8737845355f7bdb320d25a59eac685840
//
// /home/developer/.conan/data/loki-lrf/7.40.01.13/library-lprf/ga/build/0c46501566d33cb4afdce9818f8c3e61ffe04c9a/highlrfbledig/pbe/ieee/doc/pbe_ieee_ram_regs.txt
//   rcs-info: (file not managed or unknown revision control system)
//   git-hash: c58468857ac54caf18f18e6f2318390592a57ff7
//
// ===========================================================================


#ifndef __PBE_IEEE_RAM_REGS_H
#define __PBE_IEEE_RAM_REGS_H

//******************************************************************************
// REGISTER OFFSETS
//******************************************************************************

#endif // __PBE_IEEE_RAM_REGS_H
