/*
 * This file contains the same symbols generated by GenMaps and SysConfig,
 * intended to make the device-specific F3 linker files compatible with the
 * CRC tool.
 */

ti_utils_build_GenMap_sym_CRC_CCFG_BOOT_CFG_begin = 0x4e020000;
ti_utils_build_GenMap_sym_CRC_CCFG_BOOT_CFG_end = 0x4e02000b;
ti_utils_build_GenMap_sym_CRC_CCFG_begin = 0x4e020010;
ti_utils_build_GenMap_sym_CRC_CCFG_end = 0x4e02074b;
ti_utils_build_GenMap_sym_CRC_CCFG_DEBUG_begin = 0x4e0207d0;
ti_utils_build_GenMap_sym_CRC_CCFG_DEBUG_end = 0x4e0207fb;
ti_utils_build_GenMap_sym_CRC_CCFG_USER_RECORD_begin = 0x4e020750;
ti_utils_build_GenMap_sym_CRC_CCFG_USER_RECORD_end = 0x4e0207cb;